Repository ODIM-Project/ODIM, pull requests merged in 2020-12, with the labels that each got.

#260 Issue #259 migrate logging to logrus(svc-update)
  svc-update/main.go
  svc-update/rpc/common.go
  svc-update/rpc/update.go
  svc-update/ucommon/common.go
  svc-update/umodel/update.go
  svc-update/update/getresources.go
  svc-update/update/simpleUpdate.go
  svc-update/update/startUpdate.go
Labels: enhancement

#263 issue 256: Event JSON payload with multiple events
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
Labels: enhancement

#269 Odim 266 - Added rediscovery for ResourceAdded/ResourceRemoved events for a volume origin of condition
  svc-events/events/publishevttosubscriber.go
Labels: enhancement

#272 ODIM-268 Name field of aggregation source should be of form <ConnectionMethodType>-<Hostname>
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/common.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/connectionmethods_test.go
  svc-aggregation/system/get_resource.go
  svc-aggregation/system/get_resource_test.go
Labels: Aggregation Service

#265 Issue 259 - Update main.go of svc-update for fixing logger issue
  svc-update/go.mod
  svc-update/go.sum
  svc-update/main.go
  svc-update/rpc/update.go
  svc-update/ucommon/common.go
Labels: enhancement

#255 Issue number- 245: updated docs/readme, svc-aggregation/readme, svc-systems/readme, svc-update/readme files
  docs/README.md
  svc-aggregation/README.md
  svc-events/README.md
  svc-systems/README.md
  svc-update/README.md
Labels: documentation

#271 Issue 267 - Add plugin should use UUID of /ODIM/v1/Managers payload
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/system/addplugin.go
Labels: Aggregation Service

#262 Storage indexes are updating with wrong ID's
  svc-aggregation/agmodel/system.go
  svc-aggregation/system/common.go
Labels: bug

#280 Issue 277 - Adding of CI process in README.md file
  README.md
Labels: documentation

#276 Odim 241:Updating the lib message bus and platform config toml to accept the multiple kafka host
  build/RFPlugin/edit_config.sh
  build/odimra/edit_config.sh
  lib-messagebus/datacommunicator/config.go
  lib-messagebus/datacommunicator/config_test.go
  lib-messagebus/datacommunicator/kafkacomm.go
  lib-messagebus/datacommunicator/kafkacomm_test.go
  lib-messagebus/platforms/platformconfig.toml
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-task/go.mod
  svc-task/go.sum
Labels: enhancement

#283 Issue - 279 Add fsnotify logic in lib-utilities
  lib-utilities/common/trackconfig.go
  lib-utilities/go.mod
Labels: enhancement

#282 ODIM 274 - Fix consul entry point script
  install/Docker/dockerfiles/scripts/consul-entrypoint.sh
Labels: bug

#285 Issue 264 - [use local references for internal libraries]
  Makefile
  build_images.sh
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.odim
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/scripts/build_odim.sh
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-messagebus/go.mod
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  lib-rest-client/go.mod
  lib-rest-client/go.sum
  lib-utilities/go.mod
  lib-utilities/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-task/thandle/thandle_test.go
  svc-update/go.mod
  svc-update/go.sum
Labels: enhancement

#288 Odim 225 - Add uri in log message and use log module
  plugin-redfish/rfphandler/getResource.go
  plugin-redfish/rfphandler/managers.go
Labels: bug

#291 ODIM 281: Changed error response status code for GET operation on invalid event subscription ID
  svc-events/events/getevtsubscription.go
  svc-events/events/getevtsubscription_test.go
Labels: bug

#299 Issue 122 [Change the synchronisation code to support multiple instances of aggregation service]
  svc-aggregation/agmodel/system.go
  svc-aggregation/go.sum
  svc-aggregation/main.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/rpc/common.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/aggregate_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/connectionmethods_test.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/rediscoverinventory_test.go
  svc-aggregation/system/update_test.go
Labels: enhancement

#301 Odim 284 - Handled event payloads whose OriginOfCondition is not compliant with the spec
  plugin-redfish/rfpmessagebus/publish.go
  plugin-redfish/rfpmodel/Events.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
Labels: enhancement

#298 Latest task schema version update
  svc-api/go.mod
  svc-api/go.sum
  svc-api/handle/handlers.go
  svc-task/README.md
  svc-task/thandle/thandle.go
  svc-task/thandle/tmonitor.go
Labels: enhancement

#306 ODIM 227 : svc-events:evtsubscription: failing if port number specified.
  svc-events/events/deletesubscription.go
  svc-events/events/evtsubscription.go
Labels: bug
