Repository ODIM-Project/ODIM, pull requests merged in 2020-09, with the labels that each got.

#69 Adding create volume details to proto file
  lib-utilities/proto/systems/systems.micro.go
  lib-utilities/proto/systems/systems.pb.go
  lib-utilities/proto/systems/systems.proto
Labels: enhancement

#76 ODIM-67 Aggregation Service Implementation
  svc-aggregation/agresponse/rpc.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/bootorder_test.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/reset.go
  svc-aggregation/system/reset_test.go
  svc-api/handle/handlers_test.go
  svc-api/router/router.go
Labels: Aggregation Service, bug

#81 Modification for get volume in constants file
  lib-utilities/common/constants.go
  lib-utilities/common/workerpool.go
  lib-utilities/common/workerpool_test.go
Labels: enhancement

#88 Issue 65: Fix for task response Payload.JSONBody being filled with response instead of request
  lib-utilities/common/generalerror.go
  lib-utilities/proto/task/task.micro.go
  lib-utilities/proto/task/task.pb.go
  lib-utilities/proto/task/task.proto
  svc-aggregation/agcommon/common.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/common.go
  svc-aggregation/system/reset.go
  svc-events/events/evtsubscription.go
  svc-events/events/evtsubscription_test.go
  svc-events/go.mod
  svc-events/go.sum
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
  svc-task/go.mod
  svc-task/go.sum
  svc-task/thandle/thandle.go
  svc-task/thandle/thandle_test.go
  svc-task/thandle/tmonitor.go
  svc-task/tmodel/tmodel.go
  svc-task/tresponse/error.go
  svc-task/tresponse/task.go
Labels: bug

#90 ODIM-89 remove add/remove actions from proto methods
  lib-utilities/proto/aggregator/aggregator.micro.go
  lib-utilities/proto/aggregator/aggregator.pb.go
  lib-utilities/proto/aggregator/aggregator.proto
Labels: Aggregation Service, bug

#93 Odim 33: SimpleUpdate Action implementation
  .github/workflows/build_deploy_test.yml
  build/docker-compose.yml
  plugin-redfish/main.go
  plugin-redfish/rfphandler/update.go
  plugin-redfish/rfphandler/update_test.go
  svc-update/ucommon/common.go
  svc-update/update/getresources_test.go
  svc-update/update/simpleUpdate.go
  svc-update/update/simpleUpdate_test.go
Labels: Update Service, enhancement

#95 Fix for odim-87: Session Creation in plugin giving 404
  plugin-redfish/main.go
Labels: bug

#94 Odim 68 - Implemented creation of logical drive using storage schema
  plugin-redfish/main.go
  plugin-redfish/rfphandler/storage.go
  plugin-redfish/rfphandler/storage_test.go
  plugin-redfish/rfpmodel/storage.go
  svc-api/go.mod
  svc-api/go.sum
  svc-api/handle/systems.go
  svc-api/handle/systems_test.go
  svc-api/router/router.go
  svc-api/rpc/system.go
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/main.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/smodel/systems.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: enhancement

#96 ODIM-89 remove older code of add/remove server in svc-api and svc-aggregation service
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/deletecompute.go
  svc-aggregation/system/deletecompute_test.go
  svc-api/handle/aggregator.go
  svc-api/handle/aggregator_test.go
  svc-api/router/router.go
  svc-api/rpc/aggregator.go
Labels: Aggregation Service, bug

#99 odim-98: Get response on session service gives 401 status code error with invalid basic authentication
  svc-api/main.go
  svc-api/router/router.go
Labels: bug

#102 ODIM-100 add proto methods for delete volume
  lib-utilities/proto/systems/systems.micro.go
  lib-utilities/proto/systems/systems.pb.go
  lib-utilities/proto/systems/systems.proto
Labels: enhancement

#103 ODIM-100 add empty signature for delete volume proto method
  svc-api/go.mod
  svc-api/go.sum
  svc-api/handle/systems.go
  svc-api/handle/systems_test.go
  svc-api/main.go
  svc-api/rpc/system.go
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: enhancement

#101 Odim 73 : Get Volume collection
  svc-api/handle/handlers_test.go
  svc-api/router/router.go
Labels: enhancement

#108 odim 107:Updating the Event struct of lib-utilities
  lib-utilities/common/constants.go
Labels: bug

#110 Odim 107:Updating the OriginOfCondition
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  plugin-redfish/rfpmessagebus/publish.go
  svc-aggregation/agmessagebus/publish.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-events/consumer/consumer_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
  svc-events/events/submittestevent_test.go
  svc-events/go.mod
  svc-events/go.sum
  svc-events/rpc/events_test.go
  svc-task/go.mod
  svc-task/go.sum
  svc-task/tmessagebus/publish.go
Labels: bug

#111 added route for retrieving a particular volume
  svc-api/router/router.go
Labels: enhancement

#115 Odim 113
  docs/README.md
Labels: Aggregation Service, documentation

#117 Issue 107:Populate originofcondition in events correctly
  lib-utilities/common/constants.go
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  plugin-redfish/rfpmessagebus/publish.go
  svc-aggregation/agmessagebus/publish.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-events/consumer/consumer_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
  svc-events/events/submittestevent_test.go
  svc-events/go.mod
  svc-events/go.sum
  svc-events/rpc/events_test.go
  svc-task/go.mod
  svc-task/go.sum
  svc-task/tmessagebus/publish.go
Labels: bug

#116 Changes for creating etcd docker image
  .github/workflows/build_deploy_test.yml
  Makefile
  README.md
  build/cleanupbuild.sh
  build/deepcleanupbuild.sh
  build/docker-compose.yml
  build/etcd/Dockerfile.etcd
  build/etcd/etcd-persistence/.gitignore
  build/etcd/etcd.conf.tmpl
  build/etcd/setup_etcd.sh
  build/etcd/start_etcd.sh
  build/run_pre_reqs.sh
Labels: enhancement

#109 ODIM-100 Delete volume implementation
  plugin-redfish/main.go
  plugin-redfish/rfphandler/storage.go
  plugin-redfish/rfphandler/storage_test.go
  svc-api/handle/handlers.go
  svc-api/handle/handlers_test.go
  svc-api/handle/systems.go
  svc-api/handle/systems_test.go
  svc-api/main.go
  svc-api/router/router.go
  svc-api/rpc/system.go
  svc-systems/chassis/getresource.go
  svc-systems/go.sum
  svc-systems/rpc/chassis.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/scommon/common.go
  svc-systems/scommon/common_test.go
  svc-systems/systems/getresource.go
  svc-systems/systems/reset.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: enhancement

#126 Issue-112 : Updated lib-utilities to latest version
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-plugin-rest-client/go.mod
  svc-plugin-rest-client/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: enhancement

#128 ODIM-127 Get on deleted volume is getting success
  svc-systems/rpc/systems_test.go
  svc-systems/smodel/systems.go
  svc-systems/smodel/systems_test.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: bug

#125 Issue-112 : Update go-micro package.
  build/Consul/config/config.json
  build/Consul/data/.gitkeep
  build/cleanupbuild.sh
  build/deepcleanupbuild.sh
  build/docker-compose.yml
  build/odimra/account_session.service
  build/odimra/aggregation.service
  build/odimra/api.service
  build/odimra/event.service
  build/odimra/fabrics.service
  build/odimra/managers.service
  build/odimra/systems.service
  build/odimra/task.service
  build/odimra/update.service
  build/run_pre_reqs.sh
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  lib-utilities/go.mod
  lib-utilities/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-plugin-rest-client/go.mod
  svc-plugin-rest-client/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: enhancement

#130 Odim 129 - Implemented refresh storage data in DB
  svc-aggregation/system/common.go
  svc-aggregation/system/rediscoverinventory.go
  svc-aggregation/system/rediscoverinventory_test.go
  svc-systems/systems/getresource.go
Labels: enhancement

#135 Issue-112 : Reverting go-micro package to earlier version(v.1.13.2)
  build/Consul/config/config.json
  build/Consul/data/.gitkeep
  build/cleanupbuild.sh
  build/deepcleanupbuild.sh
  build/docker-compose.yml
  build/odimra/account_session.service
  build/odimra/aggregation.service
  build/odimra/api.service
  build/odimra/event.service
  build/odimra/fabrics.service
  build/odimra/managers.service
  build/odimra/systems.service
  build/odimra/task.service
  build/odimra/update.service
  build/run_pre_reqs.sh
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  lib-utilities/go.mod
  lib-utilities/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-plugin-rest-client/go.mod
  svc-plugin-rest-client/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: enhancement

#136 issue-112 : revert go-micro update and etcd docker changes
  .github/workflows/build_deploy_test.yml
  Makefile
  README.md
  build/cleanupbuild.sh
  build/deepcleanupbuild.sh
  build/docker-compose.yml
  build/etcd/Dockerfile.etcd
  build/etcd/etcd-persistence/.gitignore
  build/etcd/etcd.conf.tmpl
  build/etcd/setup_etcd.sh
  build/etcd/start_etcd.sh
  build/run_pre_reqs.sh
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-plugin-rest-client/go.mod
  svc-plugin-rest-client/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: enhancement

#141 ODIM-137 list connection methods in aggregation service and add proto methods
  lib-utilities/proto/aggregator/aggregator.micro.go
  lib-utilities/proto/aggregator/aggregator.pb.go
  lib-utilities/proto/aggregator/aggregator.proto
  svc-aggregation/agresponse/rpc.go
  svc-aggregation/rpc/aggregator.go
Labels: Aggregation Service, bug
