Repository ODIM-Project/ODIM, pull requests merged in 2020-08, with the labels that each got.

#11 Odim 7: Post on Aggregation Source functionality
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/agresponse/aggregationsource.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/common.go
  svc-api/go.mod
  svc-api/go.sum
  svc-api/handle/aggregator.go
  svc-api/handle/aggregator_test.go
  svc-api/router/router.go
  svc-api/rpc/aggregator.go
Labels: Aggregation Service

#12 Odim 8:Adding rpc GetAggregationSource in aggregator.proto and generated go micro stubs
  lib-utilities/proto/aggregator/aggregator.micro.go
  lib-utilities/proto/aggregator/aggregator.pb.go
  lib-utilities/proto/aggregator/aggregator.proto
Labels: Aggregation Service

#19 Odim 8:Adding the empty signature for new RPCmethods of AggregationSource
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/rpc/aggregator.go
  svc-api/go.mod
  svc-api/go.sum
Labels: Aggregation Service

#18 Changed odimra to ODIM in path
  README.md
Labels: bug

#16 Added lib-utilities & lib-messagebus in unit test list
  .github/workflows/build_unittest.yml
Labels: bug

#21 Phase-2 changes from bug fixes [odim-5]
  .github/workflows/build_deploy_test.yml
  plugin-redfish/config/config.go
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-account-session/README.md
  svc-account-session/UserAccounts.md
  svc-account-session/account/create.go
  svc-account-session/account/create_test.go
  svc-account-session/account/update.go
  svc-account-session/account/update_test.go
  svc-account-session/asmodel/account.go
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-account-session/role/create.go
  svc-account-session/role/create_test.go
  svc-account-session/role/update.go
  svc-account-session/rpc/account_test.go
  svc-account-session/rpc/role_test.go
  svc-aggregation/README.md
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/deletecompute.go
  svc-aggregation/system/deletecompute_test.go
  svc-aggregation/system/reset.go
  svc-aggregation/system/reset_test.go
  svc-api/go.mod
  svc-api/go.sum
  svc-api/handle/account.go
  svc-api/handle/aggregator_test.go
  svc-api/handle/handlers_test.go
  svc-api/handle/role.go
  svc-api/handle/role_test.go
  svc-api/handle/systems.go
  svc-api/handle/systems_test.go
  svc-api/router/router.go
  svc-events/events/evtsubscription.go
  svc-events/events/submittestevent.go
  svc-fabrics/fabrics/common.go
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/systems/bootorder.go
  svc-systems/systems/bootorder_test.go
  svc-systems/systems/common.go
  svc-systems/systems/getresource_test.go
  svc-systems/systems/reset.go
  svc-systems/systems/reset_test.go
Labels: bug

#43 Odim 8:Aggregation Source Get,Update and Delete Operation
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/agresponse/list.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/deletecompute.go
  svc-aggregation/system/deletecompute_test.go
  svc-aggregation/system/get_resource.go
  svc-aggregation/system/get_resource_test.go
  svc-aggregation/system/reset_test.go
  svc-aggregation/system/update.go
  svc-aggregation/system/update_test.go
  svc-api/handle/aggregator.go
  svc-api/handle/aggregator_test.go
  svc-api/router/router.go
  svc-api/rpc/aggregator.go
Labels: Aggregation Service

#40 Odim 33
  build/odimra/update.service
  lib-utilities/proto/account/account.proto
  lib-utilities/proto/update/update.micro.go
  lib-utilities/proto/update/update.pb.go
  lib-utilities/proto/update/update.proto
Labels: Update Service

#17 Add race flag
  .github/workflows/build_unittest.yml
  build/odimra/build.sh
  build/odimra/builddep.sh
Labels: enhancement

#47 ODIM-46 return 405 for invalid operations
  svc-api/handle/handlers_test.go
  svc-api/router/router.go
Labels: bug

#58 odim 55:Updating the subtask link in response
  svc-task/thandle/tmonitor.go
Labels: bug

#57 ODIM-54 fixed default admin user account getting deleted
  svc-account-session/account/common.go
  svc-account-session/account/delete.go
  svc-account-session/account/delete_test.go
Labels: bug

#60 ODIM-52 fix updating role with duplicate privileges
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-account-session/role/update.go
  svc-account-session/role/update_test.go
Labels: bug

#64 Put/Post/Delete/Path on /redfish/v1/Systems/<system_id>/ArrayControllers-0/Drives/0 uri should return 405
  svc-api/handle/handlers_test.go
  svc-api/router/router.go
Labels: bug
