Repository ODIM-Project/ODIM, pull requests merged in 2020-11, with the labels that each got.

#213 ODIM-169 Update Aggregation service to use Connection Method
  lib-utilities/config/odimra_config.json
  plugin-redfish/config/config.json
  plugin-redfish/rfphandler/pluginStatus.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/common.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/connectionmethods_test.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/reset_test.go
  svc-aggregation/system/update.go
  svc-aggregation/system/update_test.go
Labels: Aggregation Service

#217 odim 214:Adding the loggic get data from device
  svc-systems/systems/storage.go
Labels: bug

#211 Adding routes for PCIeDevice
  plugin-redfish/main.go
  svc-api/handle/handlers.go
  svc-api/router/router.go
Labels: enhancement

#216 changes to content-type to application/xml
  svc-api/handle/handlers.go
Labels: bug

#219 ODIM-218 Corrected message and message id in the response for Aggregate.RemoveElements action
  svc-aggregation/system/aggregate.go
Labels: bug

#220 ODIM 189: Adding Network adapters changes
  plugin-redfish/main.go
  svc-api/handle/handlers.go
  svc-api/router/router.go
  svc-systems/chassis/getresource.go
  svc-systems/chassis/getresource_test.go
Labels: enhancement

#229 Replace Bitnami's Kafka & Zookeeper with the in house developed dockerfile
  .github/workflows/build_deploy_test.yml
  Makefile
  README.md
  build/Kafka/Dockerfiles/Dockerfile.kafka
  build/Kafka/Dockerfiles/Dockerfile.zookeeper
  build/Kafka/scripts/setup_kafka.sh
  build/Kafka/scripts/setup_zookeeper.sh
  build/Kafka/scripts/start_kafka.sh
  build/Kafka/scripts/start_zookeeper.sh
  build/cert_generator/copy_certificate.sh
  build/cert_generator/generate_kafka_certs.sh
  build/cert_generator/generate_zookeeper_certs.sh
  build/cleanupbuild.sh
  build/deepcleanupbuild.sh
  build/docker-compose.yml
  build/run_pre_reqs.sh
Labels: enhancement

#234 ODIM-222 updated the log message for existing manager id
  lib-utilities/common/dbconn.go
  svc-managers/main.go
  svc-managers/managers/managers.go
  svc-managers/mgrmodel/manager.go
Labels: bug

#237 ODIM 233: Updated README file with zookeeper certificate generation information
  README.md
Labels: bug

#235 odim 224:Updating log message during publishing the task event
  svc-task/tmessagebus/publish.go
Labels: bug

#238 Odim 226:Updating response header the formation for event subscription GRF plugin
  plugin-redfish/rfphandler/subscribeEvents.go
  plugin-redfish/rfpresponse/errorResponse.go
Labels: bug

#242 Odim 239 - Added routes for NetworkDeviceFunctions and NetworkPorts
  plugin-redfish/main.go
  svc-api/router/router.go
Labels: enhancement

#243 ODIM-240 remove support of non-standard payload in aggregation service
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/get_resource_test.go
  svc-aggregation/system/update.go
  svc-aggregation/system/update_test.go
Labels: Aggregation Service, bug

#248 Movement of updated Dockerfiles & scripts to upstream
  build_images.sh
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.consul
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.kafka
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.redis
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/Dockerfile.zookeeper
  install/Docker/dockerfiles/scripts/add-hosts.go
  install/Docker/dockerfiles/scripts/consul-config.json
  install/Docker/dockerfiles/scripts/consul-entrypoint.sh
  install/Docker/dockerfiles/scripts/redis-checkdb.sh
  install/Docker/dockerfiles/scripts/redis-createschema.sh
  install/Docker/dockerfiles/scripts/redis-entrypointsetup.sh
  install/Docker/dockerfiles/scripts/redis-master.conf
  install/Docker/dockerfiles/scripts/redis-slave.conf
  install/Docker/dockerfiles/scripts/setup_kafka.sh
  install/Docker/dockerfiles/scripts/setup_zookeeper.sh
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_grfplugin.sh
  install/Docker/dockerfiles/scripts/start_kafka.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_update.sh
  install/Docker/dockerfiles/scripts/start_zookeeper.sh
Labels: enhancement

#250 Odim 241:Updating the go.mod reference with latest message bus and edit config.sh for accepting multiple kafka servers
  build/RFPlugin/edit_config.sh
  build/odimra/edit_config.sh
  lib-messagebus/platforms/platformconfig.toml
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-task/go.mod
  svc-task/go.sum
Labels: enhancement

#232 Handling multiple server update using tasks under UpdateService
  svc-update/go.sum
  svc-update/rpc/common.go
  svc-update/rpc/update.go
  svc-update/ucommon/common.go
  svc-update/update/common.go
  svc-update/update/getresources_test.go
  svc-update/update/simpleUpdate.go
  svc-update/update/simpleUpdate_test.go
  svc-update/update/startUpdate.go
  svc-update/update/startUpdate_test.go
Labels: Update Service, enhancement

#257 ODIM-252 error log doesn't have information about the supported and provided firmware version
  svc-aggregation/system/common.go
Labels: bug

#199 Odim 191 - updated docs/readme, deployment readme, and and individual readme files
  README.md
  docs/README.md
  svc-account-session/README.md
  svc-account-session/UserAccounts.md
  svc-aggregation/README.md
  svc-api/README.md
  svc-events/README.md
  svc-fabrics/README.md
  svc-managers/README.md
  svc-systems/README.md
  svc-task/README.md
  svc-update/README.md
Labels: documentation

#253 Odim 223 - Remove unnecessary logs from task
  svc-task/thandle/thandle.go
Labels: bug
