Repository ODIM-Project/ODIM, pull requests merged in 2020-10, with the labels that each got.

#144 Issue 124 (Get on volume is giving success response after volume deleted)
  svc-aggregation/agmodel/system.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/rediscoverinventory.go
  svc-systems/chassis/getresource.go
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/scommon/common.go
  svc-systems/scommon/common_test.go
  svc-systems/systems/getresource.go
  svc-systems/systems/storage.go
Labels: bug

#152 [Issue-149] Added checks to find the exported values of FQDN & HOSTIP before proceeding with deployment.
  .github/workflows/build_deploy_test.yml
  .github/workflows/build_unittest.yml
  build/odimra/makedep.sh
Labels: bug

#154 ODIM-137 add connection method configuration values
  lib-utilities/common/pluginstatus_test.go
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/odimra_config.json
Labels: Aggregation Service, bug

#150 Odim 142 - Implemented DrivesCollection URI should read data from DB
  lib-utilities/common/constants.go
Labels: bug

#162 odim 133:Updating Get Chassis collection and Chassis DB query
  svc-api/router/router.go
  svc-systems/chassis/getresource.go
  svc-systems/chassis/getresource_test.go
Labels: bug

#160 Odim 142
  svc-systems/systems/storage.go
Labels: bug

#165 ODIM-132 use err variable instead of pingErr
  lib-utilities/common/dbconn.go
  lib-utilities/config/config_test.go
Labels: bug

#166 ODIM-137 Code implementation of get on connection method
  svc-aggregation/agcommon/common.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/agresponse/rpc.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/main.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/connectionmethods.go
  svc-aggregation/system/connectionmethods_test.go
  svc-api/handle/aggregator.go
  svc-api/handle/aggregator_test.go
  svc-api/handle/handlers_test.go
  svc-api/router/router.go
  svc-api/rpc/aggregator.go
Labels: Aggregation Service, bug

#164 Issue 155 (changing the imports from the svc-plugin-rest-client to lib-rest-client)
  .github/workflows/build_unittest.yml
  build/odimra/build.sh
  build/odimra/builddep.sh
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/main.go
  svc-aggregation/rpc/common.go
  svc-events/evcommon/common.go
  svc-events/events/publishevttosubscriber.go
  svc-events/go.mod
  svc-events/go.sum
  svc-events/main.go
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-fabrics/main.go
  svc-managers/go.mod
  svc-managers/go.sum
  svc-managers/managers/common.go
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/rpc/chassis.go
  svc-systems/rpc/systems.go
  svc-systems/systems/storage.go
  svc-update/go.mod
  svc-update/go.sum
  svc-update/update/common.go
Labels: enhancement

#168 Issue 161 task 1 (Clean up and refactor in lib-utilities for the CreateGenericErrorResponse function)
  lib-utilities/response/errorresponse.go
  lib-utilities/response/errorresponse_test.go
Labels: bug

#170 Issue 161
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  lib-rest-client/go.mod
  lib-rest-client/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/common.go
  svc-aggregation/system/update_test.go
  svc-api/go.mod
  svc-api/go.sum
  svc-events/events/submittestevent.go
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-update/go.mod
  svc-update/go.sum
  svc-update/update/simpleUpdate.go
  svc-update/update/simpleUpdate_test.go
Labels: bug

#176 odm 163:Updating the status code for invalid system id
  svc-systems/systems/bootorder.go
  svc-systems/systems/bootorder_test.go
  svc-systems/systems/getresource.go
  svc-systems/systems/getresource_test.go
  svc-systems/systems/reset.go
  svc-systems/systems/reset_test.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: bug

#181 Issue 172
  lib-utilities/services/auth.go
  svc-account-session/session/create.go
  svc-api/main.go
Labels: enhancement

#171 Updating docs/readme, svc-systems/readme, svc-aggregation/readme
  docs/README.md
  svc-aggregation/README.md
  svc-systems/README.md
  svc-update/README.md
Labels: documentation

#183 odim 3617:adding the stub connection methods in config
  lib-utilities/config/mockconfig.go
  lib-utilities/config/mockconfig_test.go
Labels: Aggregation Service, enhancement

#185 Issue 172 task 3
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-account-session/session/create.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/reset_test.go
  svc-api/go.mod
  svc-api/go.sum
  svc-api/handle/handlers.go
  svc-api/handle/handlers_test.go
  svc-events/events/deletesubscription.go
  svc-events/events/evtsubscription.go
  svc-events/events/getevtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/submittestevent.go
  svc-events/go.mod
  svc-events/go.sum
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
  svc-fabrics/fabrics/common.go
  svc-fabrics/fabrics/createresource_test.go
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-fabrics/rpc/fabrics.go
  svc-fabrics/rpc/fabrics_test.go
  svc-managers/go.mod
  svc-managers/go.sum
  svc-managers/rpc/manager.go
  svc-managers/rpc/manager_test.go
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/rpc/chassis.go
  svc-systems/rpc/chassis_test.go
  svc-systems/rpc/systems.go
  svc-systems/systems/reset_test.go
  svc-task/go.mod
  svc-task/go.sum
  svc-task/tauth/tauth.go
  svc-task/thandle/thandle.go
  svc-task/thandle/tmonitor.go
  svc-task/thandle/tmonitor_test.go
  svc-update/go.mod
  svc-update/go.sum
  svc-update/rpc/common.go
  svc-update/rpc/update.go
  svc-update/rpc/update_test.go
  svc-update/update/common.go
  svc-update/update/getresources_test.go
Labels: enhancement

#186 Odim 173:Adding file observer in aggregation service to reload config data
  svc-aggregation/agcommon/common.go
  svc-aggregation/agcommon/common_test.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/main.go
Labels: Aggregation Service, enhancement

#187 Odim 173:Adding file observer in aggregation service to reload config data
  lib-utilities/config/mockconfig.go
  lib-utilities/config/mockconfig_test.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/agcommon/common_test.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/main.go
Labels: Aggregation Service, enhancement

#179 updating deployment readme and docs/readme
  README.md
  docs/README.md
Labels: documentation

#188 Odim-105 Adding Plugin with duplicate manager address is getting accepted
  svc-aggregation/agmodel/system.go
  svc-aggregation/rpc/common.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/common.go
Labels: bug

#180 Implementing changes for returning 204 after deleting completed task
  svc-task/thandle/thandle.go
Labels: bug

#190 Non-admin user should be able to get his own task
  svc-task/thandle/thandle.go
Labels: bug

#193 Issue 172
  lib-persistence-manager/persistencemgr/redis.go
Labels: enhancement

#194 issue 192:Updating ip in place fqdn for create and delete subscription
  svc-events/events/deletesubscription.go
  svc-events/events/evtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
Labels: bug

#196 Issue 172
  lib-utilities/go.mod
  lib-utilities/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: enhancement

#198 Issue 197
  svc-systems/rpc/systems.go
Labels: bug

#202 Issue 157- Updating Readme.md file with cleanup commands
  README.md
Labels: documentation

#203 Issue 200: GRF plugin has "bios" instead of "Bios" in route
  plugin-redfish/main.go
Labels: bug

#204 Issue 201: GET on individual Storage, Drives and Volumes not defined in Generic Redfish Plugin
  plugin-redfish/main.go
Labels: bug

#207 Issue 205: use similar table names for all managers including ODIMRA
  svc-managers/managers/common.go
  svc-managers/managers/common_test.go
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrmodel/manager.go
  svc-managers/mgrmodel/manager_test.go
  svc-managers/rpc/manager_test.go
Labels: enhancement
