Repository ODIM-Project/ODIM, pull requests merged in 2021-07, with the labels that each got.

#590 ODIM-589 Store metric data in db
  plugin-redfish/main.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/common.go
  svc-api/handle/telemetry.go
  svc-telemetry/telemetry/common.go
  svc-telemetry/telemetry/telemetry.go
Labels: prio:normal, status:in-progress, type:feature

#591 Resolved the managers/chassis issue - a get on BMC manager was giving 404 error and delete server was not deleting the manager and chassis info
  lib-utilities/common/mockconfig.go
  lib-utilities/config/README.md
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/constants.go
  lib-utilities/config/mockconfig.go
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  svc-aggregation/agmessagebus/publish.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/rediscoverinventory.go
  svc-systems/scommon/common.go
  svc-update/ucommon/common.go
Labels: prio:normal, status:in-progress, type:bug

#592 ODIM-13 : Fix for generating third party HA helm packages
  odim-controller/helmcharts/consul-ha/templates/consul-ha-deployment.yaml
  odim-controller/helmcharts/consul-ha/templates/consul-ha-service.yaml
  odim-controller/helmcharts/consul/templates/consul-deployment.yaml
  odim-controller/helmcharts/consul/templates/consul-service.yaml
  odim-controller/helmcharts/kafka-ha/templates/kafka-ha-deployment.yaml
  odim-controller/helmcharts/kafka-ha/templates/kafka-ha-service.yaml
  odim-controller/helmcharts/kafka/templates/kafka-deployment.yaml
  odim-controller/helmcharts/kafka/templates/kafka-service.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-pv-pvc.yaml
  odim-controller/helmcharts/zookeeper-ha/templates/zookeeper-ha-deployment.yaml
  odim-controller/helmcharts/zookeeper-ha/templates/zookeeper-ha-service.yaml
  odim-controller/helmcharts/zookeeper/templates/zookeeper-deployment.yaml
  odim-controller/helmcharts/zookeeper/templates/zookeeper-service.yaml
  odim-controller/odimra/roles/upgrade-thirdparty/tasks/main.yaml
  svc-aggregation/system/deleteaggregationsource.go
Labels: prio:normal, status:in-progress, type:bug

#593 ODIM-589 Count members from the super set of the collection
  svc-aggregation/system/common.go
Labels: prio:normal, status:in-progress, type:bug

#594 ODIM-14 : restrict etcd pods to master node
  .github/workflows/build_deploy_test.yml
  odim-controller/helmcharts/etcd-ha/templates/etcd-ha-service.yaml
  odim-controller/helmcharts/etcd-ha/templates/etcd-ha-statefulset.yaml
  odim-controller/helmcharts/etcd/templates/etcd-service.yaml
  odim-controller/helmcharts/etcd/templates/etcd-statefulset.yaml
Labels: prio:normal, status:in-progress, type:feature

#597 Forwarding telemetry report event to ODIM (#35)
  plugin-redfish/rfpmessagebus/publish.go
Labels: prio:normal, status:in-progress, type:feature

#600 Update individual Trigger
  svc-telemetry/main.go
Labels: prio:normal, status:in-progress, type:feature

#596 Implemented VirtualMedia Actions, Insert and Eject VirtualMedia for Dell plugin
  plugin-dell/dphandler/common.go
  plugin-dell/dphandler/managers.go
  plugin-dell/dphandler/managers_test.go
  plugin-dell/main.go
  svc-managers/managers/common.go
  svc-managers/managers/common_test.go
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrcommon/common.go
  svc-managers/mgrcommon/common_test.go
  svc-managers/mgrmodel/manager.go
  svc-managers/mgrmodel/manager_test.go
  svc-managers/rpc/manager_test.go
Labels: prio:high, status:in-progress, type:feature

#599 Removed properties which are not part of AggregateCollection schema
  lib-dmtf/model/storage.go
  svc-aggregation/system/aggregate.go
Labels: prio:normal, status:in-progress, type:bug

#602 ODIM-20 : Share startup data to specific plugin instance in event
  lib-utilities/common/kubernetes.go
  lib-utilities/go.mod
  lib-utilities/go.sum
  odim-controller/helmcharts/aggregation/templates/deployment.yaml
  odim-controller/helmcharts/create_helm_packages.sh
  odim-controller/helmcharts/dellplugin/dellplugin/templates/deployment.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/deployment.yaml
  odim-controller/helmcharts/odimra-k8s-access-config/Chart.yaml
  odim-controller/helmcharts/odimra-k8s-access-config/templates/_helpers.tpl
  odim-controller/helmcharts/odimra-k8s-access-config/templates/role.yaml
  odim-controller/helmcharts/odimra-k8s-access-config/templates/rolebinding.yaml
  odim-controller/helmcharts/odimra-k8s-access-config/templates/serviceaccount.yaml
  odim-controller/helmcharts/odimra-k8s-access-config/values.yaml
  odim-controller/odimra/group_vars/all
  odim-controller/scripts/odim-controller.py
  plugin-dell/go.sum
  plugin-dell/main.go
  plugin-redfish/go.sum
  plugin-redfish/main.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/go.sum
  svc-aggregation/system/pluginHealthCheck.go
Labels: prio:normal, status:in-progress, type:feature

#601 Adding the odimra deployment file
  .github/workflows/odimra_deployment.yml
Labels: prio:normal, status:in-progress, type:feature

#603 ODIM-20 : automate manual steps of plugin deployment
  odim-controller/helmcharts/dellplugin/dellplugin.sh
  odim-controller/helmcharts/grfplugin/grfplugin.sh
  odim-controller/helmcharts/urplugin/urplugin.sh
  odim-controller/odimra/roles/deploy-plugin/tasks/main.yaml
  odim-controller/odimra/roles/deploy-plugin/tasks/plugins.yaml
  odim-controller/odimra/roles/odimra-copy-image/tasks/main.yaml
  odim-controller/odimra/roles/post-uninstall/tasks/main.yaml
  odim-controller/odimra/roles/post-uninstall/tasks/plugins.yaml
  odim-controller/odimra/roles/pre-install/tasks/main.yaml
  odim-controller/odimra/roles/pre-install/tasks/plugins.yaml
  odim-controller/odimra/roles/remove-plugin/tasks/main.yaml
  odim-controller/odimra/roles/remove-plugin/tasks/plugins.yaml
Labels: prio:normal, status:in-progress, type:feature

#605 Update Telemetry Services Instructions in API Guide (#8)
  docs/README.md
Labels: type:doc

#604 Creating a new PR for deployment instructions as per requirement (#7)
  README.md
  docs/images/kubernetes_images.png
  docs/images/odimra_images.png
  plugin-dell/README.md
  plugin-redfish/README.md
  plugin-unmanaged-racks/README.md
Labels: type:doc

#606 ODIM-17 : Enhance logging for plugin inventory update scenario
  lib-utilities/common/kubernetes.go
  plugin-dell/dphandler/pluginStatus.go
  plugin-redfish/rfphandler/pluginStatus.go
  svc-aggregation/system/pluginHealthCheck.go
Labels: prio:normal, status:in-progress, type:feature

#607 Documented Support for URL Encoding (#3)
  docs/README.md
Labels: type:doc

#609 URP config changes
  plugin-unmanaged-racks/config/config.go
  plugin-unmanaged-racks/config/config.yml
  plugin-unmanaged-racks/rest/module.go
Labels: prio:normal, status:in-progress, type:techdebt

#612 Remove Lenovo instances from the main getting started readme
  README.md
Labels: type:doc

#613 updated sample responses for VirtualMedia APIs
  docs/README.md
Labels: type:doc

#614 URP UUID library update
  plugin-unmanaged-racks/config/config.go
  plugin-unmanaged-racks/go.mod
  plugin-unmanaged-racks/go.sum
  plugin-unmanaged-racks/redfish/chassis.go
  plugin-unmanaged-racks/rest/module.go
Labels: prio:normal, status:in-progress, type:techdebt

#617 Unable to fetch MetricReports from multiple plugins
  svc-telemetry/rpc/telemetry_test.go
  svc-telemetry/tcommon/common.go
  svc-telemetry/tcommon/common_test.go
Labels: prio:normal, status:in-progress, type:feature

#618 Odim 23- Updated registry with latest versions
  lib-utilities/etc/Base.1.10.0.json
  lib-utilities/etc/Base.1.9.0.json
  lib-utilities/etc/Composition.1.1.0.json
  lib-utilities/etc/EthernetFabric.1.0.0.json
  lib-utilities/etc/Fabric.1.0.0.json
  lib-utilities/etc/TaskEvent.1.0.3.json
  lib-utilities/etc/Update.1.0.0.json
Labels: prio:normal, status:in-progress, type:techdebt

#619 odim-24:Updating metadata info
  svc-api/handle/handlers.go
Labels: prio:normal, status:in-progress
