Repository ODIM-Project/ODIM, pull requests merged in 2021-03, with the labels that each got.

#445 Issue-444 fix event subscription info deleting automatically
  lib-persistence-manager/persistencemgr/redis.go
  lib-utilities/common/trackconfig.go
  svc-events/evcommon/common.go
  svc-events/evcommon/common_test.go
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
Labels: prio:high, status:in-progress, type:bug

#449 Odim 448: Semantic fixes on update service
  svc-update/update/getresources.go
  svc-update/update/getresources_test.go
  svc-update/uresponse/updateservice.go
Labels: prio:high, status:resolved, type:bug

#450 [Issue-446] - Removing derived Consul service name for registry address.
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_update.sh
  odim-controller/helmcharts/consul-ha/templates/consul-ha-service.yaml
Labels: prio:high, status:new, type:bug

#451 Fix for Issue 443 Fabric plugin token used for chassis not getting updated even after expiry
  svc-systems/chassis/fabric.go
  svc-systems/chassis/fabricresource.go
  svc-systems/chassis/updatefabricresource.go
Labels: prio:high, status:in-progress, type:bug

#454 [Issue-453] - Added client certificate generator script
  odim-controller/scripts/gen_client_certs.sh
Labels: prio:high, status:in-progress, type:techdebt

#455 Issue 452: Namespaces included in metadata are not found in the referenced schema URI
  lib-utilities/etc/Redfish_1.0.1_PrivilegeRegistry.json
  lib-utilities/etc/Redfish_1.0.2_PrivilegeRegistry.json
  svc-api/handle/chassis_test.go
  svc-api/handle/handlers.go
  svc-task/tresponse/task.go
Labels: prio:high, status:in-progress, type:bug

#458 Fix on Chassis resources GET
  lib-utilities/common/constants.go
  svc-api/handle/chassis.go
Labels: prio:high, status:in-progress, type:bug

#460 issue-459 : Patch request to attach system chassis to Rack is failing
  lib-utilities/config/httpConfig.go
  lib-utilities/config/httpConfig_test.go
  plugin-unmanaged-racks/rest/get_chassis_collection_handler.go
  plugin-unmanaged-racks/rest/patch_chassis_handler.go
  svc-fabrics/fabrics/common.go
  svc-systems/plugin/client.go
Labels: prio:normal, status:in-progress, type:bug

#468 Issue-463 remove trailing slash in system collection uri @odata.id
  svc-systems/systems/getresource.go
  svc-systems/systems/getresource_test.go
Labels: prio:low, status:in-progress, type:bug

#469 Odim 461: removed ActionInfo from Action struct
  svc-aggregation/agresponse/rpc.go
Labels: prio:normal, status:in-progress, type:bug

#467 issue-464: Update nodeport param in grfplugin service manifest file
  odim-controller/helmcharts/grfplugin/grfplugin/templates/service.yaml
Labels: prio:normal, status:in-progress, type:bug

#466 issue-465 : Update openjdk-jre-headless package version in kafka and zookeeper dockerfiles
  install/Docker/dockerfiles/Dockerfile.kafka
  install/Docker/dockerfiles/Dockerfile.zookeeper
Labels: prio:normal, status:in-progress, type:techdebt

#472 Odim 471:Get on /redfish/v1/Managers/{SystemId}/SerialInterface is giving 404 error
  lib-utilities/common/constants.go
  plugin-redfish/main.go
  svc-api/handle/handlers.go
  svc-api/router/router.go
  svc-managers/mgrmodel/manager.go
Labels: prio:normal, status:resolved, type:bug

#476 Issue-470 Add storage structure in lib-dmtf
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/ComputerSystem.go
  lib-dmtf/model/common.go
  lib-dmtf/model/storage.go
Labels: prio:low, status:resolved, type:bug

#479 Odim 456:Adding the DMTF models for Zone and Endpoints
  lib-dmtf/model/addressPool.go
  lib-dmtf/model/common.go
  lib-dmtf/model/endpoint.go
  lib-dmtf/model/fabric.go
  lib-dmtf/model/manager.go
  lib-dmtf/model/port.go
  lib-dmtf/model/switch.go
  lib-dmtf/model/zones.go
  svc-systems/chassis/fabric.go
Labels: prio:normal, status:in-progress, type:feature

#482 Issue-470 update storage object with pointer
  lib-dmtf/model/common.go
  lib-dmtf/model/storage.go
Labels: prio:low, status:in-progress, type:bug

#483 issue-317 : helmcharts for dellplugin
  odim-controller/helmcharts/dellplugin/dellplugin-config.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/Chart.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/_helpers.tpl
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/deployment.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/pv.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/pvc.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/service.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/values.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/values.yaml
Labels: prio:normal, status:in-progress, type:feature

#480 Issues-478 Remove version in odatatype of aggregate collection
  svc-aggregation/agresponse/rpc.go
  svc-aggregation/system/aggregate.go
Labels: prio:low, status:in-progress, type:bug

#487 issue-486 : Check both IP address and servicename/FQDN in events to identify the fabric plugin
  svc-fabrics/fabrics/addfabric.go
Labels: prio:normal, status:resolved, type:techdebt

#488 Issue 481
  svc-update/update/simpleUpdate.go
Labels: prio:low, status:in-progress, type:bug

#490 response headers and routes added for fabrics (#22)
  svc-api/handle/fabrics.go
  svc-api/handle/fabrics_test.go
  svc-api/router/router.go
Labels: prio:normal, status:in-progress, type:feature

#340 Issue 328 - addressed a comment "remove unnecessary ` `"
  README.md
Labels: prio:normal, status:resolved, type:doc

#348 Issue 345 - addressed readme doc
  README.md
Labels: prio:normal, status:in-progress, type:doc

#493 Issue-470 Add drive and volume object in lib-dmtf
  lib-dmtf/model/common.go
  lib-dmtf/model/storage.go
Labels: prio:low, status:resolved, type:bug
