Repository ODIM-Project/ODIM, pull requests merged in 2021-12, with the labels that each got.

#714 Fix on Chassis collection get: Replacement of colon fix
  svc-systems/smodel/systems.go
Labels: type:bug, prio:high, status:in-progress

#715 ODIM-62 update plugin config files
  odim-controller/helmcharts/dellplugin/dellplugin-config.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/values.yaml
  odim-controller/helmcharts/grfplugin/grfplugin-config.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/configmaps.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/values.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin-config.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/configmaps.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/values.yaml
  plugin-dell/config/config.go
  plugin-dell/config/dell_config.json
  plugin-lenovo/config/config.go
  plugin-lenovo/config/config.json
  plugin-lenovo/config/lenovo_config.json
  plugin-redfish/config/config.go
  plugin-redfish/config/config.json
Labels: type:feature, prio:normal, status:in-progress

#718 ODIM-71 Fix event service unit test cases
  svc-events/evcommon/common.go
  svc-events/evcommon/common_test.go
  svc-events/evcommon/mock.go
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription.go
  svc-events/events/evtsubscription_test.go
  svc-events/events/getevtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
  svc-events/events/submittestevent_test.go
  svc-events/evmodel/events_test.go
  svc-events/evresponse/events_test.go
  svc-events/main.go
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
Labels: type:bug, prio:high, status:in-progress

#719 Colons replacement - Merge content from my feature branch to Dev branch
  docs/README.md
Labels: type:doc

#722 ODIM-73 Volume creation is failing in ODIM
  svc-aggregation/system/rediscoverinventory.go
Labels: type:bug, prio:normal, status:in-progress

#723 odim 72:Adding the changes related redis stream publish in aggregation , task and lib message bus
  lib-messagebus/datacommunicator/config.go
  lib-messagebus/datacommunicator/header.go
  lib-messagebus/datacommunicator/header_test.go
  lib-messagebus/datacommunicator/redisstreamcomm.go
  lib-messagebus/go.mod
  lib-messagebus/go.sum
  lib-messagebus/platforms/platformconfig.toml
  lib-utilities/config/constants.go
  odim-controller/helmcharts/odimra-platformconfig/templates/configmaps.yaml
  svc-aggregation/agmessagebus/publish.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/main.go
  svc-events/go.mod
  svc-events/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-task/main.go
  svc-task/tmessagebus/publish.go
Labels: prio:high, type:feature, status:in-progress
