Repository ODIM-Project/ODIM, pull requests merged in 2021-06, with the labels that each got.

#551 Adding the base code for plugin Lenovo
  plugin-lenovo/README.md
  plugin-lenovo/config/README.md
  plugin-lenovo/config/config.go
  plugin-lenovo/config/config.json
  plugin-lenovo/config/mockconfig.go
  plugin-lenovo/config/mockconfig_test.go
  plugin-lenovo/go.mod
  plugin-lenovo/go.sum
  plugin-lenovo/lphandler/basicAuth.go
  plugin-lenovo/lphandler/basicAuth_test.go
  plugin-lenovo/lphandler/biosSettings.go
  plugin-lenovo/lphandler/biosSettings_test.go
  plugin-lenovo/lphandler/bootorder.go
  plugin-lenovo/lphandler/createSession.go
  plugin-lenovo/lphandler/getResource.go
  plugin-lenovo/lphandler/managers.go
  plugin-lenovo/lphandler/pluginStatus.go
  plugin-lenovo/lphandler/redfishEvents.go
  plugin-lenovo/lphandler/reset.go
  plugin-lenovo/lphandler/storage.go
  plugin-lenovo/lphandler/storage_test.go
  plugin-lenovo/lphandler/subscribeEvents.go
  plugin-lenovo/lphandler/update.go
  plugin-lenovo/lphandler/update_test.go
  plugin-lenovo/lpmessagebus/publish.go
  plugin-lenovo/lpmiddleware/basicAuthenticate.go
  plugin-lenovo/lpmodel/Config.go
  plugin-lenovo/lpmodel/ConfigAuth.go
  plugin-lenovo/lpmodel/Device.go
  plugin-lenovo/lpmodel/Reset.go
  plugin-lenovo/lpmodel/users.go
  plugin-lenovo/lpresponse/authResponse.go
  plugin-lenovo/lpresponse/errorResponse.go
  plugin-lenovo/lpresponse/loginResponse.go
  plugin-lenovo/lpresponse/pluginStatus.go
  plugin-lenovo/lputilities/redfishClient.go
  plugin-lenovo/lputilities/utility.go
  plugin-lenovo/main.go
Labels: prio:normal, status:in-progress, type:feature

#556 issue-553 : add member EventType to Events model
  lib-utilities/common/constants.go
Labels: prio:normal, status:in-progress, type:feature

#559 issue 523:Removing the framework type passing retrieving it from retrieving command line argument
  build/odimra/managers.service
  install/Docker/dockerfiles/scripts/start_managers.sh
  lib-utilities/config/cli.go
  lib-utilities/services/rpcService.go
  svc-account-session/main.go
  svc-aggregation/main.go
  svc-api/main.go
  svc-events/main.go
  svc-fabrics/main.go
  svc-managers/main.go
  svc-systems/main.go
  svc-task/main.go
  svc-update/main.go
  svc-update/update/simpleUpdate.go
Labels: prio:normal, status:in-progress, type:feature

#558 Telemetry service RPC and basic handlers
  lib-utilities/common/constants.go
  svc-telemetry/go.mod
  svc-telemetry/go.sum
  svc-telemetry/main.go
  svc-telemetry/rpc/common.go
  svc-telemetry/rpc/telemetry.go
  svc-telemetry/rpc/telemetry_test.go
  svc-telemetry/telemetry/common.go
  svc-telemetry/telemetry/telemetry.go
  svc-telemetry/tlresponse/list.go
  svc-telemetry/tlresponse/telemetryservice.go
Labels: prio:normal, status:in-progress, type:feature

#562 Revert "Telemetry service implementation under api service and lib-utilities"
  lib-utilities/config/odimra_config.json
  lib-utilities/services/name.go
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  svc-api/go.mod
  svc-api/handle/handlers.go
  svc-api/handle/telemetry.go
  svc-api/handle/telemetry_test.go
  svc-api/models/serviceroot.go
  svc-api/router/router.go
  svc-api/rpc/telemetry.go
Labels: prio:normal

#565 Issue 523:grpc changes for systems service
  build/odimra/systems.service
  install/Docker/dockerfiles/scripts/start_systems.sh
  lib-utilities/proto/chassis/chassis.micro.go
  lib-utilities/proto/chassis/chassis.pb.go
  lib-utilities/proto/systems/systems.micro.go
  lib-utilities/proto/systems/systems.pb.go
  svc-api/go.mod
  svc-api/go.sum
  svc-api/rpc/chassis.go
  svc-api/rpc/system.go
  svc-systems/chassis/getresource.go
  svc-systems/chassis/getresource_test.go
  svc-systems/main.go
  svc-systems/rpc/chassis.go
  svc-systems/rpc/chassis_test.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
Labels: prio:normal, status:in-progress, type:feature

#563 Revert "Telemetry proto files "
  lib-utilities/proto/telemetry/telemetry.micro.go
  lib-utilities/proto/telemetry/telemetry.pb.go
  lib-utilities/proto/telemetry/telemetry.proto
  svc-api/go.mod
  svc-api/go.sum
  svc-api/router/router.go
Labels: prio:normal

#566 issue-523 : grpc changes in svc-aggregation module
  build/odimra/aggregation.service
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  lib-utilities/go.mod
  lib-utilities/go.sum
  lib-utilities/proto/aggregator/aggregator.micro.go
  lib-utilities/proto/aggregator/aggregator.pb.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/main.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-api/go.mod
  svc-api/go.sum
  svc-api/rpc/aggregator.go
  svc-events/events/publishevttosubscriber.go
  svc-events/go.mod
  svc-events/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/systems/getresource.go
Labels: prio:normal, status:in-progress, type:feature

#561 Handled encoded URL paths
  svc-api/handle/systems_test.go
  svc-api/router/router.go
Labels: prio:low, status:in-progress, type:feature

#541 Updating CI Process Instructions + Updating Deployment Instructions
  README.md
  docs/images/all_services_verification.png
  docs/images/check_1.png
  docs/images/check_2.png
  docs/images/check_3.png
  docs/images/kuberenetes_pods_verification.png
  docs/images/odim_cluster.png
  docs/images/odim_deployment.png
Labels: type:doc

#568 issue-523 : grpc changes in svc-update module
  .gitignore
  Makefile
  build/cert_generator/copy_certificate.sh
  build/cert_generator/generate_etcd_certs.sh
  build/cert_generator/generate_odimra_cert.sh
  build/cleanupbuild.sh
  build/deepcleanupbuild.sh
  build/docker-compose.yml
  build/etcd/Dockerfile.etcd
  build/etcd/etcd.conf
  build/etcd/start_etcd.sh
  build/odimra/update.service
  install/Docker/dockerfiles/scripts/start_update.sh
  lib-utilities/go.mod
  lib-utilities/proto/update/update.micro.go
  lib-utilities/proto/update/update.pb.go
  svc-account-session/go.sum
  svc-api/go.sum
  svc-api/rpc/update.go
  svc-fabrics/go.sum
  svc-managers/go.sum
  svc-task/go.sum
  svc-update/go.mod
  svc-update/go.sum
  svc-update/main.go
  svc-update/rpc/update.go
  svc-update/rpc/update_test.go
Labels: prio:normal, status:in-progress, type:feature

#570 issue-567 : model for storing plugin status update events
  lib-utilities/common/constants.go
Labels: prio:normal, status:in-progress, type:feature

#569 Issue 523:grpc changes for events
  build/odimra/event.service
  build/odimra/task.service
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  lib-utilities/proto/events/events.micro.go
  lib-utilities/proto/events/events.pb.go
  lib-utilities/proto/task/task.micro.go
  lib-utilities/proto/task/task.pb.go
  lib-utilities/services/eventsubscription.go
  lib-utilities/services/task.go
  svc-aggregation/system/common.go
  svc-api/rpc/events.go
  svc-api/rpc/task.go
  svc-events/main.go
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
  svc-task/main.go
  svc-task/tauth/tauth.go
  svc-task/thandle/thandle.go
  svc-task/thandle/thandle_test.go
  svc-task/thandle/tmonitor.go
  svc-task/thandle/tmonitor_test.go
Labels: prio:normal, status:in-progress, type:feature

#571 Issue 523-grpc changes for account session and task
  build/odimra/account_session.service
  install/Docker/dockerfiles/scripts/start_account_session.sh
  lib-utilities/proto/account/account.micro.go
  lib-utilities/proto/account/account.pb.go
  lib-utilities/proto/auth/auth.micro.go
  lib-utilities/proto/auth/auth.pb.go
  lib-utilities/proto/role/role.micro.go
  lib-utilities/proto/role/role.pb.go
  lib-utilities/proto/session/session.micro.go
  lib-utilities/proto/session/session.pb.go
  lib-utilities/services/auth.go
  svc-account-session/main.go
  svc-account-session/rpc/account.go
  svc-account-session/rpc/account_test.go
  svc-account-session/rpc/auth.go
  svc-account-session/rpc/role.go
  svc-account-session/rpc/role_test.go
  svc-account-session/rpc/sessions.go
  svc-account-session/session/getsession.go
  svc-account-session/session/getsession_test.go
  svc-api/rpc/account.go
  svc-api/rpc/role.go
  svc-api/rpc/sessions.go
Labels: prio:normal, status:in-progress, type:feature

#576 ODIM-573 Correct MetricReports model in lib-dmtf
  lib-dmtf/model/telemetry.go
Labels: prio:normal, status:in-progress, type:bug

#577 Issue 523 :grpc changes in svc-fabircs module
  build/odimra/fabrics.service
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  lib-utilities/proto/fabrics/fabrics.micro.go
  lib-utilities/proto/fabrics/fabrics.pb.go
  svc-api/rpc/fabrics.go
  svc-events/events/publishevttosubscriber.go
  svc-fabrics/main.go
  svc-fabrics/rpc/fabrics.go
  svc-fabrics/rpc/fabrics_test.go
Labels: prio:high, status:in-progress, type:techdebt

#578 ODIM-573 Correct MetricReports model in lib-dmtf
  lib-dmtf/model/telemetry.go
Labels: prio:normal, status:in-progress, type:bug

#572 issue-567 : share managed servers list with plugin during its startup
  lib-utilities/common/constants.go
  lib-utilities/common/intercomm.go
  lib-utilities/go.sum
  lib-utilities/proto/aggregator/aggregator.micro.go
  lib-utilities/proto/aggregator/aggregator.pb.go
  lib-utilities/proto/aggregator/aggregator.proto
  odim-controller/helmcharts/grfplugin/grfplugin/templates/configmaps.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/deployment.yaml
  plugin-dell/dphandler/pluginStatus.go
  plugin-dell/dpmodel/Device.go
  plugin-dell/go.mod
  plugin-dell/go.sum
  plugin-dell/main.go
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  plugin-redfish/main.go
  plugin-redfish/rfphandler/pluginStatus.go
  plugin-redfish/rfpmodel/Device.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/agmessagebus/publish.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/main.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/pluginHealthCheck.go
  svc-events/consumer/consumer.go
  svc-events/evcommon/common.go
  svc-events/events/publishevttosubscriber.go
  svc-events/evmodel/events.go
  svc-events/go.mod
  svc-events/go.sum
  svc-events/main.go
Labels: prio:normal, status:in-progress, type:feature

#574 ODIM-573 Retrieve individual metric report
  svc-telemetry/go.mod
  svc-telemetry/go.sum
  svc-telemetry/rpc/telemetry_test.go
  svc-telemetry/tcommon/common.go
  svc-telemetry/tcommon/common_test.go
  svc-telemetry/telemetry/common.go
  svc-telemetry/telemetry/telemetry.go
  svc-telemetry/tmodel/model.go
Labels: prio:normal, status:in-progress, type:feature

#581 issue-523 : removed consul from both docker and kubernetes deployment
  .gitignore
  build/Consul/config/config.json
  build/Consul/data/.gitkeep
  build/cleanupbuild.sh
  build/deepcleanupbuild.sh
  build/docker-compose.yml
  build/odimra/managers.service
  build/odimra/systems.service
  build_images.sh
  install/Docker/dockerfiles/Dockerfile.consul
  install/Docker/dockerfiles/scripts/consul-config.json
  install/Docker/dockerfiles/scripts/consul-entrypoint.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  odim-controller/helmcharts/consul-ha/Chart.yaml
  odim-controller/helmcharts/consul-ha/templates/_helpers.tpl
  odim-controller/helmcharts/consul-ha/templates/consul-ha-deployment.yaml
  odim-controller/helmcharts/consul-ha/templates/consul-ha-service.yaml
  odim-controller/helmcharts/consul-ha/values.yaml
  odim-controller/helmcharts/consul/Chart.yaml
  odim-controller/helmcharts/consul/templates/_helpers.tpl
  odim-controller/helmcharts/consul/templates/consul-deployment.yaml
  odim-controller/helmcharts/consul/templates/consul-service.yaml
  odim-controller/helmcharts/consul/values.yaml
  odim-controller/helmcharts/create_helm_packages.sh
  odim-controller/helmcharts/etcd-ha/templates/etcd-ha-service.yaml
  odim-controller/helmcharts/etcd-ha/templates/etcd-ha-statefulset.yaml
  odim-controller/helmcharts/odimra-pv-pvc/templates/odimra-pv.yaml
  odim-controller/helmcharts/odimra-pv-pvc/templates/odimra-pvc.yaml
  odim-controller/helmcharts/odimra-pv-pvc/values.yaml
  odim-controller/odimra/ansible.cfg
  odim-controller/odimra/group_vars/all
  odim-controller/odimra/roles/install/tasks/main.yaml
  odim-controller/odimra/roles/post-uninstall/tasks/main.yaml
  odim-controller/odimra/roles/pre-install/tasks/main.yaml
  odim-controller/odimra/roles/pre-install/templates/config.json.j2
  odim-controller/odimra/roles/uninstall/tasks/main.yaml
  odim-controller/odimra/roles/upgrade-thirdparty/tasks/main.yaml
  odim-controller/scripts/gen_odimra_certs.sh
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  odim-controller/scripts/odim-controller.py
Labels: prio:normal, status:in-progress, type:feature

#582 Telemetry service deployment
  .github/workflows/build_deploy_test.yml
  .github/workflows/build_unittest.yml
  Makefile
  build/docker-compose.yml
  build/odimra/Dockerfile.odimra
  build/odimra/start_odimra.sh
  build/odimra/telemetry.service
  build_images.sh
  install/Docker/dockerfiles/Dockerfile.odim
  install/Docker/dockerfiles/Dockerfile.telemetry
  install/Docker/dockerfiles/scripts/start_telemetry.sh
  lib-utilities/proto/telemetry/telemetry.micro.go
  lib-utilities/proto/telemetry/telemetry.pb.go
  lib-utilities/proto/telemetry/telemetry.proto
  lib-utilities/services/name.go
  odim-controller/helmcharts/create_helm_packages.sh
  odim-controller/helmcharts/telemetry/Chart.yaml
  odim-controller/helmcharts/telemetry/templates/_helpers.tpl
  odim-controller/helmcharts/telemetry/templates/deployment.yaml
  odim-controller/helmcharts/telemetry/templates/service.yaml
  odim-controller/helmcharts/telemetry/values.yaml
  odim-controller/odimra/group_vars/all
  odim-controller/scripts/odim-controller.py
  svc-api/handle/telemetry.go
  svc-api/handle/telemetry_test.go
  svc-api/router/router.go
  svc-api/rpc/telemetry.go
  svc-telemetry/rpc/telemetry_test.go
Labels: prio:normal, status:in-progress, type:feature

#580 ODIM-573 retrieve individual metric report from bmc in GRF
  plugin-redfish/go.mod
  plugin-redfish/main.go
  plugin-redfish/rfphandler/metricreport.go
  plugin-redfish/rfphandler/metricreport_test.go
  plugin-redfish/rfpmodel/Device.go
Labels: prio:normal, status:in-progress, type:feature

#583 Telemetry deployment files from development branch
  install/Docker/dockerfiles/scripts/start_telemetry.sh
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/helmcharts/telemetry/templates/deployment.yaml
  odim-controller/helmcharts/telemetry/templates/service.yaml
  svc-api/handle/handlers.go
  svc-api/models/serviceroot.go
Labels: prio:normal, status:in-progress, type:feature

#584 ODIM-573 Fix issues in telemetry services
  install/Docker/dockerfiles/scripts/start_telemetry.sh
  svc-api/handle/telemetry.go
  svc-telemetry/rpc/telemetry_test.go
  svc-telemetry/tcommon/common.go
  svc-telemetry/tcommon/common_test.go
  svc-telemetry/telemetry/telemetry.go
Labels: prio:high, status:in-progress, type:bug

#586 ODIM-573 Put mutex unlock in defer
  svc-telemetry/tcommon/common.go
Labels: prio:low, status:in-progress, type:bug

#585 Implemented VirtualMedia actions - insert and eject media
  lib-utilities/proto/managers/managers.micro.go
  lib-utilities/proto/managers/managers.pb.go
  lib-utilities/proto/managers/managers.proto
  svc-api/go.mod
  svc-api/handle/managers.go
  svc-api/handle/managers_test.go
  svc-api/router/router.go
  svc-api/rpc/managers.go
  svc-managers/go.mod
  svc-managers/go.sum
  svc-managers/managers/common.go
  svc-managers/managers/common_test.go
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrcommon/common.go
  svc-managers/mgrcommon/common_test.go
  svc-managers/mgrmodel/manager.go
  svc-managers/rpc/manager.go
  svc-managers/rpc/manager_test.go
Labels: prio:low, status:in-progress, type:feature
