Repository ODIM-Project/ODIM, pull requests merged in 2021-08, with the labels that each got.

#620 odim-24 : Updated metadata
  svc-api/handle/handlers.go
Labels: prio:normal, status:in-progress

#622 Fix redfish validator issues
  svc-account-session/account/create.go
  svc-account-session/account/create_test.go
  svc-account-session/account/getaccounts.go
  svc-account-session/account/getaccounts_test.go
  svc-account-session/account/update.go
  svc-account-session/account/update_test.go
  svc-account-session/session/getsession.go
  svc-account-session/session/getsession_test.go
  svc-task/tresponse/task.go
Labels: prio:normal, status:in-progress, type:bug

#624 odim 22:Updating the odataid in the chassis response collection
  svc-systems/go.sum
  svc-systems/sresponse/Collection.go
Labels: prio:high, status:in-progress, type:bug

#621 Update error type to MalformJson
  svc-systems/systems/bootorder.go
Labels: prio:normal, status:in-progress, type:bug

#623 Added virtual media actions support for GRF plugin
  plugin-redfish/main.go
  plugin-redfish/rfphandler/common.go
  plugin-redfish/rfphandler/managers.go
  plugin-redfish/rfphandler/managers_test.go
Labels: prio:low, status:in-progress, type:feature

#625 odim 26:Adding the chassis and managers uri in default subscription
  svc-aggregation/system/addcompute.go
Labels: prio:high, status:in-progress, type:bug

#627 ODIM-20 : ansible changes to install nginx and keepalived
  odim-controller/odimra/roles/configure-keepalived/tasks/main.yaml
  odim-controller/odimra/roles/configure-keepalived/templates/action_script.sh.j2
  odim-controller/odimra/roles/configure-keepalived/templates/keepalived.conf.j2
  odim-controller/odimra/roles/configure-proxy/tasks/main.yaml
  odim-controller/odimra/roles/configure-proxy/templates/nginx.conf.j2
  odim-controller/odimra/roles/remove-keepalived/tasks/main.yaml
  odim-controller/odimra/roles/remove-proxy/tasks/main.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
Labels: prio:normal, status:in-progress, type:techdebt

#626 Odim 22 : modify id in get chassis response body
  svc-api/handle/chassis.go
  svc-systems/chassis/get.go
Labels: prio:normal, status:resolved, type:bug

#628 Update redis deployment version to latest stable build
  .github/workflows/build_deploy_test.yml
  .github/workflows/build_unittest.yml
  README.md
  build/Redis/Dockerfile.redis
  install/Docker/dockerfiles/Dockerfile.redis
  odim-controller/helmcharts/redis-ha/Chart.yaml
  odim-controller/helmcharts/redis/Chart.yaml
  odim-controller/helmcharts/redis/templates/_helpers.tpl
  odim-controller/odimra/group_vars/all
Labels: type:feature, prio:low, status:in-progress

#633 Forwarding metric event from plugin to subscribed destination
  lib-utilities/common/constants.go
  plugin-redfish/rfphandler/subscribeEvents.go
  plugin-redfish/rfpmodel/Device.go
  svc-api/handle/handlers.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-systems/chassis/fabric.go
  svc-systems/chassis/fabricresource.go
  svc-systems/chassis/updatefabricresource.go
Labels: prio:high, type:feature, status:in-progress

#635 Implemented the changes in Lenovo plugin for BIOS Settings, Chassis and Registries
  lib-dmtf/model/Chassis.go
  plugin-lenovo/go.sum
  plugin-lenovo/lphandler/biosSettings.go
  plugin-lenovo/lphandler/getResource.go
  plugin-lenovo/main.go
Labels: type:feature, prio:normal, status:in-progress

#636 Remove telemetry information if all the servers are deleted
  svc-aggregation/agmodel/system.go
  svc-aggregation/rpc/common.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-telemetry/tcommon/common.go
  svc-telemetry/telemetry/telemetry.go
Labels: type:feature, prio:normal, status:in-progress

#637 ODIM-20 : Install and configure nginx, keepalived during deployment
  install/templates/dellplugin_proxy_server.conf.j2
  install/templates/grfplugin_proxy_server.conf.j2
  odim-controller/odimra/roles/configure-keepalived/tasks/main.yaml
  odim-controller/odimra/roles/configure-proxy/tasks/main.yaml
  odim-controller/odimra/roles/configure-proxy/templates/api_proxy_server.conf.j2
  odim-controller/odimra/roles/post-uninstall/tasks/main.yaml
  odim-controller/odimra/roles/pre-install/tasks/main.yaml
  odim-controller/scripts/gen_client_certs.sh
  odim-controller/scripts/gen_odimra_certs.sh
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  odim-controller/scripts/odim-controller.py
Labels: type:techdebt, prio:normal, status:in-progress

#643 gRPC changes for telemetry feature
  build/odimra/telemetry.service
  install/Docker/dockerfiles/scripts/start_telemetry.sh
  lib-utilities/proto/telemetry/telemetry.micro.go
  lib-utilities/proto/telemetry/telemetry.pb.go
  lib-utilities/services/rpcService.go
  svc-api/go.sum
  svc-api/rpc/telemetry.go
  svc-task/go.sum
  svc-task/tauth/tauth.go
  svc-telemetry/go.mod
  svc-telemetry/go.sum
  svc-telemetry/main.go
  svc-telemetry/rpc/telemetry.go
  svc-telemetry/rpc/telemetry_test.go
Labels: prio:high, type:feature, status:in-progress

#641 ODIM-20 : Update proxy conf during add and remove node operations
  install/templates/dellplugin_proxy_server.conf.j2
  install/templates/grfplugin_proxy_server.conf.j2
  odim-controller/helmcharts/dellplugin/dellplugin-config.yaml
  odim-controller/helmcharts/grfplugin/grfplugin-config.yaml
  odim-controller/helmcharts/urplugin/urplugin-config.yaml
  odim-controller/odimra/post_uninstall.yaml
  odim-controller/odimra/pre_install.yaml
  odim-controller/odimra/roles/configure-keepalived/tasks/main.yaml
  odim-controller/odimra/roles/configure-proxy/tasks/main.yaml
  odim-controller/odimra/roles/configure-proxy/tasks/plugins.yaml
  odim-controller/odimra/roles/configure-proxy/templates/nginx.conf.j2
  odim-controller/odimra/roles/deploy-plugin/tasks/main.yaml
  odim-controller/odimra/roles/deploy-plugin/tasks/proxy.yaml
  odim-controller/odimra/roles/post-uninstall/tasks/main.yaml
  odim-controller/odimra/roles/post-uninstall/tasks/plugins.yaml
  odim-controller/odimra/roles/pre-install/tasks/main.yaml
  odim-controller/odimra/roles/remove-keepalived/tasks/main.yaml
  odim-controller/odimra/roles/remove-plugin/tasks/main.yaml
  odim-controller/odimra/roles/remove-proxy/tasks/main.yaml
  odim-controller/odimra/roles/update-proxy-conf/tasks/main.yaml
  odim-controller/odimra/roles/update-proxy-conf/tasks/plugins.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
Labels: type:feature, prio:normal, status:in-progress

#644 Issue 523:Removing the changes related to go micro
  build/odimra/account_session.service
  build/odimra/aggregation.service
  build/odimra/api.service
  build/odimra/event.service
  build/odimra/fabrics.service
  build/odimra/managers.service
  build/odimra/systems.service
  build/odimra/task.service
  build/odimra/telemetry.service
  build/odimra/update.service
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_telemetry.sh
  install/Docker/dockerfiles/scripts/start_update.sh
  lib-utilities/config/cli.go
  lib-utilities/go.mod
  lib-utilities/go.sum
  lib-utilities/services/rpcService.go
  svc-api/go.sum
  svc-api/handle/handlers.go
  svc-api/main.go
  svc-api/rpc/telemetry.go
Labels: prio:high, type:feature, status:in-progress

#645 Added initial version of odim-profiles
  odim-profiles/ODIMBaselineHardwareManagement.v1_0_0.json
  odim-profiles/ODIMFabricManagement.v1_0_0.json
  odim-profiles/ODIMServerHardwareManagement.v1_0_0.json
Labels: type:feature, prio:normal, status:in-progress

#642 odim 4987:Modification to return 409 for duplicate plugin (#21)
  svc-aggregation/agmodel/system.go
  svc-aggregation/system/addaggregationsource.go
Labels: type:bug, prio:normal, status:in-progress

#646 ODIM-20 : log odim-controller operations and output to a file (#41)
  odim-controller/scripts/odim-controller.py
Labels: type:techdebt, prio:normal, status:in-progress

#647 odim-5260:Removed json files using incorrect schema (#22)
  lib-utilities/etc/Base.1.0.0.json
  lib-utilities/etc/ResourceEvent.1.0.0.json
  lib-utilities/etc/TaskEvent.1.0.0.json
Labels: type:bug, prio:normal, status:in-progress

#649 ODIM-20 : allow just one instance of odim-controller to be active at a time
  odim-controller/scripts/odim-controller.py
Labels: type:techdebt, prio:normal, status:in-progress

#650 Implemented Insert and Eject VirtualMedia for Lenovo plugin
  plugin-lenovo/lphandler/common.go
  plugin-lenovo/lphandler/managers.go
  plugin-lenovo/lphandler/managers_test.go
  plugin-lenovo/lpmodel/managers.go
  plugin-lenovo/main.go
Labels: type:feature, prio:normal, status:in-progress

#651 Added actions for get on virtual media (#26)
  lib-dmtf/model/manager.go
  plugin-lenovo/lphandler/getResource.go
Labels: type:feature, prio:normal, status:in-progress

#652 ODIM-20 : script for setting up deployment node
  docker-images.sh
  odim-controller/scripts/setup_deployment_node.sh
Labels: type:techdebt, prio:normal, status:in-progress

#648 Sync plugin-redfish/README.md changes made in main branch with development
  plugin-redfish/README.md
Labels: prio:normal, status:in-progress, type:doc

#653 ODIM-20 : build ODIMRA images in setup_deployment_node.sh
  odim-controller/scripts/setup_deployment_node.sh
Labels: type:techdebt, prio:normal, status:in-progress

#658 plugin tls fix and event fix handling format fix
  lib-rest-client/go.sum
  lib-rest-client/pmbhandle/rest.go
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  plugin-redfish/rfpmessagebus/publish.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/go.sum
  svc-aggregation/system/pluginHealthCheck.go
  svc-events/events/publishevttosubscriber.go
  svc-events/go.sum
Labels: type:bug, prio:high, status:in-progress

#656 Troubleshooting readme (#14)
  docs/Troubleshooting.md
Labels: prio:normal

#655 Phase 3 Getting Started Readme Documentation Updates (#13) - Pushing to upstream Dev
  README.md
  docs/images/kubernetes_images.png
  docs/images/odimra_images.png
Labels: prio:normal

#659 ODIM-20 : restart nginx after keepalived is configured
  odim-controller/odimra/roles/configure-keepalived/tasks/main.yaml
Labels: type:techdebt, prio:normal, status:in-progress

#660 Updating Telemetry Services APIs section and merging to dev upstream
  docs/README.md
  svc-telemetry/README.md
Labels: prio:normal

#661 Added support for UpdateService.StartUpdate action in Lenovo
  plugin-lenovo/lphandler/update.go
  plugin-lenovo/lphandler/update_test.go
  plugin-lenovo/main.go
Labels: type:feature, prio:normal, status:in-progress
