Repository ODIM-Project/ODIM, pull requests merged in 2021-01, with the labels that each got.

#305 Issue-279 use fsnotify logic in all micro services to track the config file changes
  lib-utilities/common/trackconfig.go
  lib-utilities/config/config.go
  plugin-redfish/go.mod
  plugin-redfish/main.go
  plugin-redfish/rfputilities/utility.go
  svc-account-session/main.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/main.go
  svc-events/evcommon/common.go
  svc-events/main.go
  svc-fabrics/main.go
  svc-managers/main.go
  svc-managers/mgrcommon/common.go
  svc-managers/mgrmodel/manager.go
  svc-managers/mgrmodel/manager_test.go
  svc-systems/main.go
  svc-systems/scommon/common.go
  svc-systems/systems/getresource.go
  svc-systems/systems/getresource_test.go
  svc-task/main.go
  svc-update/go.mod
  svc-update/go.sum
  svc-update/main.go
Labels: enhancement

#313 Issue-312 delete compute isn't sending chassis removal event
  svc-aggregation/system/deleteaggregationsource.go
Labels: prio:high, status:in-progress, type:bug

#319 Issue-316 Update to /etc/hosts file should be copied to the pod /etc/hosts file without restart
  install/Docker/dockerfiles/Dockerfile.odim
  install/Docker/dockerfiles/scripts/add-hosts.go
  install/Docker/dockerfiles/scripts/add-hosts/add-hosts.go
  install/Docker/dockerfiles/scripts/add-hosts/go.mod
  install/Docker/dockerfiles/scripts/add-hosts/go.sum
  install/Docker/dockerfiles/scripts/build_odim.sh
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_grfplugin.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_update.sh
Labels: type:feature

#323 Issue-320 Event published from ODIM RA to NB client is not following redfish standard event schema
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
Labels: prio:high, status:resolved, type:bug

#326 Issue-322 Update Message registry in ODIM
  lib-utilities/etc/Base.1.7.0.json
  lib-utilities/etc/Base.1.8.0.json
  lib-utilities/etc/Base.1.8.1.json
  lib-utilities/etc/Base.1.8.2.json
  lib-utilities/etc/Composition.1.0.1.json
  lib-utilities/etc/JobEvent.1.0.0.json
  lib-utilities/etc/LogService.1.0.0.json
  lib-utilities/etc/NetworkDevice.1.0.0.json
  lib-utilities/etc/NetworkDevice.1.0.1.json
  lib-utilities/etc/Redfish_1.1.0_PrivilegeRegistry.json
  lib-utilities/etc/ResourceEvent.1.0.3.json
  lib-utilities/etc/StorageDevice.1.0.0.json
  lib-utilities/etc/TaskEvent.1.0.2.json
Labels: prio:high, type:feature

#330 [Issue 321] update setup_kafka.sh for accommodating listener.security.protocol.map for exposing KAFKA for external usage
  install/Docker/dockerfiles/scripts/setup_kafka.sh
Labels: type:bug

#332 Issue-331 Fix redfish validator issues
  svc-aggregation/system/connectionmethods.go
  svc-aggregation/system/connectionmethods_test.go
  svc-aggregation/system/get_resource.go
  svc-aggregation/system/get_resource_test.go
  svc-api/go.sum
  svc-api/handle/chassis.go
  svc-api/handle/handlers.go
Labels: prio:high, type:bug

#334 [Issue-324] Updated start scripts to pick HA enabled consul & fixed build_script to exit on failure
  build_images.sh
  install/Docker/dockerfiles/scripts/build_odim.sh
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_update.sh
Labels: prio:high, type:bug, type:feature

#335 Issue-331 Fix redfish validator issues in Release_21.01 branch
  svc-aggregation/system/connectionmethods.go
  svc-aggregation/system/connectionmethods_test.go
  svc-aggregation/system/get_resource.go
  svc-aggregation/system/get_resource_test.go
  svc-api/go.sum
  svc-api/handle/chassis.go
  svc-api/handle/handlers.go
Labels: prio:high, type:bug

#338 Issue-337 Remove add-hosts function calling from in all micro service start script
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_grfplugin.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_update.sh
Labels: prio:high, status:in-progress, type:bug

#343 Issue-339 Change type of OriginOfCondition from string to Object in URP
  plugin-unmanaged-racks/redfish/events.go
  plugin-unmanaged-racks/rest/events_listener.go
  plugin-unmanaged-racks/rest/module_test.go
Labels: prio:high, status:in-progress, type:feature

#344 Issue-343 Change type of OriginOfCondition from string to Object in URP in Release_21.01 branch
  plugin-unmanaged-racks/redfish/events.go
  plugin-unmanaged-racks/rest/events_listener.go
  plugin-unmanaged-racks/rest/module_test.go
Labels: prio:high, type:feature

#346 Issue 341: Adding service root structure to the lib-dmtf
  lib-dmtf/go.sum
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/Chassis_test.go
  lib-dmtf/model/ComputerSystem.go
  lib-dmtf/model/ComputerSystem_test.go
  lib-dmtf/model/Links.go
  lib-dmtf/model/serviceRoot.go
Labels: type:bug

#350 Issue 342: Changing Redfish Version from 1.8.0 to 1.11.1
  svc-api/handle/handlers.go
Labels: prio:low, status:in-progress, type:bug

#353 issue-347 : Change the names of docker images created
  build_images.sh
Labels: prio:normal, status:in-progress, type:techdebt

#359 Issue 357 - Addressed API and deployment readme review comments (For Release branch)
  README.md
  docs/README.md
  svc-aggregation/README.md
  svc-managers/README.md
  svc-systems/README.md
  svc-task/README.md
  svc-update/README.md
Labels: prio:normal, status:new, type:doc

#363 issue-361 : Updated link of kafka source bundle in dockerfiles
  build/Kafka/Dockerfiles/Dockerfile.kafka
  build/Kafka/Dockerfiles/Dockerfile.zookeeper
  install/Docker/dockerfiles/Dockerfile.kafka
  install/Docker/dockerfiles/Dockerfile.zookeeper
Labels: prio:high, status:in-progress, type:bug

#365 Issue 364 - fixed broken image links
  README.md
Labels: prio:normal, status:new, type:doc
