Repository ODIM-Project/ODIM, pull requests merged in 2021-11, with the labels that each got.

#704 Odim 56:Adding Changes related to verifying the BMC address uniqueness
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/common.go
  svc-aggregation/system/rediscoverinventory.go
  svc-aggregation/system/reset_test.go
  svc-aggregation/system/systemstate.go
  svc-aggregation/system/update.go
Labels: type:bug, prio:normal, status:in-progress

#705 Removing docker based workflow as we have moved to k8s
  .github/workflows/build_deploy_test.yml
Labels: type:techdebt, prio:low, status:in-progress

#686 Changes to "UpdateService" section + other updates as per downstream document + BMC edits
  docs/README.md
Labels: type:doc

#707 Added audit logs
  svc-api/handle/account.go
  svc-api/handle/aggregator.go
  svc-api/handle/chassis.go
  svc-api/handle/events.go
  svc-api/handle/fabrics.go
  svc-api/handle/handlers.go
  svc-api/handle/managers.go
  svc-api/handle/role.go
  svc-api/handle/sessions.go
  svc-api/handle/systems.go
  svc-api/handle/task.go
  svc-api/handle/telemetry.go
  svc-api/handle/update.go
  svc-api/router/router.go
Labels: prio:low

#708 Odim 57:Adding logic to save to undelivered events
  svc-events/evcommon/common.go
  svc-events/evcommon/common_test.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/submittestevent.go
  svc-events/evmodel/events.go
Labels: type:feature, prio:normal, status:in-progress

#709 Odim 5368: Update protoc version to latest
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-messagebus/go.mod
  lib-messagebus/go.sum
  lib-persistence-manager/go.sum
  lib-utilities/go.mod
  lib-utilities/go.sum
  lib-utilities/proto/account/account.pb.go
  lib-utilities/proto/aggregator/aggregator.pb.go
  lib-utilities/proto/auth/odim_auth.pb.go
  lib-utilities/proto/chassis/chassis.pb.go
  lib-utilities/proto/events/events.pb.go
  lib-utilities/proto/fabrics/fabrics.pb.go
  lib-utilities/proto/managers/managers.pb.go
  lib-utilities/proto/role/role.pb.go
  lib-utilities/proto/session/session.pb.go
  lib-utilities/proto/systems/systems.pb.go
  lib-utilities/proto/task/task.pb.go
  lib-utilities/proto/telemetry/telemetry.pb.go
  lib-utilities/proto/update/update.pb.go
  plugin-dell/go.mod
  plugin-dell/go.sum
  plugin-lenovo/go.mod
  plugin-lenovo/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-telemetry/go.mod
  svc-telemetry/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: prio:normal

#710 ODIM-62 update configuration file with message bus info
  .github/workflows/odimra_deployment.yml
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/unit_test_db_confighelp.go
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/constants.go
  lib-utilities/config/mockconfig.go
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  svc-aggregation/agmessagebus/publish.go
  svc-aggregation/main.go
  svc-events/consumer/consumer.go
  svc-events/consumer/consumer_test.go
  svc-events/main.go
  svc-task/main.go
  svc-task/tmessagebus/publish.go
  svc-telemetry/go.mod
  svc-telemetry/go.sum
Labels: type:feature, prio:normal, status:in-progress
