Repository ODIM-Project/ODIM, pull requests merged in 2021-04, with the labels that each got.

#495 Issue-494 handle search and filter case of processor summary model(Intel(R))
  svc-systems/systems/getresource.go
Labels: prio:low, status:in-progress, type:bug

#498 Odim 4414
  lib-persistence-manager/persistencemgr/redis.go
  svc-aggregation/agmodel/system.go
Labels: prio:normal, status:in-progress, type:bug

#501 [Issue-499] Fix for Adding a new connection method in kube_deploy_nodes.yaml after editing and deleting it doesn't get reflected in ODIM
  svc-aggregation/agcommon/common.go
Labels: prio:high, status:resolved, type:bug

#509 Odim 507:Updating the routes of message registries
  svc-api/handle/chassis.go
  svc-api/handle/handlers.go
  svc-api/router/router.go
  svc-api/rpc/chassis.go
Labels: prio:normal, status:in-progress, type:bug

#508 Odim 502: BDD issue: Search for system resources to check if any data remains after deleting a BMC fails
  svc-aggregation/agmodel/system.go
Labels: prio:normal, status:resolved, type:bug

#505 Issue-504 Expose telemetry service related resources
  plugin-redfish/main.go
Labels: prio:normal, status:in-progress, type:feature

#491 ODIM-484 expose chassis resource uris in dell plugin
  .github/workflows/build_deploy_test.yml
  Makefile
  build/DELLPlugin/Dockerfile.dell_plugin
  build/DELLPlugin/command.sh
  build/DELLPlugin/dell_plugin.service
  build/DELLPlugin/edit_config.sh
  build/DELLPlugin/start_plugin.sh
  build/docker-compose.yml
  plugin-dell/main.go
Labels: prio:low, status:resolved, type:bug

#516 Issue 514: Make use of logrus package in DELL plugin for logging
  plugin-dell/config/config.go
  plugin-dell/dphandler/basicAuth.go
  plugin-dell/dphandler/biosSettings.go
  plugin-dell/dphandler/biosSettings_test.go
  plugin-dell/dphandler/bootorder.go
  plugin-dell/dphandler/common.go
  plugin-dell/dphandler/createSession.go
  plugin-dell/dphandler/getResource.go
  plugin-dell/dphandler/managers.go
  plugin-dell/dphandler/pluginStatus.go
  plugin-dell/dphandler/redfishEvents.go
  plugin-dell/dphandler/reset.go
  plugin-dell/dphandler/storage.go
  plugin-dell/dphandler/subscribeEvents.go
  plugin-dell/dphandler/update.go
  plugin-dell/dpmessagebus/publish.go
  plugin-dell/dpmiddleware/basicAuthenticate.go
  plugin-dell/dputilities/redfishClient.go
  plugin-dell/dputilities/utility.go
  plugin-dell/go.mod
  plugin-dell/main.go
Labels: prio:normal, status:in-progress, type:techdebt

#517 odim 506:Adding power model to lib-dmtf
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/power.go
Labels: prio:normal, status:in-progress, type:techdebt

#519 Add resource model for telemetry service
  lib-dmtf/model/telemetry.go
Labels: prio:normal, status:resolved, type:techdebt

#521 odim 520:Adding the thermal model to lib-dmtf
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/thermal.go
Labels: prio:normal, status:in-progress, type:techdebt

#515 Issue 512: Make use of data models defined in lib-dmtf package in GRF plugin.
  lib-dmtf/model/events.go
  plugin-redfish/go.mod
  plugin-redfish/rfphandler/managers.go
  plugin-redfish/rfphandler/storage_test.go
  plugin-redfish/rfpmessagebus/publish.go
  plugin-redfish/rfpmodel/Chassis.go
  plugin-redfish/rfpmodel/ComputerSystem.go
  plugin-redfish/rfpmodel/Device.go
  plugin-redfish/rfpmodel/Events.go
  plugin-redfish/rfpmodel/Links.go
  plugin-redfish/rfpmodel/ServiceRoot.go
  plugin-redfish/rfpmodel/storage.go
  plugin-redfish/rfpresponse/managersResponse.go
  plugin-redfish/rfputilities/redfishClient.go
Labels: prio:normal, status:in-progress, type:techdebt

#513 Issue 511: Correct the usage of logrus package in the plugin-redfish
  plugin-redfish/config/config.go
  plugin-redfish/main.go
  plugin-redfish/rfphandler/basicAuth.go
  plugin-redfish/rfphandler/biosSettings.go
  plugin-redfish/rfphandler/bootorder.go
  plugin-redfish/rfphandler/getResource.go
  plugin-redfish/rfphandler/managers.go
  plugin-redfish/rfphandler/pluginStatus.go
  plugin-redfish/rfphandler/reset.go
  plugin-redfish/rfphandler/storage.go
  plugin-redfish/rfphandler/subscribeEvents.go
  plugin-redfish/rfphandler/update.go
  plugin-redfish/rfpmessagebus/publish.go
  plugin-redfish/rfpmiddleware/basicAuthenticate.go
  plugin-redfish/rfputilities/redfishClient.go
Labels: prio:normal, status:resolved, type:techdebt

#528 odim 525:Updating the completed task index for the task which is having task state as Exception
  svc-task/thandle/thandle.go
  svc-task/tmodel/tmodel.go
  svc-task/tmodel/tmodel_test.go
Labels: prio:normal, status:in-progress, type:bug

#529 odim 526:Adding the condition to check plugin service name in device subscription
  svc-events/events/deletesubscription.go
Labels: prio:normal, status:in-progress, type:bug
