Repository ODIM-Project/ODIM, pull requests merged in 2021-05, with the labels that each got.

#530 odim 317:Adding the missing step of dell plugin in build_image.sh
  build_images.sh
Labels: prio:normal, status:in-progress, type:bug

#531 Issue 522: Change the data type of lib-dmtf Oem for accommodating any data
  lib-dmtf/model/Links.go
Labels: prio:normal, status:resolved, type:bug

#535 Telemetry proto files
  lib-utilities/proto/telemetry/telemetry.micro.go
  lib-utilities/proto/telemetry/telemetry.pb.go
  lib-utilities/proto/telemetry/telemetry.proto
  svc-api/go.mod
  svc-api/go.sum
  svc-api/router/router.go
Labels: prio:normal, status:in-progress, type:feature

#536 issue-317 : Reorder tls config suites according to preference
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
Labels: prio:normal, status:in-progress, type:feature

#537 Issue 533: Correct BIOS schema to lib-dmtf
  lib-dmtf/model/ComputerSystem.go
Labels: prio:normal, status:resolved, type:techdebt

#542 issue-317:Adding the missing processor route
  plugin-dell/main.go
Labels: prio:high, status:in-progress, type:bug

#540 Telemetry service implementation under api service and lib-utilities
  lib-utilities/config/odimra_config.json
  lib-utilities/services/name.go
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  svc-api/go.mod
  svc-api/handle/handlers.go
  svc-api/handle/telemetry.go
  svc-api/handle/telemetry_test.go
  svc-api/models/serviceroot.go
  svc-api/router/router.go
  svc-api/rpc/telemetry.go
Labels: prio:normal, status:in-progress, type:feature

#500 Odim 497 - Handled the invalid basic authorizations
  svc-api/main.go
Labels: status:in-progress, type:bug

#543 Issue 317 updating reset response
  plugin-dell/dphandler/reset.go
Labels: prio:high, status:resolved, type:bug

#547 issue-546 : fix for copying docker images during upgrade
  odim-controller/odimra/pre_upgrade.yaml
  odim-controller/odimra/roles/pre-upgrade/tasks/main.yaml
  odim-controller/scripts/odim-controller.py
Labels: prio:high, status:in-progress, type:bug

#550 Updated the payload for create volume as per 4.40 firmware version of Dell server
  plugin-dell/dphandler/storage.go
  plugin-dell/dphandler/storage_test.go
  plugin-dell/dpmodel/storage.go
Labels: prio:low, status:in-progress, type:feature
