Repository ODIM-Project/ODIM, pull requests merged in 2021-09, with the labels that each got.

#664 Odim 5195 Update valid message argument
  svc-events/events/evtsubscription.go
Labels: type:bug, prio:normal, status:in-progress

#666 ODIM-20 : keepalived to restart nginx on changing state to master
  odim-controller/odimra/roles/configure-keepalived/tasks/main.yaml
  odim-controller/odimra/roles/configure-keepalived/templates/action_script.sh.j2
  odim-controller/odimra/roles/configure-proxy/tasks/main.yaml
  odim-controller/odimra/roles/k8-delete-image/tasks/main.yaml
  odim-controller/odimra/roles/odimra-delete-image/tasks/main.yaml
  odim-controller/odimra/roles/plugin-delete-image/tasks/main.yaml
  odim-controller/odimra/roles/post-uninstall/tasks/main.yaml
  odim-controller/odimra/roles/remove-plugin/tasks/main.yaml
  odim-controller/scripts/odim-controller.py
Labels: type:techdebt, prio:normal, status:in-progress

#667 update service action response fix (#39)
  svc-update/go.sum
  svc-update/update/getresources.go
  svc-update/update/getresources_test.go
Labels: type:bug, prio:normal, status:in-progress

#669 Skip inventory share for non Compute plugin type
  svc-aggregation/system/pluginHealthCheck.go
Labels: type:techdebt, prio:normal, status:in-progress

#668 ODIM-5064 Fix airship issue regarding search and filter
  svc-aggregation/system/common.go
Labels: type:bug, prio:normal, status:in-progress

#670 ODIM-5227 Fixed issue while adding multiple servers is failing with panic error
  svc-aggregation/system/common.go
Labels: type:bug, prio:normal, status:in-progress

#671 odim-5189 : Updated metadata info (#24)
  docs/README.md
  lib-utilities/common/constants.go
  svc-api/handle/handlers.go
  svc-telemetry/README.md
  svc-telemetry/telemetry/telemetry.go
  svc-telemetry/tlresponse/telemetryservice.go
Labels: type:bug, prio:normal

#672 odim-5191:removed back slash (#25)
  svc-api/handle/handlers.go
Labels: type:bug, prio:normal

#673 ODIM 5194 Added omitempty in json tag
  lib-dmtf/model/ComputerSystem.go
Labels: type:bug, prio:normal, status:in-progress

#674 Odim 5190: Removed default jsonschema as true
  lib-utilities/response/response.go
  lib-utilities/services/rpcService.go
  svc-telemetry/tlresponse/telemetryservice.go
Labels: type:bug, prio:normal

#678 ODIM-20 : Updated docker image and helm packages versions of the services and plugins
  build_images.sh
  docker-images.sh
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.dellplugin
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.lenovoplugin
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.telemetry
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/Dockerfile.urplugin
  odim-controller/helmcharts/account-session/Chart.yaml
  odim-controller/helmcharts/account-session/values.yaml
  odim-controller/helmcharts/aggregation/Chart.yaml
  odim-controller/helmcharts/aggregation/values.yaml
  odim-controller/helmcharts/api/Chart.yaml
  odim-controller/helmcharts/api/values.yaml
  odim-controller/helmcharts/etcd-ha/Chart.yaml
  odim-controller/helmcharts/etcd/Chart.yaml
  odim-controller/helmcharts/events/Chart.yaml
  odim-controller/helmcharts/events/values.yaml
  odim-controller/helmcharts/fabrics/Chart.yaml
  odim-controller/helmcharts/fabrics/values.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/Chart.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/values.yaml
  odim-controller/helmcharts/managers/Chart.yaml
  odim-controller/helmcharts/managers/values.yaml
  odim-controller/helmcharts/odimra-config/Chart.yaml
  odim-controller/helmcharts/odimra-k8s-access-config/Chart.yaml
  odim-controller/helmcharts/odimra-pv-pvc/Chart.yaml
  odim-controller/helmcharts/odimra-secret/Chart.yaml
  odim-controller/helmcharts/redis-ha/Chart.yaml
  odim-controller/helmcharts/redis-ha/values.yaml
  odim-controller/helmcharts/redis/Chart.yaml
  odim-controller/helmcharts/redis/values.yaml
  odim-controller/helmcharts/systems/Chart.yaml
  odim-controller/helmcharts/systems/values.yaml
  odim-controller/helmcharts/task/Chart.yaml
  odim-controller/helmcharts/task/values.yaml
  odim-controller/helmcharts/telemetry/Chart.yaml
  odim-controller/helmcharts/update/Chart.yaml
  odim-controller/helmcharts/update/values.yaml
  odim-controller/helmcharts/urplugin/urplugin/Chart.yaml
  odim-controller/helmcharts/urplugin/urplugin/values.yaml
  odim-controller/odimra/group_vars/all/all.yaml
  odim-controller/odimra/group_vars/all/requirements.yaml
  odim-controller/odimra/roles/configure-keepalived/tasks/main.yaml
  odim-controller/odimra/roles/configure-proxy/tasks/main.yaml
  odim-controller/odimra/roles/k8-copy-image/tasks/main.yaml
  odim-controller/odimra/roles/pre-install/tasks/main.yaml
  odim-controller/scripts/odim-controller.py
Labels: type:techdebt, prio:normal, status:in-progress

#679 ODIM-20 : fix github action failure
  .github/workflows/odimra_deployment.yml
  odim-controller/scripts/odim-controller.py
Labels: type:bug, prio:normal, status:in-progress

#677 Modified the code to get latest data from device based on systemreset…
  plugin-lenovo/lphandler/reset.go
  svc-aggregation/system/pluginHealthCheck.go
  svc-aggregation/system/rediscoverinventory.go
  svc-systems/systems/bootorder.go
  svc-systems/systems/getresource.go
Labels: type:feature, prio:normal, status:in-progress

#680 Added precondition to check odimra deployed while adding new node to k8s cluster before deploying ODIM
  odim-controller/scripts/odim-controller.py
Labels: type:bug, prio:normal, status:in-progress

#682 Storage struct fix on data type
  lib-dmtf/model/storage.go
Labels: type:bug, prio:high, status:in-progress

#683 ODIM 5230 Added new error message in lib utilities
  lib-utilities/response/errorresponse.go
  lib-utilities/response/errorresponse_test.go
  lib-utilities/response/response.go
Labels: type:bug, status:new, prio:normal

#681 Fixed the UpdateService.SimpleUpdate uses of Invalid property "@Redfish.OperationApplyTimeSupport"
  plugin-lenovo/lphandler/update.go
  svc-update/update/common.go
  svc-update/update/getresources.go
  svc-update/update/getresources_test.go
  svc-update/update/simpleUpdate.go
  svc-update/update/simpleUpdate_test.go
  svc-update/uresponse/updateservice.go
Labels: type:bug, prio:normal, status:in-progress
