Repository ODIM-Project/ODIM, pull requests merged in 2021-10, with the labels that each got.

#687 ODIM-46 : Increase the channel buffer size used for processing events
  .github/workflows/odimra_deployment.yml
  lib-dmtf/model/storage.go
  lib-messagebus/datacommunicator/kafkacomm.go
  lib-utilities/common/jobqueue.go
  lib-utilities/common/jobqueue_test.go
  lib-utilities/common/workerpool_test.go
  plugin-dell/main.go
  plugin-lenovo/main.go
  plugin-redfish/main.go
  svc-aggregation/system/pluginHealthCheck.go
  svc-events/consumer/consumer.go
  svc-events/consumer/consumer_test.go
  svc-events/main.go
Labels: type:techdebt, prio:normal, status:in-progress

#688 ODIM-20 : Fixed regeneration of etcd certs during secrets upgrade
  odim-controller/odimra/roles/deploy-plugin/tasks/main.yaml
  odim-controller/odimra/roles/pre-install/tasks/main.yaml
  odim-controller/scripts/gen_odimra_certs.sh
Labels: type:techdebt, prio:normal, status:in-progress

#689 Odim 47:Fix for odim etcd fails to form quorum when all master nodes are restarted
  odim-controller/helmcharts/etcd-ha/templates/etcd-ha-deployment.yaml
  odim-controller/helmcharts/etcd-ha/values.yaml
  odim-controller/odimra/roles/install/tasks/main.yaml
Labels: type:bug, prio:high, status:in-progress

#691 Odim 49:Updating the Error response in create and delete volume
  plugin-lenovo/go.sum
  plugin-lenovo/lphandler/handler.go
Labels: prio:high, type:feature, status:in-progress
