Repository ODIM-Project/ODIM, pull requests merged in 2021-02, with the labels that each got.

#373 Issue 362: Route missing for PATCHing fabric port
  svc-api/router/router.go
Labels: type:feature

#380 issue-375 : monitor and exit when odim-ra process is not running
  install/Docker/dockerfiles/scripts/consul-entrypoint.sh
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_grfplugin.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_update.sh
Labels: prio:normal, status:in-progress, type:bug

#383 Odim 377:Updating the task response in add aggregation source
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/common.go
  svc-aggregation/system/update.go
Labels: prio:high, status:in-progress, type:bug

#382 Issue 374: Fabric APIs with Schema 2020.3 are not working from ODIM
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/ComputerSystem.go
  lib-dmtf/model/Links.go
  lib-dmtf/model/addressPool.go
  svc-fabrics/fabrics/common.go
  svc-fabrics/go.mod
  svc-fabrics/go.sum
Labels: prio:high, status:in-progress, type:bug

#385 Issue 378: Fabric added event is not received in ODIM
  svc-events/events/publishevttosubscriber.go
Labels: prio:high, status:in-progress, type:bug

#387 Odim 318 : Fixing makefile for urp build and cleanup issue
  Makefile
  build/cert_generator/generate_odimra_cert.sh
  build/cleanupbuild.sh
  build/docker-compose.yml
  build/odimra/build.sh
  build/odimra/builddep.sh
  build/plugin-unmanaged-racks/Dockerfile
  plugin-unmanaged-racks/Makefile
Labels: prio:high, status:in-progress, type:bug

#389 Odim 388: modified response for malformed json while creating chassis
  svc-api/handle/chassis.go
  svc-api/handle/chassis_test.go
Labels: prio:low, status:in-progress, type:bug

#394 Odim 311: Event subscription creation fix for multiple 'OriginResources' with same id
  svc-events/events/evtsubscription.go
Labels: prio:low, status:in-progress, type:bug

#395 Issue-310 fix race conditions in odimra
  install/Docker/dockerfiles/scripts/build_odim.sh
  lib-utilities/common/trackconfig.go
  lib-utilities/config/httpConfig.go
  svc-account-session/main.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/system/common.go
  svc-api/main.go
  svc-events/consumer/consumer.go
  svc-events/evcommon/common.go
  svc-events/main.go
  svc-fabrics/main.go
  svc-managers/mgrcommon/common.go
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/main.go
  svc-systems/scommon/common.go
  svc-task/main.go
  svc-update/main.go
Labels: prio:high, status:in-progress, type:bug

#401 odim 400:Adding the fabric ,switch ,collection and manager model
  lib-dmtf/model/ComputerSystem.go
  lib-dmtf/model/Links.go
  lib-dmtf/model/addressPool.go
  lib-dmtf/model/common.go
  lib-dmtf/model/fabric.go
  lib-dmtf/model/manager.go
  lib-dmtf/model/resourceCollection.go
  lib-dmtf/model/switch.go
Labels: prio:normal, status:resolved, type:techdebt

#405 Odim 396: Added logs to debug reinitialization of WriteConnection Pool and corrected error messages
  lib-persistence-manager/persistencemgr/redis.go
  lib-utilities/services/task.go
  svc-aggregation/system/addaggregationsource.go
Labels: prio:high, status:in-progress, type:bug

#403 Issue 391: PCIeDevices spelt as PCIDevices in GRF handler URL
  plugin-redfish/main.go
Labels: prio:normal, status:resolved, type:bug

#406 Fix on update service start script
  install/Docker/dockerfiles/scripts/start_update.sh
Labels: prio:high, status:in-progress, type:bug

#358 Issue 357 - Addressed API and deployment readme review comments
  README.md
  docs/README.md
  svc-aggregation/README.md
  svc-managers/README.md
  svc-systems/README.md
  svc-task/README.md
  svc-update/README.md
Labels: prio:normal, status:new, type:doc

#411 Issue-410 fix: split host address and assign ip to host variable
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
Labels: prio:high, status:in-progress, type:bug

#402 Issue 390 task 1: Fix for panic when chassis resource is not found
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/main.go
  svc-systems/plugin/client.go
Labels: prio:high, status:in-progress, type:bug

#413 issue-381 : Remove additional setup script used for kafka, zookeeper
  install/Docker/dockerfiles/Dockerfile.kafka
  install/Docker/dockerfiles/Dockerfile.zookeeper
  install/Docker/dockerfiles/scripts/setup_kafka.sh
  install/Docker/dockerfiles/scripts/setup_zookeeper.sh
  install/Docker/dockerfiles/scripts/start_kafka.sh
  install/Docker/dockerfiles/scripts/start_zookeeper.sh
Labels: prio:normal, status:in-progress, type:feature

#415 odim 414:Updating the id reference in the fabric, switch ,manager and address pool dmtf model
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/fabric.go
  lib-dmtf/model/manager.go
  lib-dmtf/model/switch.go
Labels: prio:normal, status:in-progress, type:bug

#418 Issue 416: Not able to add native vlan addresspool
  lib-dmtf/model/addressPool.go
Labels: prio:high, status:in-progress, type:bug

#421 Issue 390 task 4: Modify the PATCH on individual device chassis resource for newly added fabric chassis resources
  svc-systems/chassis/fabric.go
  svc-systems/chassis/fabric_test.go
  svc-systems/chassis/fabricresource.go
  svc-systems/chassis/update.go
  svc-systems/chassis/updatefabricresource.go
  svc-systems/chassis/updatefabricresource_test.go
Labels: prio:high, status:in-progress, type:bug

#419 Issue-410 split remote address and assign ip to event struct in grf plugin
  plugin-redfish/rfphandler/redfishEvents.go
Labels: prio:high, status:in-progress, type:bug

#422 Issue-410 use http handler event routers in dell plugin
  build/Kafka/Dockerfiles/Dockerfile.kafka
  build/Kafka/Dockerfiles/Dockerfile.zookeeper
  plugin-dell/config/dell_config.json
  plugin-dell/dphandler/redfishEvents.go
  plugin-dell/go.sum
  plugin-dell/main.go
Labels: prio:normal, status:in-progress, type:bug

#424 Issue 390: GET on Switch Chasis is giving 500 internal service error
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/Links.go
  svc-systems/chassis/fabric.go
  svc-systems/chassis/fabric_test.go
  svc-systems/chassis/fabricresource.go
  svc-systems/chassis/fabricresource_test.go
  svc-systems/chassis/get.go
  svc-systems/chassis/get_collection.go
  svc-systems/chassis/get_collection_test.go
  svc-systems/chassis/update.go
  svc-systems/chassis/updatefabricresource.go
  svc-systems/chassis/updatefabricresource_test.go
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/main.go
  svc-systems/plugin/client.go
  svc-systems/plugin/client_mock.go
  svc-systems/smodel/fabrics.go
Labels: prio:high, status:resolved, type:bug

#425 issue-381 : Use derived service name of consul in docker entrypoint scripts
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_grfplugin.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_update.sh
  install/Docker/dockerfiles/scripts/start_urplugin.sh
Labels: prio:normal, status:in-progress, type:feature

#429 adding logs to task.go, system.go and redis.go files
  lib-persistence-manager/persistencemgr/redis.go
  svc-aggregation/agmodel/system.go
  svc-task/tmodel/tmodel.go
Labels: prio:high, status:resolved, type:techdebt

#430 issue-381 : Change nginx path used by kubespray
  odim-controller/kubespray/configure-kubespray.sh
Labels: prio:normal, status:in-progress, type:feature

#426 issue-317 : Dockerfiles for DELL plugin
  install/Docker/dockerfiles/Dockerfile.dellplugin
  install/Docker/dockerfiles/Dockerfile.odim
  install/Docker/dockerfiles/scripts/start_dellplugin.sh
Labels: prio:normal, status:in-progress, type:feature

#433 odim 432:Adding Port model to lib-dmtf package
  lib-dmtf/model/port.go
Labels: prio:normal, status:in-progress, type:techdebt

#436 Issue 348- Adding server failed after master redis pod reset
  lib-persistence-manager/persistencemgr/redis.go
  odim-controller/helmcharts/redis-ha/values.yaml
Labels: prio:high, status:in-progress, type:bug

#437 issue-434 : Updatedd odim-controller usage logs
  install/Docker/dockerfiles/scripts/start_events.sh
  odim-controller/.gitignore
  odim-controller/helmcharts/events/templates/_helpers.tpl
  odim-controller/helmcharts/events/templates/deployment.yaml
  odim-controller/helmcharts/events/templates/service.yaml
  odim-controller/scripts/odim-controller.py
Labels: prio:normal, status:in-progress, type:bug

#439 issue-438 : Update log messages during plugin add and upgrade operation
  odim-controller/odimra/deploy_plugin.yaml
  odim-controller/odimra/roles/deploy-plugin/tasks/main.yaml
  odim-controller/odimra/roles/remove-plugin/tasks/main.yaml
  odim-controller/odimra/roles/upgrade-config/tasks/main.yaml
  odim-controller/odimra/roles/upgrade-thirdparty/tasks/main.yaml
  odim-controller/odimra/upgrade_plugin.yaml
  odim-controller/scripts/odim-controller.py
Labels: prio:normal, status:in-progress, type:techdebt

#435 Issue 399: Adding route for the individual processor in the GRF plugin
  plugin-redfish/main.go
Labels: prio:low, status:resolved, type:bug

#440 issue-438 : Use latest keytool options to generate JKS
  odim-controller/scripts/gen_odimra_certs.sh
Labels: prio:normal, status:in-progress, type:techdebt

#442 updated default redis configurations
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
Labels: prio:normal, status:in-progress, type:techdebt
