Repository ODIM-Project/ODIM, pull requests merged in 2022-07, with the labels that each got.

#925 ODIM-6117: As an ODIM user I want all the security hotspots listed in Sonarqube should be resolved
  odim-controller/scripts/odim-controller.py
Labels: type:bug, prio:normal, status:in-progress

#928 Merge to dev - Peer review comments
  README.md
Labels: prio:normal, status:in-progress, type:doc

#929 DeliveryRetryPolicy Added new property in event subscription
  svc-events/events/common.go
  svc-events/events/evtsubscription.go
  svc-events/events/getevtsubscription.go
  svc-events/evmodel/events.go
  svc-events/evresponse/events.go
Labels: prio:high, type:feature, status:in-progress

#926 Merge to dev - Message registries update
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#927 Merge to dev - Update AccountService, AggregationService, Chassis and System service APIs
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#930 Merge to dev - Undelivered (persist) events
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#931 Merge to dev - Update Responses for Sessions, Tasks, Aggregates and Managers services
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#933 Merge to dev - Snap 6 server support
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#934 Remove empty certificate link while getting manager info
  lib-dmtf/model/manager.go
Labels: type:bug, prio:normal, status:in-progress

#932 Bruce 5961:As a customer I want to see Volume capabilities under ODIM for ILO Gen10+ Snap 6 server
  lib-dmtf/model/resourceCollection.go
  lib-dmtf/model/storage.go
  plugin-lenovo/lphandler/getResource.go
  svc-aggregation/system/common.go
  svc-api/router/router.go
  svc-api/rpc/system.go
  svc-systems/systems/getresource.go
Labels: type:feature, prio:normal, status:in-progress

#935 Status code for license collection should be statusOK if no server is added
  svc-licenses/licenses/licenses.go
Labels: type:bug, prio:normal, status:in-progress

#936 Modify subtask collection response as per redfish specification
  svc-task/thandle/thandle.go
Labels: type:bug, prio:normal, status:in-progress

#939 Updated EventService, TelemetryService and LicenseService sections
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#940 Merge to dev - Updateservice responses
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#942 Updated event service and code improvement
  lib-utilities/common/constants.go
  svc-events/consumer/consumer_test.go
  svc-events/evcommon/common.go
  svc-events/events/common.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/submittestevent.go
  svc-events/rpc/events.go
Labels: prio:high, type:techdebt, status:in-progress

#943 Odim 6120:UT coverage for svc-aggregation
  svc-aggregation/agcommon/common_test.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/pluginHealthCheck.go
  svc-aggregation/system/pluginHealthCheck_test.go
  svc-aggregation/system/update_test.go
Labels: type:feature, prio:normal, status:in-progress

#945 Odim 6051:Implementing task for system reset
  svc-aggregation/agcommon/common.go
  svc-aggregation/agcommon/common_test.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/aggregate_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/pluginHealthCheck_test.go
  svc-systems/main.go
  svc-systems/plugin/client.go
  svc-systems/plugin/client_test.go
  svc-systems/rpc/chassis.go
  svc-systems/rpc/chassis_test.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/rpc/wrapers.go
  svc-systems/scommon/common.go
  svc-systems/scommon/common_test.go
  svc-systems/smodel/fabrics.go
  svc-systems/smodel/systems.go
  svc-systems/systems/bootorder.go
  svc-systems/systems/bootorder_test.go
  svc-systems/systems/common.go
  svc-systems/systems/getresource.go
  svc-systems/systems/reset.go
  svc-systems/systems/reset_test.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: prio:high, type:feature, status:in-progress

#946 odim-6295: Handle odim-controller.lock to resolve deploy/reset issue
  odim-controller/scripts/odim-controller.py
Labels: type:bug, prio:normal, status:in-progress

#947 odim 6214:Updating the logging condition
  svc-aggregation/system/common.go
  svc-events/evcommon/mock.go
  svc-events/events/publishevttosubscriber.go
  svc-events/evresponse/events.go
  svc-events/go.mod
  svc-events/go.sum
  svc-systems/systems/common.go
  svc-update/update/common.go
Labels: type:bug, prio:normal, status:in-progress

#949 Odim-6229 : Added actions and elements count in aggregates response body
  svc-aggregation/agresponse/aggregationsource.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/aggregate_test.go
Labels: type:bug, prio:normal, status:in-progress

#950 Odim 6217:Updating the volume creation request
  .github/workflows/odimra_deployment.yml
  plugin-dell/dphandler/storage.go
  plugin-dell/dphandler/storage_test.go
  plugin-dell/dpmodel/storage.go
  plugin-dell/go.mod
  plugin-dell/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  plugin-redfish/rfphandler/storage_test.go
  svc-systems/smodel/systems.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: type:bug, prio:high, status:in-progress

#948 BRUCE-6190 - After Redis DB auth changes, some pods go to CrashLoopBackOff state in multi node after upgrading secrets
  install/Docker/dockerfiles/scripts/redis-entrypointsetup.sh
  odim-controller/scripts/gen_odimra_certs.sh
Labels: type:bug, prio:normal, status:in-progress

#952 BRUCE-6349 - Redis sentinel connection is failing for POST APIs of urplugin
  plugin-unmanaged-racks/db/persistence.go
  plugin-unmanaged-racks/go.mod
  plugin-unmanaged-racks/go.sum
Labels: type:bug, prio:normal, status:in-progress

#954 Odim 5864:Adding logic to enable nat_outgoing for ipv6 requests
  install/Docker/dockerfiles/scripts/redis-entrypointsetup.sh
  odim-controller/kubespray/configure-kubespray.sh
  odim-controller/odimra/roles/configure-proxy/tasks/main.yaml
  odim-controller/scripts/odim-controller.py
Labels: prio:high, type:feature, status:in-progress

#955 Receive events based on the aggregates subscription
  svc-events/events/common.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/evmodel/events.go
  svc-events/rpc/events.go
Labels: prio:high, type:feature, status:in-progress

#956 Bruce 6339: Handling responses of telemetry and manager services
  svc-managers/mgrresponse/managers.go
  svc-telemetry/tlresponse/list.go
Labels: type:bug, prio:high, status:in-progress

#957 Odim-6275:Added logic to remove simpleupdate key from inmemory after removing the server
  svc-aggregation/agmodel/system.go
Labels: type:bug, prio:normal, status:in-progress

#958 Merge to dev - Reset system +volume creation response update
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#959 BRUCE-6330 - Setting Redis In-memory and On-disk password requests are coming during K8s installation via odim-controller
  odim-controller/scripts/odim-controller.py
Labels: type:bug, prio:normal, status:in-progress

#960 Merge to dev- Event subscription with aggregates
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#961 Odim 5401:Updating logic of subscribing and forwarding event for bmc and desitnation with IPv6 Address
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  odim-controller/odimra/roles/configure-proxy/tasks/plugins.yaml
  odim-controller/odimra/roles/deploy-plugin/tasks/proxy.yaml
  odim-controller/odimra/roles/update-proxy-conf/tasks/plugins.yaml
  svc-aggregation/agmodel/system.go
  svc-events/evcommon/mock.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/evmodel/events.go
Labels: prio:high, type:feature, status:in-progress

#963 Merge to dev - Updated all readmes in ODIM-Project repo
  lib-dmtf/README.md
  lib-messagebus/README.md
  lib-persistence-manager/README.md
  lib-utilities/README.md
  plugin-dell/README.md
  plugin-lenovo/README.md
  plugin-redfish/README.md
  svc-account-session/README.md
  svc-aggregation/README.md
  svc-api/README.md
  svc-events/README.md
  svc-fabrics/README.md
  svc-licenses/README.md
  svc-managers/README.md
  svc-task/README.md
  svc-telemetry/README.md
  svc-update/README.md
Labels: prio:normal, status:in-progress, type:doc

#964 Merge to dev - Modify configurations for services
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#962 Odim 6132: ODIM Profiles - Failure on Registry Prefixes
  svc-events/evresponse/events.go
Labels: type:bug, prio:normal, status:in-progress
