Repository ODIM-Project/ODIM, pull requests merged in 2022-11, with the labels that each got.

#1030 Bruce-6747: BiosAttribute url not getting listed in RegistryFileCollection
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-api/models/registries.go
Labels: type:bug, prio:normal, status:in-progress

#1032 Remove adding default subscription for each server
  build/Redis/createschema.sh
  install/Docker/dockerfiles/scripts/redis-createschema.sh
  svc-aggregation/system/rediscoverinventory_test.go
  svc-events/evcommon/common_test.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/evmodel/events.go
  svc-systems/chassis/delete_test.go
Labels: type:techdebt, prio:normal, status:in-progress

#1033 odim-6775: Increase the UT coverage for agcommon folder for aggregation service
  svc-aggregation/agcommon/common_test.go
Labels: type:bug

#1034 Set OriginResources is empty, while creating event subscription for empty originresource enhancement
  svc-events/events/common.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
Labels: type:techdebt, prio:normal, status:in-progress

#1036 Merge to dev - Log levels and support for logs in syslog format
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1042 BRUCE-6865: Fix the kafka config topic to set it odim-control-messages for intercomm messages
  lib-utilities/common/intercomm.go
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/mockconfig.go
  lib-utilities/config/odimra_config.json
  svc-aggregation/agmessagebus/publish.go
  svc-events/main.go
  svc-task/tmessagebus/publish.go
Labels: prio:high

#1043 Bruce-6816: Add process related logs under system collection
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-persistence-manager/persistencemgr/redis.go
  lib-utilities/common/constants.go
  lib-utilities/common/kubernetes.go
  lib-utilities/common/responses.go
  lib-utilities/logs/logger.go
  svc-api/handle/systems.go
  svc-api/handle/systems_test.go
  svc-api/main.go
  svc-api/router/router.go
  svc-api/rpc/system.go
  svc-api/rpc/system_test.go
  svc-systems/rpc/chassis.go
  svc-systems/rpc/chassis_test.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/systems/getresource.go
  svc-systems/systems/getresource_test.go
Labels: type:feature, prio:normal, status:in-progress
