Repository ODIM-Project/ODIM, pull requests merged in 2022-12, with the labels that each got.

#1045 Removed instances of Docker for cluster nodes
  docs/Troubleshooting.md
Labels: prio:normal, status:in-progress, type:doc

#1046 Add required fields in logs for api service
  lib-utilities/common/constants.go
  lib-utilities/common/responses.go
  lib-utilities/logs/logger.go
  svc-api/handle/account.go
  svc-api/handle/account_test.go
  svc-api/handle/aggregator.go
  svc-api/handle/aggregator_test.go
  svc-api/handle/chassis.go
  svc-api/handle/chassis_test.go
  svc-api/handle/events.go
  svc-api/handle/events_test.go
  svc-api/handle/fabrics.go
  svc-api/handle/fabrics_test.go
  svc-api/handle/handlers.go
  svc-api/handle/licenses.go
  svc-api/handle/licenses_test.go
  svc-api/handle/managers.go
  svc-api/handle/managers_test.go
  svc-api/handle/role.go
  svc-api/handle/role_test.go
  svc-api/handle/sessions.go
  svc-api/handle/sessions_test.go
  svc-api/handle/systems.go
  svc-api/handle/systems_test.go
  svc-api/handle/task.go
  svc-api/handle/task_test.go
  svc-api/handle/telemetry.go
  svc-api/handle/telemetry_test.go
  svc-api/handle/update.go
  svc-api/handle/update_test.go
  svc-api/main.go
  svc-api/middleware/middleware.go
  svc-api/models/registries.go
  svc-api/ratelimiter/ratelimiter.go
  svc-api/router/router.go
  svc-api/rpc/account.go
  svc-api/rpc/account_test.go
  svc-api/rpc/aggregator.go
  svc-api/rpc/aggregator_test.go
  svc-api/rpc/chassis.go
  svc-api/rpc/chassis_test.go
  svc-api/rpc/events.go
  svc-api/rpc/events_test.go
  svc-api/rpc/fabrics.go
  svc-api/rpc/fabrics_test.go
  svc-api/rpc/licenses.go
  svc-api/rpc/managers.go
  svc-api/rpc/managers_test.go
  svc-api/rpc/role.go
  svc-api/rpc/role_test.go
  svc-api/rpc/sessions.go
  svc-api/rpc/sessions_test.go
  svc-api/rpc/system.go
  svc-api/rpc/system_test.go
  svc-api/rpc/task.go
  svc-api/rpc/task_test.go
  svc-api/rpc/telemetry.go
  svc-api/rpc/telemetry_test.go
  svc-api/rpc/update.go
  svc-api/rpc/update_test.go
Labels: type:feature, prio:normal, status:in-progress

#1047 Add information about containerd engine + K8S image versions updates
  README.md
  docs/images/kubernetes_images.png
  docs/images/odim_cluster.png
Labels: prio:normal, status:in-progress, type:doc

#1037 Remove adding default subscription for each server and OriginResource from subscription
  build/Redis/createschema.sh
  install/Docker/dockerfiles/scripts/redis-createschema.sh
  svc-aggregation/system/rediscoverinventory_test.go
  svc-events/evcommon/common_test.go
  svc-events/events/common.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/evmodel/events.go
  svc-systems/chassis/delete_test.go
Labels: type:techdebt, prio:normal, status:in-progress

#1048 Resolve the vulnerabilities found in github code scanning
  lib-utilities/config/constants.go
  lib-utilities/logs/logging.go
  odim-controller/scripts/odim-controller.py
Labels: type:techdebt, prio:normal, status:in-progress

#1049 ODIM-6721 - Implement a job queue for tasks to perform redis DB operations
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  lib-persistence-manager/persistencemgr/unit_test_db_confighelp.go
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/mockconfig.go
  lib-utilities/config/odimra_config.json
  lib-utilities/errors/constants.go
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  svc-task/main.go
  svc-task/thandle/thandle.go
  svc-task/thandle/thandle_test.go
  svc-task/tmessagebus/publish.go
  svc-task/tmodel/tmodel.go
  svc-task/tmodel/tmodel_test.go
  svc-task/tqueue/queue.go
  svc-task/tqueue/queue_test.go
Labels: type:feature, prio:normal, status:in-progress

#1054 Add process logs for svc-managers
  lib-utilities/common/constants.go
  svc-managers/managers/common.go
  svc-managers/managers/common_test.go
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrcommon/common.go
  svc-managers/mgrcommon/common_test.go
  svc-managers/rpc/manager.go
  svc-managers/rpc/manager_test.go
Labels: type:feature, prio:normal, status:in-progress

#1055 Add process logs for svc-account-session
  lib-utilities/common/constants.go
  lib-utilities/common/responses.go
  svc-account-session/account/create.go
  svc-account-session/account/create_test.go
  svc-account-session/account/delete.go
  svc-account-session/account/delete_test.go
  svc-account-session/account/getaccounts.go
  svc-account-session/account/getaccounts_test.go
  svc-account-session/account/update.go
  svc-account-session/account/update_test.go
  svc-account-session/auth/auth.go
  svc-account-session/auth/auth_test.go
  svc-account-session/auth/session.go
  svc-account-session/auth/session_test.go
  svc-account-session/role/checkprivilege.go
  svc-account-session/role/create.go
  svc-account-session/role/create_test.go
  svc-account-session/role/delete.go
  svc-account-session/role/delete_test.go
  svc-account-session/role/getroles.go
  svc-account-session/role/getroles_test.go
  svc-account-session/role/update.go
  svc-account-session/role/update_test.go
  svc-account-session/rpc/account.go
  svc-account-session/rpc/account_test.go
  svc-account-session/rpc/auth.go
  svc-account-session/rpc/auth_test.go
  svc-account-session/rpc/role.go
  svc-account-session/rpc/role_test.go
  svc-account-session/rpc/sessions.go
  svc-account-session/rpc/sessions_test.go
  svc-account-session/session/create.go
  svc-account-session/session/create_test.go
  svc-account-session/session/delete.go
  svc-account-session/session/delete_test.go
  svc-account-session/session/getsession.go
  svc-account-session/session/getsession_test.go
  svc-account-session/session/update.go
  svc-account-session/session/update_test.go
  svc-api/rpc/account.go
  svc-api/rpc/aggregator.go
  svc-api/rpc/chassis.go
  svc-api/rpc/events.go
  svc-api/rpc/fabrics.go
  svc-api/rpc/licenses.go
  svc-api/rpc/managers.go
  svc-api/rpc/role.go
  svc-api/rpc/sessions.go
  svc-api/rpc/system.go
  svc-api/rpc/system_test.go
  svc-api/rpc/task.go
  svc-api/rpc/telemetry.go
  svc-api/rpc/update.go
  svc-systems/rpc/systems_test.go
Labels: type:feature, prio:normal, status:in-progress

#1056 Increase UT coverage for svc-aggregation
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
Labels: type:bug, prio:normal, status:in-progress

#1058 Backup and restore of kubernetes etcd and odim etcd sections
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1057 As an ODIM user I want support both syslog and json format
  lib-utilities/config/config.go
  lib-utilities/logs/logger.go
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-config/values.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  odim-controller/scripts/odim-controller.py
  svc-account-session/account/common.go
  svc-account-session/main.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/main.go
  svc-api/apicommon/common.go
  svc-api/main.go
  svc-events/evcommon/common.go
  svc-events/main.go
  svc-fabrics/fabrics/common.go
  svc-fabrics/main.go
  svc-licenses/lcommon/common.go
  svc-licenses/main.go
  svc-managers/main.go
  svc-managers/mgrcommon/common.go
  svc-systems/main.go
  svc-systems/scommon/common.go
  svc-task/main.go
  svc-task/tcommon/common.go
  svc-telemetry/main.go
  svc-telemetry/tcommon/common.go
  svc-update/main.go
  svc-update/ucommon/common.go
Labels: type:feature, prio:normal, status:in-progress

#1053 Adding the new config "OdimControlMessageQueue" to the odimra_config helm chart
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
Labels: type:bug, prio:high, prio:normal

#1059 New section "Application logs"
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc
