Repository ODIM-Project/ODIM, pull requests merged in 2022-04, with the labels that each got.

#848 odim-5732: Add pointer to the bool parameter
  lib-dmtf/model/storage.go
Labels: type:bug

#849 Odim 5734:Event subcription changes
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/evresponse/events.go
  svc-events/evresponse/events_test.go
Labels: type:bug, prio:high, status:in-progress

#850 odim 5739:3node dual stack configuration fix
  odim-controller/helmcharts/api/templates/service.yaml
  odim-controller/odimra/roles/configure-keepalived/tasks/main.yaml
  odim-controller/odimra/roles/configure-keepalived/templates/keepalived.conf.j2
  odim-controller/odimra/roles/configure-proxy/tasks/main.yaml
  odim-controller/odimra/roles/configure-proxy/templates/api_proxy_server.conf.j2
  odim-controller/odimra/roles/update-proxy-conf/tasks/main.yaml
  odim-controller/scripts/odim-controller.py
Labels: type:bug, prio:normal, status:in-progress

#852 updated the changes for composition_service
  svc-composition-service/app/db/persistant.py
  svc-composition-service/app/rest/composition_service.py
  svc-composition-service/app/rest/pool.py
  svc-composition-service/app/rest/resource_blocks.py
  svc-composition-service/app/rest/resource_zones.py
  svc-composition-service/app/utilities/auth.py
  svc-composition-service/app/utilities/client.py
  svc-composition-service/app/utilities/client_service.py
  svc-composition-service/app/utilities/crypt.py
Labels: type:bug, prio:normal, status:in-progress

#853 ODIM-85 Redis connection pool fix under rate limiting
  lib-persistence-manager/persistencemgr/redis.go
Labels: type:bug, prio:high, status:in-progress

#856 Update requirements.txt
  svc-composition-service/requirements.txt
Labels: type:bug, prio:high, status:in-progress

#854 Bruce2484:Tech Debt: Check the error responses sent in ODIM are as per redfish spec.- Managers,Systems
  svc-api/go.mod
  svc-api/go.sum
  svc-api/router/router.go
Labels: type:bug, prio:normal, status:in-progress

#858 ODIM-5563 Event Service cleanup and fixing panic issues
  svc-events/evcommon/common.go
  svc-events/events/common.go
  svc-events/events/deletesubscription.go
  svc-events/events/evtsubscription.go
  svc-events/events/getevtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/submittestevent.go
  svc-events/evresponse/events.go
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
Labels: type:bug, prio:normal, status:in-progress

#857 odim-4557: Upgrade kafka, zookeeper and kafka-segmentio version to latest
  build/Kafka/Dockerfiles/Dockerfile.kafka
  build/Kafka/Dockerfiles/Dockerfile.zookeeper
  build/docker-compose.yml
  build_images.sh
  docker-images.sh
  install/Docker/dockerfiles/Dockerfile.kafka
  install/Docker/dockerfiles/Dockerfile.zookeeper
  lib-messagebus/go.mod
  lib-messagebus/go.sum
  odim-controller/helmcharts/kafka-ha/Chart.yaml
  odim-controller/helmcharts/kafka-ha/values.yaml
  odim-controller/helmcharts/kafka-secret/Chart.yaml
  odim-controller/helmcharts/kafka/Chart.yaml
  odim-controller/helmcharts/kafka/templates/_helpers.tpl
  odim-controller/helmcharts/kafka/values.yaml
  odim-controller/helmcharts/zookeeper-ha/Chart.yaml
  odim-controller/helmcharts/zookeeper-ha/values.yaml
  odim-controller/helmcharts/zookeeper-secret/Chart.yaml
  odim-controller/helmcharts/zookeeper/Chart.yaml
  odim-controller/helmcharts/zookeeper/templates/_helpers.tpl
  odim-controller/helmcharts/zookeeper/values.yaml
  odim-controller/odimra/group_vars/all/all.yaml
  plugin-dell/go.mod
  plugin-dell/go.sum
  plugin-lenovo/go.mod
  plugin-lenovo/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-task/go.mod
  svc-task/go.sum
Labels: type:feature, prio:normal, status:in-progress

#859 ODIM-5729 Testcases for svc-api and svc-account-session
  svc-account-session/asmodel/account.go
  svc-account-session/asmodel/account_test.go
  svc-account-session/asmodel/privilege.go
  svc-account-session/asmodel/privilege_test.go
  svc-account-session/asmodel/redfishroles.go
  svc-account-session/asmodel/redfishroles_test.go
  svc-account-session/asmodel/sessions.go
  svc-account-session/asmodel/sessions_test.go
  svc-account-session/asmodel/userRole.go
  svc-account-session/asmodel/userRole_test.go
  svc-account-session/rpc/account.go
  svc-account-session/rpc/account_test.go
  svc-account-session/rpc/auth.go
  svc-account-session/rpc/auth_test.go
  svc-account-session/rpc/role.go
  svc-account-session/rpc/role_test.go
  svc-account-session/rpc/sessions.go
  svc-account-session/rpc/sessions_test.go
  svc-api/rpc/account.go
  svc-api/rpc/account_test.go
  svc-api/rpc/aggregator.go
  svc-api/rpc/aggregator_test.go
  svc-api/rpc/chassis.go
  svc-api/rpc/chassis_test.go
  svc-api/rpc/events.go
  svc-api/rpc/events_test.go
  svc-api/rpc/fabrics.go
  svc-api/rpc/fabrics_test.go
  svc-api/rpc/fakeStruct_testfile.go
  svc-api/rpc/managers.go
  svc-api/rpc/managers_test.go
  svc-api/rpc/role.go
  svc-api/rpc/role_test.go
  svc-api/rpc/sessions.go
  svc-api/rpc/sessions_test.go
  svc-api/rpc/system.go
  svc-api/rpc/system_test.go
  svc-api/rpc/task.go
  svc-api/rpc/task_test.go
  svc-api/rpc/telemetry.go
  svc-api/rpc/telemetry_test.go
  svc-api/rpc/update.go
  svc-api/rpc/update_test.go
Labels: type:techdebt, prio:normal, status:in-progress

#860 ODIM-5797: Upgrade redis from version 6.2.5 to 6.2.6
  .github/workflows/build_unittest.yml
  build/Redis/Dockerfile.redis
  install/Docker/dockerfiles/Dockerfile.redis
  odim-controller/helmcharts/redis-ha/Chart.yaml
  odim-controller/helmcharts/redis/Chart.yaml
  odim-controller/helmcharts/redis/templates/_helpers.tpl
  odim-controller/odimra/group_vars/all/all.yaml
Labels: type:feature, prio:normal, status:in-progress
