Repository ODIM-Project/ODIM, pull requests merged in 2022-10, with the labels that each got.

#1025 Made fixes to avoid panic while deleting aggregate
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
Labels: type:bug, prio:low, status:in-progress

#1028 odim-6689: Disable composition service deployment
  .github/workflows/build_unittest.yml
  build_images.sh
  docker-images.sh
  odim-controller/helmcharts/create_helm_packages.sh
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/odimra/group_vars/all/all.yaml
  svc-api/router/router.go
Labels: type:feature, prio:normal, status:in-progress

#1029 Update logLevel priority using odimra-configmap
  lib-utilities/logs/logger.go
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  odim-controller/scripts/odim-controller.py
  svc-account-session/account/common.go
  svc-account-session/main.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/system/pluginHealthCheck_test.go
  svc-api/apicommon/common.go
  svc-api/main.go
  svc-events/evcommon/common.go
  svc-events/main.go
  svc-fabrics/fabrics/common.go
  svc-fabrics/main.go
  svc-licenses/lcommon/common.go
  svc-licenses/main.go
  svc-managers/mgrcommon/common.go
  svc-systems/scommon/common.go
  svc-task/main.go
  svc-task/tcommon/common.go
  svc-telemetry/main.go
  svc-telemetry/tcommon/common.go
  svc-update/main.go
  svc-update/ucommon/common.go
Labels: type:bug, prio:normal, status:in-progress
