Repository ODIM-Project/ODIM, pull requests merged in 2022-02, with the labels that each got.

#747 ODIM-80 For created Collection subscription Events from underlying server not getting delivered to the destination
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/evresponse/events.go
Labels: type:bug, prio:high, status:in-progress

#748 odim 76:Adding the changes to check kafka configuration in lib-message bus
  lib-messagebus/datacommunicator/config.go
  lib-messagebus/datacommunicator/kafkacomm.go
  lib-messagebus/datacommunicator/redisstreamcomm.go
  odim-controller/helmcharts/odimra-platformconfig/templates/configmaps.yaml
  svc-events/consumer/consumer_test.go
  svc-events/evcommon/common_test.go
  svc-events/evresponse/events.go
Labels: type:techdebt, prio:normal, status:in-progress

#750 Security Logging section - Merge to Dev
  docs/README.md
Labels: type:doc

#755 ODIM-81 ODIM created events are missing EventTimestamp, Message and Severity parameters
  svc-aggregation/agmessagebus/publish.go
  svc-task/thandle/thandle.go
  svc-task/thandle/thandle_test.go
  svc-task/tmessagebus/publish.go
  svc-task/tresponse/task.go
Labels: type:bug, prio:normal, status:in-progress

#756 odim 76:Replacing the writer lock with readlock in Kafka Accept
  lib-messagebus/datacommunicator/kafkacomm.go
Labels: type:bug, prio:high, status:in-progress

#752 Troubleshooting information for error during K8S deployment - Merge to Dev
  docs/Troubleshooting.md
Labels: type:doc

#751 Removed RedisStream instances for Redfish - Merge to Dev
  plugin-redfish/README.md
Labels: type:doc

#753 Audit Logging - Merge to Dev
  docs/README.md
Labels: type:doc

#754 EMB parameters in kube yaml file - Merge to Dev
  README.md
Labels: type:doc

#759 ODIM-5533: Fixed Odimra service manager empty @odata.id in the Certificates property
  svc-managers/mgrmodel/manager.go
Labels: type:bug

#761 ODIM-81 Fix publishing duplicate events to destination
  svc-events/events/publishevttosubscriber.go
Labels: type:bug, prio:normal, status:in-progress

#762 Odim-5453: Add ManagerForChassis and ManagerForServer details under manager ID
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addcompute_test.go
  svc-managers/managers/managers.go
  svc-managers/mgrmodel/manager.go
Labels: prio:normal, status:in-progress

#763 Odim-5501: Delete ManagerForServer and ManagerForChassis property under Links for manager id when server is deleted
  svc-aggregation/system/deleteaggregationsource.go
Labels: prio:normal, status:in-progress

#764 Odim-5454: Add & delete ManagerForChassis for URP plugin
  svc-systems/chassis/create.go
  svc-systems/chassis/delete.go
  svc-systems/smodel/systems.go
Labels: prio:normal, status:in-progress

#766 Merge to Dev - Replace existing IPs with public IPs throughout the document + replace missed colons with a period
  docs/README.md
Labels: type:doc

#767 Merge to Dev - Add a missed step, in Dell and GRF plugins deployment instructions
  README.md
Labels: type:doc

#771 Merge to Dev - Update all third-party component versions and related screens
  README.md
  docs/images/all_services_verification.png
  docs/images/kuberenetes_pods_verification.png
  docs/images/kubernetes_images.png
  docs/images/odimra_images.png
Labels: type:doc

#768 Merge to Dev- Mandate haDeploymentEnabled parameter to true for 3-node cluster deployments #35
  README.md
Labels: type:doc

#765 Updated cipher suites across ODIMRA and all plugins
  lib-utilities/config/constants.go
  lib-utilities/config/httpConfig_test.go
  lib-utilities/config/mockconfig.go
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/configmaps.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/helmcharts/urplugin/urplugin/templates/configmaps.yaml
  odim-controller/odimra/roles/configure-proxy/templates/nginx.conf.j2
  odim-controller/scripts/odim-controller.py
  plugin-dell/config/dell_config.json
  plugin-dell/config/mockconfig.go
  plugin-lenovo/config/lenovo_config.json
  plugin-lenovo/config/mockconfig.go
  plugin-redfish/config/config.json
  plugin-redfish/config/mockconfig.go
Labels: type:techdebt, prio:normal, status:in-progress

#769 Merge to Dev - Lenovo deployment instructions
  README.md
Labels: type:doc

#773 Merge to Dev - Update response for GET on plugin managers
  docs/README.md
Labels: type:doc

#774 Updated the security log for URI with no auth
  lib-utilities/common/constants.go
  svc-api/router/router.go
Labels: type:bug, prio:normal, status:in-progress

#775 Odim 5510:Manager resource to be updated as per comments from OCP profile validation
  svc-aggregation/system/addplugin.go
  svc-managers/main.go
  svc-managers/managers/common_test.go
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrcommon/common.go
  svc-managers/mgrmodel/manager.go
Labels: prio:normal, status:in-progress

#778 odim-5557: fix for even pod distribution on 3-node cluster
  odim-controller/helmcharts/account-session/templates/deployment.yaml
  odim-controller/helmcharts/aggregation/templates/deployment.yaml
  odim-controller/helmcharts/api/templates/deployment.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/deployment.yaml
  odim-controller/helmcharts/events/templates/deployment.yaml
  odim-controller/helmcharts/fabrics/templates/deployment.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/deployment.yaml
  odim-controller/helmcharts/managers/templates/deployment.yaml
  odim-controller/helmcharts/systems/templates/deployment.yaml
  odim-controller/helmcharts/task/templates/deployment.yaml
  odim-controller/helmcharts/telemetry/templates/deployment.yaml
  odim-controller/helmcharts/update/templates/deployment.yaml
  odim-controller/helmcharts/urplugin/urplugin/templates/deployment.yaml
Labels: type:bug

#781 ODIM-81 Event Pod is in CrashLoopBackOff after adding the ACI fabric
  plugin-redfish/rfpmessagebus/publish.go
  svc-events/events/publishevttosubscriber.go
Labels: type:bug, prio:normal, status:in-progress

#777 Odim 82:Updating SerialInterface Route
  lib-utilities/common/constants.go
  plugin-lenovo/main.go
  plugin-redfish/main.go
  svc-api/router/router.go
Labels: type:bug, prio:normal, status:in-progress

#782 Docker image and helm chart tag update
  build_images.sh
  docker-images.sh
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.dellplugin
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.lenovoplugin
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.telemetry
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/Dockerfile.urplugin
  odim-controller/helmcharts/account-session/Chart.yaml
  odim-controller/helmcharts/account-session/values.yaml
  odim-controller/helmcharts/aggregation/Chart.yaml
  odim-controller/helmcharts/aggregation/values.yaml
  odim-controller/helmcharts/api/Chart.yaml
  odim-controller/helmcharts/api/values.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/Chart.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/values.yaml
  odim-controller/helmcharts/events/Chart.yaml
  odim-controller/helmcharts/events/values.yaml
  odim-controller/helmcharts/fabrics/Chart.yaml
  odim-controller/helmcharts/fabrics/values.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/Chart.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/values.yaml
  odim-controller/helmcharts/managers/Chart.yaml
  odim-controller/helmcharts/managers/values.yaml
  odim-controller/helmcharts/systems/Chart.yaml
  odim-controller/helmcharts/systems/values.yaml
  odim-controller/helmcharts/task/Chart.yaml
  odim-controller/helmcharts/task/values.yaml
  odim-controller/helmcharts/telemetry/Chart.yaml
  odim-controller/helmcharts/telemetry/values.yaml
  odim-controller/helmcharts/update/Chart.yaml
  odim-controller/helmcharts/update/values.yaml
  odim-controller/helmcharts/urplugin/urplugin/Chart.yaml
  odim-controller/helmcharts/urplugin/urplugin/values.yaml
  odim-controller/odimra/group_vars/all/all.yaml
Labels: prio:high, type:feature, status:in-progress

#779 Merge to Dev - Common response headers updated
  docs/README.md
Labels: type:doc

#787 ODIM-5566: Empty "Id" property removed
  lib-utilities/response/response.go
Labels: type:bug

#784 ODIM-71 Fix volume creation and deletion unit tests
  svc-systems/rpc/systems_test.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: type:bug, prio:normal, status:in-progress

#783 ODIM 5511: Sub task resource updated as per comments from OCP profile validation
  svc-task/thandle/thandle.go
  svc-task/thandle/tmonitor.go
  svc-task/tresponse/task.go
Labels: type:bug

#786 odim 5509:Updating the chassis and power model
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/power.go
Labels: type:bug, prio:normal, status:in-progress

#790 Omit certificates property if its null in chassis schema
  lib-dmtf/model/Chassis.go
Labels: type:bug, prio:normal, status:in-progress

#791 Merge to dev - Rename Docker images of all the Kubernetes microservices
  README.md
Labels: type:doc

#795 ODIM-5569 Add network adapter dmtf model
  lib-dmtf/model/networkadapter.go
Labels: type:bug, prio:normal, status:in-progress

#792 ODIM-5564: TaskService Resource version updated from 1.1.4 to 1.2.0
  svc-task/thandle/thandle.go
Labels: type:bug, prio:normal, status:in-progress

#794 Odim 5522: Manager resource to be updated as per comments from OCP profile validation
  svc-managers/main.go
  svc-managers/managers/managers.go
  svc-managers/mgrmodel/manager.go
Labels: prio:normal, status:in-progress

#798 RC branch sync with upstream development
  README.md
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/networkadapter.go
  lib-dmtf/model/power.go
  lib-utilities/response/response.go
  svc-account-session/asresponse/role.go
  svc-api/handle/role.go
  svc-managers/main.go
  svc-managers/managers/managers.go
  svc-managers/mgrmodel/manager.go
  svc-systems/rpc/systems_test.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
  svc-task/thandle/thandle.go
  svc-task/thandle/tmonitor.go
  svc-task/tresponse/task.go
  svc-update/update/getresources.go
Labels: prio:high, type:feature, status:in-progress

#799 ODIM-5569 update Action as interface{} in network adapter model
  lib-dmtf/model/networkadapter.go
Labels: type:bug, prio:normal, status:in-progress

#802 Merge to Release branch - Contribution to open-source community
  README.md
  lib-dmtf/model/networkadapter.go
Labels: type:doc

#800 Merge to Dev - Contribution to open-source community
  README.md
Labels: type:doc

#801 Merge to Dev - Update Scaling up and scaling down resources section
  README.md
Labels: type:doc

#796 odim-5454: Add ManagerForChassis ManagerForServer and ManagersForManager links under odim manager
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrmodel/manager.go
Labels: prio:normal, status:in-progress

#804 ODIM-5269 Add oem block and Description in network adapter model
  lib-dmtf/model/networkadapter.go
Labels: type:bug, prio:normal, status:in-progress

#807 Merge to Release branch - Update sample responses for managers
  docs/README.md
Labels: type:doc

#805 Adding the support for BMC account and roles operations under Managers
  lib-dmtf/model/accountService.go
  lib-utilities/proto/managers/managers.proto
  svc-api/handle/managers.go
  svc-api/handle/managers_test.go
  svc-api/handle/role.go
  svc-api/router/router.go
  svc-api/rpc/managers.go
  svc-managers/managers/common_test.go
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrmodel/manager.go
  svc-managers/rpc/manager.go
  svc-managers/rpc/manager_test.go
Labels: prio:high, type:feature, status:in-progress

#806 Merge to Dev - Update sample responses for managers
  docs/README.md
Labels: type:doc

#811 Merge to release - Sample responses updated + adding "generating and importing certs section before adding server section"
  docs/README.md
Labels: type:doc

#812 Merge to release branch - Overall Team's feedback PR
  README.md
Labels: type:doc
