Repository ODIM-Project/ODIM, pull requests merged in 2022-09, with the labels that each got.

#1008 Merge to dev branch - plugin deployment instructions, API responses and other fixes updated
  README.md
  docs/README.md
  docs/images/odimra_images.png
Labels: prio:normal, status:in-progress, type:doc

#1007 Allow aggregate source uri in AggregationService.Reset action
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/reset.go
  svc-aggregation/system/reset_test.go
Labels: prio:high, type:feature, status:in-progress

#1014 Update log priority through config file
  lib-utilities/config/config.go
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  odim-controller/scripts/odim-controller.py
  svc-account-session/main.go
  svc-aggregation/main.go
  svc-api/main.go
  svc-events/main.go
  svc-fabrics/main.go
  svc-licenses/main.go
  svc-managers/main.go
  svc-systems/main.go
  svc-task/main.go
  svc-telemetry/main.go
  svc-update/main.go
Labels: prio:high, type:techdebt, status:in-progress

#1017 Update log priority for lib
  lib-messagebus/datacommunicator/config.go
  lib-messagebus/datacommunicator/header.go
  lib-messagebus/datacommunicator/kafkacomm.go
  lib-messagebus/datacommunicator/redisstreamcomm.go
  lib-messagebus/go.mod
  lib-messagebus/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  lib-persistence-manager/persistencemgr/redis.go
  lib-rest-client/go.mod
  lib-rest-client/go.sum
  lib-rest-client/pmbhandle/rest.go
  lib-utilities/common/kubernetes.go
  lib-utilities/common/trackconfig.go
  lib-utilities/logService/common.go
  lib-utilities/logs/logging.go
  lib-utilities/services/auth.go
  lib-utilities/services/eventsubscription.go
  lib-utilities/services/rpcService.go
  lib-utilities/services/task.go
  odim-controller/scripts/odim-controller.py
  svc-api/router/router.go
Labels: prio:high, type:techdebt, status:in-progress

#1018 Updated logLevel properties in user config
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/odimra/group_vars/all/all.yaml
  odim-controller/scripts/odim-controller.py
Labels: type:bug, prio:normal, status:in-progress

#1019 Updated failing of composition service while odim upgrade
  odim-controller/scripts/odim-controller.py
Labels: type:bug

#1020 Odim 6636:Updating fixes of scale testing issues
  install/Docker/dockerfiles/Dockerfile.etcd
  install/Docker/dockerfiles/Dockerfile.kafka
  install/Docker/dockerfiles/Dockerfile.zookeeper
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  odim-controller/helmcharts/account-session/templates/deployment.yaml
  odim-controller/helmcharts/aggregation/templates/deployment.yaml
  odim-controller/helmcharts/api/templates/deployment.yaml
  odim-controller/helmcharts/etcd-ha/templates/etcd-ha-deployment.yaml
  odim-controller/helmcharts/etcd/templates/etcd-statefulset.yaml
  odim-controller/helmcharts/events/templates/deployment.yaml
  odim-controller/helmcharts/fabrics/templates/deployment.yaml
  odim-controller/helmcharts/kafka-ha/templates/kafka-ha-deployment.yaml
  odim-controller/helmcharts/kafka/templates/kafka-deployment.yaml
  odim-controller/helmcharts/licenses/templates/deployment.yaml
  odim-controller/helmcharts/managers/templates/deployment.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-secondary-statefulset.yaml
  odim-controller/helmcharts/redis/templates/redis-inmemory-statefulset.yaml
  odim-controller/helmcharts/redis/templates/redis-ondisk-statefulset.yaml
  odim-controller/helmcharts/reloader/templates/deployment.yaml
  odim-controller/helmcharts/systems/templates/deployment.yaml
  odim-controller/helmcharts/task/templates/deployment.yaml
  odim-controller/helmcharts/telemetry/templates/deployment.yaml
  odim-controller/helmcharts/update/templates/deployment.yaml
  odim-controller/helmcharts/zookeeper-ha/templates/zookeeper-ha-deployment.yaml
  odim-controller/helmcharts/zookeeper/templates/zookeeper-deployment.yaml
  odim-controller/odimra/roles/install/tasks/main.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  svc-aggregation/agmodel/system.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/common.go
  svc-aggregation/system/rediscoverinventory.go
  svc-aggregation/system/rediscoverinventory_test.go
  svc-api/handle/compositionservice.go
  svc-api/handle/handlers_test.go
  svc-api/router/router.go
  svc-api/rpc/account.go
  svc-api/rpc/aggregator.go
  svc-api/rpc/aggregator_test.go
  svc-api/rpc/chassis.go
  svc-api/rpc/chassis_test.go
  svc-api/rpc/events.go
  svc-api/rpc/fabrics.go
  svc-api/rpc/managers.go
  svc-api/rpc/role.go
  svc-api/rpc/role_test.go
  svc-api/rpc/sessions.go
  svc-api/rpc/task.go
  svc-api/rpc/telemetry.go
  svc-api/rpc/update.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/evresponse/events.go
  svc-task/thandle/thandle.go
Labels: type:bug, prio:high, status:in-progress

#1021 Updated UT coverage for fabric service
  svc-fabrics/fabmodel/fabrics.go
  svc-fabrics/fabmodel/fabrics_test.go
  svc-fabrics/fabrics/addfabric.go
  svc-fabrics/fabrics/addfabric_test.go
  svc-fabrics/fabrics/common.go
  svc-fabrics/fabrics/common_test.go
  svc-fabrics/rpc/fabrics_test.go
Labels: type:techdebt, prio:normal, status:in-progress

#1023 odim-6666: Add omitempty to collectionCapabilities field
  lib-dmtf/model/storage.go
Labels: type:bug, prio:normal, status:in-progress

#1022 Update power state sync with the BMC
  lib-dmtf/model/Chassis.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/system/aggregate.go
  svc-managers/managers/managers.go
  svc-systems/chassis/get.go
  svc-systems/chassis/get_test.go
  svc-systems/rpc/chassis.go
  svc-systems/rpc/systems.go
  svc-systems/systems/getresource.go
  svc-systems/systems/getresource_test.go
Labels: type:techdebt, prio:normal, status:in-progress

#1024 Odim-6685: Fixed ODIM deployment failing issue due to the missing helm configurations
  .github/workflows/odimra_deployment.yml
  lib-utilities/config/config.go
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-config/values.yaml
  odim-controller/scripts/odim-controller.py
Labels: type:bug, prio:normal, status:in-progress
