Repository ODIM-Project/ODIM, pull requests merged in 2022-08, with the labels that each got.

#966 Update string separators while add and remove aggregate elements
  svc-aggregation/agmodel/system.go
Labels: type:bug, prio:high, status:in-progress

#968 Update image tag for odimra services and plugins
  build_images.sh
  docker-images.sh
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.compositionService
  install/Docker/dockerfiles/Dockerfile.dellplugin
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.lenovoplugin
  install/Docker/dockerfiles/Dockerfile.licenses
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.telemetry
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/Dockerfile.urplugin
  odim-controller/helmcharts/account-session/Chart.yaml
  odim-controller/helmcharts/account-session/values.yaml
  odim-controller/helmcharts/aggregation/Chart.yaml
  odim-controller/helmcharts/aggregation/values.yaml
  odim-controller/helmcharts/api/Chart.yaml
  odim-controller/helmcharts/api/values.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/Chart.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/values.yaml
  odim-controller/helmcharts/events/Chart.yaml
  odim-controller/helmcharts/events/values.yaml
  odim-controller/helmcharts/fabrics/Chart.yaml
  odim-controller/helmcharts/fabrics/values.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/Chart.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/values.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/Chart.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/values.yaml
  odim-controller/helmcharts/managers/Chart.yaml
  odim-controller/helmcharts/managers/values.yaml
  odim-controller/helmcharts/redis-ha/Chart.yaml
  odim-controller/helmcharts/redis-ha/values.yaml
  odim-controller/helmcharts/redis/Chart.yaml
  odim-controller/helmcharts/redis/values.yaml
  odim-controller/helmcharts/systems/Chart.yaml
  odim-controller/helmcharts/systems/values.yaml
  odim-controller/helmcharts/task/Chart.yaml
  odim-controller/helmcharts/task/values.yaml
  odim-controller/helmcharts/telemetry/Chart.yaml
  odim-controller/helmcharts/telemetry/values.yaml
  odim-controller/helmcharts/update/Chart.yaml
  odim-controller/helmcharts/update/values.yaml
  odim-controller/helmcharts/urplugin/urplugin/Chart.yaml
  odim-controller/helmcharts/urplugin/urplugin/values.yaml
  odim-controller/odimra/group_vars/all/all.yaml
  svc-api/go.mod
  svc-api/go.sum
  svc-task/go.mod
  svc-task/go.sum
Labels: prio:high, type:feature, status:in-progress

#967 Odim-5938:changed the SetDefaultBootOrderActionInfo parameters type from Array to Object Array
  svc-aggregation/rpc/aggregator.go
Labels: type:bug, prio:normal, status:in-progress

#970 odim 5985:Updating the task index check while deleting task
  svc-task/main.go
  svc-task/thandle/thandle.go
  svc-task/thandle/thandle_test.go
Labels: type:bug, prio:high, status:in-progress

#969 Odim 6282 - As an ODIM user I want aggregates to remove system if the system is deleted from ODIM
  svc-aggregation/agmodel/system.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
Labels: type:bug

#971 Merge to dev - Updated image versions of odim and k8s services
  README.md
  docs/images/kubernetes_images.png
  docs/images/odimra_images.png
Labels: prio:normal, status:in-progress, type:doc

#976 Merge to dev - Update third party software versions
  README.md
Labels: prio:normal, status:in-progress, type:doc

#974 Odim-6313:changed Licenses url into LicenseService
  lib-utilities/config/odimra_config.json
  lib-utilities/services/rpcService.go
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  svc-api/handle/handlers.go
Labels: type:bug, prio:normal, status:in-progress

#975 Subscription to be removed when an aggregate is removed
  lib-persistence-manager/persistencemgr/redis.go
  lib-utilities/proto/events/events.proto
  svc-aggregation/agcommon/common.go
  svc-aggregation/agcommon/common_test.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/aggregate_test.go
  svc-api/rpc/fakeStruct_testfile.go
  svc-events/events/deletesubscription.go
  svc-events/events/evtsubscription.go
  svc-events/events/getevtsubscription.go
  svc-events/rpc/events.go
Labels: prio:high, type:feature, status:in-progress

#972 BRUCE-6422 - OCP Interop Validator - fail.MinVersion on EthernetInterfaces from Managers
  lib-utilities/common/constants.go
  svc-managers/managers/managers.go
Labels: type:bug, prio:normal, status:in-progress

#977 Odim 6308:Adding logic to verfiy the code name of use the same while installing docker
  odim-controller/odimra/roles/k8-copy-image/tasks/main.yaml
Labels: type:bug, prio:normal, status:in-progress

#980 odim-6468: Change DataType value for ResetActionInfo response
  svc-aggregation/rpc/aggregator.go
Labels: type:bug

#978 Odim 6411:As an ODIM user I want the responses to be as per redfish spec for license service
  svc-licenses/licenses/licenses.go
Labels: type:bug, prio:normal, status:in-progress

#983 Odim 6484:Fixing the protoc compiler clone to specific version
  install/Docker/dockerfiles/Dockerfile.odim
Labels: type:bug, prio:high, status:in-progress

#979 ODIM-6390 - Remove lib-utilities dependency from lib-messagebus
  lib-messagebus/datacommunicator/config.go
  lib-messagebus/datacommunicator/redisstreamcomm.go
  lib-messagebus/platforms/platformconfig.toml
  odim-controller/helmcharts/odimra-platformconfig/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-platformconfig/values.yaml
Labels: type:bug, prio:normal, status:in-progress

#981 Sprint-58-odim-5943: Added new routes for PCIeFunctions
  lib-dmtf/model/ComputerSystem.go
  plugin-redfish/main.go
  svc-api/handle/handlers.go
  svc-api/handle/handlers_test.go
  svc-api/router/router.go
Labels: type:bug, prio:normal, status:in-progress

#985 Merge to dev - IPV6 events
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#984 ODIM-5433 - Plugin is not able to be added as aggregation source again once the plugin removed and redeployed again
  svc-aggregation/system/deleteaggregationsource.go
Labels: type:bug, prio:normal, status:in-progress

#986 Merge to dev - API readme overall updates
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#987 Team feedback on eventservice
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#988 Merge to dev - GS Readme overall doc feedback
  README.md
  docs/images/kubernetes_images.png
Labels: prio:normal, status:in-progress, type:doc

#989 BRUCE_6292 - As a customer I want centralized logging framework for ODIM
  lib-utilities/logs/formatter.go
  lib-utilities/logs/logger.go
Labels: type:feature, prio:normal, status:in-progress

#990 Merge to dev - Final feedback for svc and plugin readmes
  plugin-dell/README.md
  plugin-lenovo/README.md
  plugin-redfish/README.md
  plugin-unmanaged-racks/README.md
  svc-managers/README.md
  svc-systems/README.md
Labels: prio:normal, status:in-progress, type:doc

#991 Handle IPv6 adderess for event forwording
  svc-aggregation/system/addcompute.go
  svc-events/events/publishevttosubscriber.go
Labels: type:bug, prio:low, status:in-progress

#992 Odim 6412: As an ODIM user I want the responses to be as per redfish spec for telemetry service
  svc-api/handle/handlers.go
  svc-api/router/router.go
Labels: type:bug, prio:normal, status:in-progress

#993 Added New properties on create volume
  lib-dmtf/model/Links.go
  svc-systems/smodel/systems.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: type:techdebt, prio:normal, status:in-progress

#995 ODIM-6498:Updated schema
  lib-utilities/common/constants.go
Labels: type:bug, prio:low, status:in-progress

#994 BRUCE-6520 - grf plugin deployment is failing with because of db connect issue
  odim-controller/helmcharts/dellplugin/dellplugin/templates/deployment.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/deployment.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/deployment.yaml
  odim-controller/helmcharts/odimra-platformconfig/templates/configmaps.yaml
Labels: type:bug, prio:normal, status:in-progress

#996 odim-6514: Made struct changes to resolve error while installing license using aggregate
  svc-licenses/licenses/common_test.go
  svc-licenses/licenses/licenses.go
  svc-licenses/model/licenses.go
Labels: type:bug

#997 BRUCE-6495 - ERROR - Licenses not defined in schema ServiceRoot.v1_14_0
  svc-api/handle/handlers.go
  svc-api/models/serviceroot.go
Labels: type:bug, prio:normal, status:in-progress

#998 odim-6497: Add omitempty for odatatype in storage controller struct
  lib-dmtf/model/storage.go
Labels: type:bug

#999 odim-6496: Modify datatype for location under Port struct
  lib-dmtf/model/port.go
Labels: type:bug

#1000 Add schema for storage controller in handler
  svc-api/handle/handlers.go
Labels: type:bug

#1001 Merge to Release branch - Team's feedback on APIs
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1002 Merge to Release branch - Fixed formatting of codeblock and paragraph text in GS readme
  README.md
  docs/images/odimra_images.png
Labels: prio:normal, status:in-progress, type:doc

#1003 Merge to Release Branch - Fixed formatting issues in API readme
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1005 Merge to Release branch - plugin deployment instructions updated
  README.md
Labels: prio:normal, status:in-progress, type:doc
