Repository ODIM-Project/ODIM, pull requests merged in 2022-06, with the labels that each got.

#890 Add mandatory parameter checks add/delete plugin
  odim-controller/odimra/roles/remove-plugin/tasks/main.yaml
  odim-controller/scripts/odim-controller.py
Labels: type:feature, prio:normal, status:in-progress

#892 Updating dockerfile for reducing build time for odimra images
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.compositionService
  install/Docker/dockerfiles/Dockerfile.dellplugin
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.lenovoplugin
  install/Docker/dockerfiles/Dockerfile.licenses
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.odim
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.telemetry
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/Dockerfile.urplugin
  install/Docker/dockerfiles/build/accountSession.sh
  install/Docker/dockerfiles/build/aggregation.sh
  install/Docker/dockerfiles/build/api.sh
  install/Docker/dockerfiles/build/dellplugin.sh
  install/Docker/dockerfiles/build/events.sh
  install/Docker/dockerfiles/build/fabrics.sh
  install/Docker/dockerfiles/build/grfplugin.sh
  install/Docker/dockerfiles/build/lenovoplugin.sh
  install/Docker/dockerfiles/build/licenses.sh
  install/Docker/dockerfiles/build/managers.sh
  install/Docker/dockerfiles/build/systems.sh
  install/Docker/dockerfiles/build/task.sh
  install/Docker/dockerfiles/build/telemetry.sh
  install/Docker/dockerfiles/build/update.sh
  install/Docker/dockerfiles/build/urplugin.sh
  install/Docker/dockerfiles/scripts/build_cs.sh
  install/Docker/dockerfiles/scripts/fetch_odim_pkgs.sh
Labels: type:feature, prio:normal, status:in-progress

#894 odim 5930:Unit test coverage for agcommon under svc-aggregation
  svc-aggregation/agcommon/common.go
  svc-aggregation/agcommon/common_test.go
Labels: type:feature, prio:normal, status:in-progress

#889 Merge to Dev - Style guide compliance and grammatical fixes
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#896 Merge to dev - Redis db version and docker image version updated #65
  README.md
Labels: prio:normal, status:in-progress, type:doc

#895 Odim-5783: Added new handler for page not found error
  lib-utilities/response/errorresponse.go
  lib-utilities/response/response.go
  svc-api/handle/handlers.go
  svc-api/router/router.go
Labels: type:techdebt, prio:low, status:in-progress

#897 Implement action under license service for Systems and Managers resource URLs
  lib-dmtf/model/licenses.go
  lib-utilities/proto/licenses/licenses.proto
  svc-api/handle/handlers.go
  svc-api/handle/licenses.go
  svc-api/handle/licenses_test.go
  svc-api/router/router.go
  svc-api/rpc/licenses.go
  svc-licenses/lcommon/common.go
  svc-licenses/licenses/common_test.go
  svc-licenses/licenses/licenses.go
  svc-licenses/licenses/licenses_test.go
  svc-licenses/model/licenses.go
  svc-licenses/rpc/licenses.go
  svc-licenses/rpc/licenses_test.go
Labels: type:feature, prio:normal, status:in-progress

#898 As a developer I want to access redis DB with authentication at the start of every ODIM service
  .github/workflows/build_unittest.yml
  .github/workflows/odimra_deployment.yml
  install/Docker/dockerfiles/Dockerfile.redis
  install/Docker/dockerfiles/scripts/redis-checkdb.sh
  install/Docker/dockerfiles/scripts/redis-createschema.sh
  install/Docker/dockerfiles/scripts/redis-entrypointsetup.sh
  install/Docker/dockerfiles/scripts/redis-master.conf
  install/Docker/dockerfiles/scripts/redis-slave.conf
  lib-messagebus/datacommunicator/redisstreamcomm.go
  lib-persistence-manager/persistencemgr/config.go
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/unit_test_db_confighelp.go
  lib-utilities/common/mockconfig.go
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/mockconfig.go
  odim-controller/helmcharts/account-session/templates/deployment.yaml
  odim-controller/helmcharts/aggregation/templates/deployment.yaml
  odim-controller/helmcharts/api/templates/deployment.yaml
  odim-controller/helmcharts/events/templates/deployment.yaml
  odim-controller/helmcharts/fabrics/templates/deployment.yaml
  odim-controller/helmcharts/licenses/templates/deployment.yaml
  odim-controller/helmcharts/managers/templates/deployment.yaml
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-secret/templates/secret.yaml
  odim-controller/helmcharts/odimra-secret/values.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/values.yaml
  odim-controller/helmcharts/redis/templates/redis-inmemory-statefulset.yaml
  odim-controller/helmcharts/redis/templates/redis-ondisk-statefulset.yaml
  odim-controller/helmcharts/redis/values.yaml
  odim-controller/helmcharts/systems/templates/deployment.yaml
  odim-controller/helmcharts/task/templates/deployment.yaml
  odim-controller/helmcharts/telemetry/templates/deployment.yaml
  odim-controller/helmcharts/update/templates/deployment.yaml
  odim-controller/scripts/gen_odimra_certs.sh
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  odim-controller/scripts/odim-controller.py
Labels: type:feature, prio:normal, status:in-progress

#899 Odim 5843: Sonarqube: Validate/Fix the security hostspots for ODIMRA
  .github/workflows/odimra_deployment.yml
  svc-events/evcommon/common_test.go
  svc-events/evcommon/mock.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription_test.go
  svc-events/rpc/events_test.go
Labels: type:bug, prio:normal, status:in-progress

#900 Redis TLS changes to be changed in UR plugin
  plugin-unmanaged-racks/db/persistence.go
  plugin-unmanaged-racks/rest/module.go
  plugin-unmanaged-racks/rest/module_test.go
Labels: type:feature, prio:normal, status:in-progress

#901 Implement action under license service for Aggregate resource URLs
  svc-licenses/lcommon/common.go
  svc-licenses/licenses/common.go
  svc-licenses/licenses/common_test.go
  svc-licenses/licenses/licenses.go
  svc-licenses/licenses/licenses_test.go
  svc-licenses/model/licenses.go
  svc-licenses/rpc/licenses_test.go
Labels: type:feature, prio:normal, status:in-progress

#903 Merge to dev - Update Redfish schema and spec versions
  README.md
Labels: prio:normal, status:in-progress, type:doc

#902 ODIM-5879 Redis authentication changes to be changed in UR plugin
  odim-controller/helmcharts/urplugin/urplugin/templates/configmaps.yaml
  odim-controller/helmcharts/urplugin/urplugin/templates/deployment.yaml
  plugin-unmanaged-racks/config/config.go
  plugin-unmanaged-racks/db/persistence.go
Labels: type:feature, prio:normal, status:in-progress

#904 Merge to dev - Update Redfish schema and spec versions
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#905 Merge to Dev - Add POST method for LicenseService
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#907 Merge to dev - Replace creds with variable strings
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#908 Merge to dev - Update IP addresses with style guide compliant IPs in API readme
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#909 Merge to dev - Update IP addresses with style guide compliant IPs in GS readme
  README.md
Labels: prio:normal, status:in-progress, type:doc

#912 Added heading level 2 for LicenseService section in toc
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#910 Merge to dev - Peer and self review
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#913 Validate the db connection with authentication on multi node deployment
  lib-messagebus/datacommunicator/redisstreamcomm.go
  lib-persistence-manager/persistencemgr/redis.go
  odim-controller/scripts/odim-controller.py
Labels: type:feature, prio:normal, status:in-progress

#915 Merge to dev - Cleanup of the API readme
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#917 Merge to dev - protoc compiler information #916
  README.md
Labels: prio:normal, status:in-progress, type:doc

#918 odim 6718:Adding logic to check the members value
  svc-aggregation/system/common.go
Labels: type:bug, prio:normal, status:in-progress

#911 Odim-5756: Updating the kubernetes version to v1.23.5 with the kubespray-2.18.1 release
  .github/workflows/odimra_deployment.yml
  odim-controller/kubespray/kubespray-2.17.0.tar.gz
  odim-controller/kubespray/kubespray-2.18.1.tar.gz
  odim-controller/odimra/group_vars/all/requirements.yaml
  odim-controller/odimra/roles/configure-proxy/tasks/main.yaml
Labels: prio:normal, status:in-progress

#920 BRUCE-5743 Aggregates request payload and response is not as per redfish spec
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/agresponse/aggregationsource.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/aggregate_test.go
Labels: type:bug, prio:normal, status:in-progress

#922 Updated metadata as per new Redfish schema 2022.1
  svc-api/handle/handlers.go
  svc-fabrics/README.md
Labels: prio:high, type:techdebt, status:in-progress

#924 Odim-6136: Enabled support for persists events
  svc-events/evcommon/common.go
  svc-events/events/publishevttosubscriber.go
Labels: prio:high, type:techdebt, status:in-progress
