Repository ODIM-Project/ODIM, pull requests merged in 2022-01, with the labels that each got.

#724 ODIM-66 Set flag for reading undelivered events in multiple instance
  lib-utilities/config/config.go
  lib-utilities/config/constants.go
  lib-utilities/config/odimra_config.json
  svc-events/evcommon/common.go
  svc-events/evcommon/mock.go
  svc-events/events/evtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/evmodel/events.go
  svc-events/evmodel/events_test.go
  svc-events/rpc/events.go
Labels: type:feature, prio:normal, status:in-progress

#725 ODIM Introduction and architecture sections - Merge content and diagram to Dev
  docs/README.md
  docs/images/redfish_data_model.png
Labels: type:doc

#726 Golang version update: Merge content and diagram to Dev
  README.md
Labels: type:doc

#728 odim 74:Adding changes related to the redis stream event consuming
  lib-messagebus/datacommunicator/header.go
  lib-messagebus/datacommunicator/redisstreamcomm.go
  lib-messagebus/go.mod
  lib-messagebus/go.sum
  svc-events/consumer/consumer.go
  svc-events/consumer/consumer_test.go
  svc-events/main.go
Labels: prio:high, type:feature, status:in-progress

#729 Odim-5449: Update registry version to latest
  lib-utilities/errors/constants.go
  lib-utilities/response/response.go
  plugin-dell/dpresponse/errorResponse.go
  plugin-lenovo/lphandler/update.go
  plugin-lenovo/lpresponse/errorResponse.go
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-api/handle/handlers_test.go
  svc-events/evresponse/errorResponse.go
Labels: type:bug, prio:normal, status:in-progress

#731 odim:Renaming the MessageQueueConfigFilePath to MessageBusConfigFilePath
  build/DELLPlugin/edit_config.sh
  build/LenovoPlugin/edit_config.sh
  build/RFPlugin/edit_config.sh
  build/odimra/edit_config.sh
  lib-utilities/common/responses.go
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/constants.go
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/configmaps.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  plugin-dell/config/README.md
  plugin-dell/config/config.go
  plugin-dell/config/dell_config.json
  plugin-dell/dphandler/biosSettings_test.go
  plugin-dell/dpmessagebus/publish.go
  plugin-dell/main.go
  plugin-lenovo/config/config.go
  plugin-lenovo/config/lenovo_config.json
  plugin-lenovo/lphandler/biosSettings_test.go
  plugin-lenovo/lpmessagebus/publish.go
  plugin-lenovo/main.go
  plugin-redfish/config/config.go
  plugin-redfish/config/config.json
  plugin-redfish/main.go
  plugin-redfish/rfphandler/biosSettings_test.go
  plugin-redfish/rfpmessagebus/publish.go
  svc-aggregation/agmessagebus/publish.go
  svc-aggregation/main.go
  svc-events/consumer/consumer.go
  svc-events/main.go
  svc-task/main.go
  svc-task/tmessagebus/publish.go
Labels: type:feature, prio:normal, status:in-progress

#732 Merge updated URP hostname and password content to dev branch
  docs/README.md
Labels: type:doc

#730 Odim-5335: Update ODIM to latest DMTF schema
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/ComputerSystem.go
  lib-dmtf/model/Links.go
  lib-dmtf/model/addressPool.go
  lib-dmtf/model/common.go
  lib-dmtf/model/endpoint.go
  lib-dmtf/model/events.go
  lib-dmtf/model/fabric.go
  lib-dmtf/model/manager.go
  lib-dmtf/model/port.go
  lib-dmtf/model/power.go
  lib-dmtf/model/resourceCollection.go
  lib-dmtf/model/serviceRoot.go
  lib-dmtf/model/storage.go
  lib-dmtf/model/switch.go
  lib-dmtf/model/telemetry.go
  lib-dmtf/model/thermal.go
  lib-dmtf/model/zones.go
  svc-account-session/asresponse/accounts.go
  svc-account-session/asresponse/session.go
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/agmodel/system.go
  svc-aggregation/agresponse/aggregationsource.go
  svc-aggregation/agresponse/rpc.go
  svc-api/go.mod
  svc-api/go.sum
  svc-api/models/serviceroot.go
  svc-api/response/accounts.go
  svc-api/response/session.go
  svc-events/evresponse/events.go
  svc-fabrics/fabresponse/fabrics.go
  svc-managers/mgrmodel/manager.go
  svc-managers/mgrresponse/managers.go
  svc-systems/sresponse/Collection.go
  svc-task/tresponse/task.go
  svc-telemetry/go.mod
  svc-telemetry/go.sum
  svc-telemetry/tlresponse/telemetryservice.go
  svc-update/uresponse/updateservice.go
Labels: prio:normal, status:in-progress

#733 Merge content of "updated ODIMRA schema to the latest Redfish release" to Dev
  docs/README.md
Labels: type:doc

#735 Odim-4558: Upgrading the kubespray version
  .github/workflows/odimra_deployment.yml
  odim-controller/kubespray/configure-kubespray.sh
  odim-controller/kubespray/kubespray-2.14.0.tar.gz
  odim-controller/kubespray/kubespray-2.17.0.tar.gz
  odim-controller/odimra/group_vars/all/requirements.yaml
  odim-controller/odimra/install.yaml
  odim-controller/odimra/pre_upgrade.yaml
  odim-controller/odimra/roles/deploy-plugin/tasks/main.yaml
  odim-controller/odimra/roles/install/tasks/main.yaml
  odim-controller/odimra/roles/post-uninstall/tasks/main.yaml
  odim-controller/odimra/roles/pre-install/tasks/main.yaml
  odim-controller/odimra/roles/remove-plugin/tasks/main.yaml
  odim-controller/odimra/roles/upgrade-config/tasks/main.yaml
  odim-controller/odimra/uninstall.yaml
  odim-controller/scripts/odim-controller.py
Labels: status:in-progress

#736 URP, GRF docker image version upgrade - Merge to dev
  README.md
Labels: type:doc

#737 EMB configuration process update - Merge to Dev
  plugin-redfish/README.md
Labels: type:doc

#738 Odim 76:Adding logic of Acknowledgingthe events
  lib-messagebus/datacommunicator/config.go
  lib-messagebus/datacommunicator/redisstreamcomm.go
  lib-messagebus/platforms/platformconfig.toml
  odim-controller/helmcharts/dellplugin/dellplugin-config.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/values.yaml
  odim-controller/helmcharts/grfplugin/grfplugin-config.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/configmaps.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/values.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin-config.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/configmaps.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/values.yaml
  odim-controller/helmcharts/odimra-platformconfig/templates/configmaps.yaml
  plugin-dell/config/config.go
  plugin-dell/config/dell_config.json
  plugin-dell/go.mod
  plugin-dell/go.sum
  plugin-lenovo/config/config.go
  plugin-lenovo/config/lenovo_config.json
  plugin-lenovo/go.mod
  plugin-lenovo/go.sum
  plugin-redfish/config/config.go
  plugin-redfish/config/config.json
Labels: prio:high, type:feature, status:in-progress

#739 Odim 77:Updating the hostname split
  svc-aggregation/agmodel/system.go
  svc-aggregation/agresponse/aggregationsource.go
  svc-aggregation/system/update.go
Labels: type:bug, prio:high, status:in-progress

#740 Updated audit logs to syslog format
  lib-utilities/proto/session/session.pb.go
  lib-utilities/proto/session/session.proto
  lib-utilities/services/auth.go
  svc-account-session/asresponse/accounts.go
  svc-account-session/rpc/sessions.go
  svc-account-session/session/getsession.go
  svc-account-session/session/getsession_test.go
  svc-api/response/accounts.go
  svc-api/router/router.go
Labels: type:feature, prio:normal, status:in-progress

#743 Odim 79:Updating the ubuntu base image
  .github/workflows/build_unittest.yml
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.dellplugin
  install/Docker/dockerfiles/Dockerfile.etcd
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.kafka
  install/Docker/dockerfiles/Dockerfile.lenovoplugin
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.telemetry
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/Dockerfile.urplugin
  install/Docker/dockerfiles/Dockerfile.zookeeper
Labels: type:techdebt, prio:normal, status:in-progress

#742 ODIM-78 Remove compiled proto files from GIT repo
  .github/workflows/build_unittest.yml
  .gitignore
  install/Docker/dockerfiles/Dockerfile.odim
  install/Docker/dockerfiles/scripts/build_odim.sh
  lib-utilities/proto/account/account.pb.go
  lib-utilities/proto/aggregator/aggregator.pb.go
  lib-utilities/proto/auth/odim_auth.pb.go
  lib-utilities/proto/chassis/chassis.pb.go
  lib-utilities/proto/events/events.pb.go
  lib-utilities/proto/fabrics/fabrics.pb.go
  lib-utilities/proto/managers/managers.pb.go
  lib-utilities/proto/role/role.pb.go
  lib-utilities/proto/session/session.pb.go
  lib-utilities/proto/systems/systems.pb.go
  lib-utilities/proto/task/task.pb.go
  lib-utilities/proto/telemetry/telemetry.pb.go
  lib-utilities/proto/update/update.pb.go
Labels: type:feature, prio:normal, status:in-progress

#745 odim-5495: Add go.mod file in scripts folder
  odim-controller/scripts/go.mod
  odim-controller/scripts/go.sum
Labels: type:bug

#746 ODIM-5502: Fixing the HA deployment issue & updating the k8s images
  odim-controller/odimra/group_vars/all/all.yaml
  odim-controller/scripts/odim-controller.py
Labels: type:bug

#749 Updated authentication/authorization logs in syslog format
  lib-utilities/common/constants.go
  lib-utilities/errors/constants.go
  lib-utilities/logs/common.go
  lib-utilities/logs/logging.go
  lib-utilities/response/response.go
  lib-utilities/services/auth.go
  lib-utilities/services/eventsubscription.go
  lib-utilities/services/task.go
  svc-account-session/account/create.go
  svc-account-session/account/delete.go
  svc-account-session/account/getaccounts.go
  svc-account-session/account/update.go
  svc-account-session/auth/auth.go
  svc-account-session/auth/session.go
  svc-account-session/role/create.go
  svc-account-session/role/delete.go
  svc-account-session/role/getroles.go
  svc-account-session/role/update.go
  svc-account-session/rpc/account.go
  svc-account-session/rpc/role.go
  svc-account-session/session/create.go
  svc-account-session/session/create_test.go
  svc-account-session/session/delete.go
  svc-account-session/session/getsession.go
  svc-aggregation/rpc/aggregator.go
  svc-api/handle/account.go
  svc-api/handle/aggregator.go
  svc-api/handle/chassis.go
  svc-api/handle/events.go
  svc-api/handle/fabrics.go
  svc-api/handle/handlers.go
  svc-api/handle/managers.go
  svc-api/handle/role.go
  svc-api/handle/sessions.go
  svc-api/handle/systems.go
  svc-api/handle/task.go
  svc-api/handle/telemetry.go
  svc-api/handle/update.go
  svc-api/router/router.go
  svc-events/rpc/events.go
  svc-managers/rpc/manager.go
  svc-systems/rpc/chassis.go
  svc-systems/rpc/systems.go
  svc-telemetry/rpc/telemetry.go
  svc-update/rpc/update.go
Labels: prio:normal
