Repository ODIM-Project/ODIM, pull requests merged in 2022-03, with the labels that each got.

#809 Merge to Dev - Update Sample Responses as per team's feedback + adding "generating and importing certs section before adding server section"
  docs/README.md
Labels: type:doc

#813 Merge to Dev - Overall Team's feedback + Grammatical changes
  README.md
  docs/images/kubernetes_images.png
Labels: type:doc

#780 odim-5465: Adding routes to storage controller and subordinate resources
  svc-api/router/router.go
Labels: prio:normal, status:in-progress

#816 Odim-5632: Empty Certificates link is not allowed in Drives
  lib-dmtf/model/storage.go
Labels: type:bug, status:in-progress

#817 Odim 5612 Publishing manager events when delete server
  svc-aggregation/system/deleteaggregationsource.go
Labels: type:bug, prio:normal, status:in-progress

#819 Service Validator: "DateTime" property in odimra and plugin manager is not the valid date format - Bug fix
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
Labels: type:bug, prio:low, status:in-progress

#820 Odim 5636:Service Validator: 'ReadOnly' and 'Operator' Roles Should not allow Delete Operation as per the 2021.2 spec
  svc-api/handle/role.go
Labels: type:bug, prio:normal, status:in-progress

#821 Odim 5645:Resource password to be hidden part of task response body
  lib-utilities/logs/common.go
  lib-utilities/logs/logging.go
  svc-aggregation/system/common.go
Labels: type:bug, prio:normal, status:in-progress

#818 Odim-5638: Resolve errors in api.log while performing POST operation while creating a new session & add TaskCollection as odata type
  lib-utilities/common/constants.go
  svc-account-session/session/getsession.go
  svc-api/router/router.go
  svc-task/thandle/thandle.go
Labels: type:bug, status:in-progress

#826 Odim 5510: Code to delete logservicecollection while delete plugin
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
Labels: type:bug, prio:normal, status:in-progress

#823 Odim-5641:Remove older Registry file
  lib-utilities/etc/Base.1.0.0.json
  lib-utilities/etc/Base.1.10.0.json
  lib-utilities/etc/Base.1.10.1.json
  lib-utilities/etc/Base.1.2.0.json
  lib-utilities/etc/Base.1.3.0.json
  lib-utilities/etc/Base.1.3.1.json
  lib-utilities/etc/Base.1.4.0.json
  lib-utilities/etc/Base.1.5.0.json
  lib-utilities/etc/Base.1.6.0.json
  lib-utilities/etc/Base.1.6.1.json
  lib-utilities/etc/Base.1.7.0.json
  lib-utilities/etc/Base.1.8.0.json
  lib-utilities/etc/Base.1.8.1.json
  lib-utilities/etc/Base.1.8.2.json
  lib-utilities/etc/Base.1.9.0.json
  lib-utilities/etc/Composition.1.0.0.json
  lib-utilities/etc/Composition.1.0.1.json
  lib-utilities/etc/NetworkDevice.1.0.0.json
  lib-utilities/etc/Redfish_1.0.1_PrivilegeRegistry.json
  lib-utilities/etc/Redfish_1.0.2_PrivilegeRegistry.json
  lib-utilities/etc/Redfish_1.0.3_PrivilegeRegistry.json
  lib-utilities/etc/Redfish_1.0.4_PrivilegeRegistry.json
  lib-utilities/etc/ResourceEvent.1.0.0.json
  lib-utilities/etc/ResourceEvent.1.0.1.json
  lib-utilities/etc/ResourceEvent.1.0.2.json
  lib-utilities/etc/TaskEvent.1.0.0.json
  lib-utilities/etc/TaskEvent.1.0.1.json
  lib-utilities/etc/TaskEvent.1.0.2.json
Labels: type:techdebt, prio:normal

#824 odim-5243: Validate Simple update post request
  svc-api/handle/update.go
  svc-api/handle/update_test.go
  svc-update/update/simpleUpdate.go
Labels: type:bug, prio:normal, status:in-progress

#825 Support for DualStack based single node deployment
  install/Docker/dockerfiles/scripts/redis-entrypointsetup.sh
  install/Docker/dockerfiles/scripts/redis-master.conf
  install/Docker/dockerfiles/scripts/redis-slave.conf
  lib-utilities/config/config.go
  odim-controller/helmcharts/api/templates/service.yaml
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-config/values.yaml
  odim-controller/kubespray/configure-kubespray.sh
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  odim-controller/scripts/odim-controller.py
Labels: type:feature, prio:normal, status:in-progress

#828 odimra config commit override fix
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/constants.go
  lib-utilities/config/mockconfig.go
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
Labels: type:bug, prio:high, status:in-progress

#827 Odim 83:Support for DualStack based three node deployment
  odim-controller/odimra/roles/configure-keepalived/tasks/main.yaml
  odim-controller/odimra/roles/configure-keepalived/templates/keepalived.conf.j2
  odim-controller/odimra/roles/configure-proxy/tasks/main.yaml
  odim-controller/odimra/roles/configure-proxy/templates/api_proxy_server.conf.j2
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  odim-controller/scripts/odim-controller.py
Labels: prio:high, type:feature, status:in-progress

#829 Updated Iris and etcd packages
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-messagebus/go.mod
  lib-messagebus/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  lib-rest-client/go.mod
  lib-rest-client/go.sum
  lib-utilities/go.mod
  lib-utilities/go.sum
  lib-utilities/services/rpcService.go
  plugin-dell/go.mod
  plugin-dell/go.sum
  plugin-lenovo/go.mod
  plugin-lenovo/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-api/handle/handlers.go
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-telemetry/go.mod
  svc-telemetry/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: type:bug, prio:high, status:in-progress

#830 odim-5631: AccountService/Roles should not allow post operation
  .github/workflows/odimra_deployment.yml
  svc-api/handle/role.go
  svc-api/handle/role_test.go
  svc-api/router/router.go
  svc-api/rpc/role.go
Labels: type:bug, prio:normal, status:in-progress

#832 Added support for delete BMC account
  lib-utilities/proto/managers/managers.proto
  svc-api/handle/managers.go
  svc-api/handle/managers_test.go
  svc-api/router/router.go
  svc-api/rpc/managers.go
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/rpc/manager.go
  svc-managers/rpc/manager_test.go
Labels: type:feature, prio:normal, status:in-progress

#831 500 response while getting individual role id if invalid role id is provided
  svc-managers/managers/managers.go
Labels: type:bug, prio:normal, status:in-progress

#833 Running of go tools and fixing issues
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/ComputerSystem.go
  lib-dmtf/model/addressPool.go
  lib-dmtf/model/manager.go
  lib-dmtf/model/port.go
  lib-dmtf/model/serviceRoot.go
  lib-persistence-manager/persistencemgr/redis_test.go
  svc-systems/chassis/create.go
  svc-systems/chassis/delete.go
  svc-systems/chassis/get.go
  svc-systems/chassis/get_collection.go
  svc-systems/chassis/update.go
  svc-systems/plugin/client.go
  svc-systems/plugin/client_mock.go
  svc-systems/rpc/chassis.go
  svc-systems/smodel/systems.go
  svc-systems/sresponse/Collection.go
  svc-update/update/common.go
  svc-update/update/getresources.go
  svc-update/update/simpleUpdate.go
  svc-update/update/startUpdate.go
  svc-update/uresponse/updateservice.go
Labels: type:bug, prio:normal, status:in-progress

#834 Odim 5673: changes for adding logservice member and log entries under odimra and plugin manager
  lib-dmtf/model/Chassis.go
  lib-utilities/common/constants.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-api/router/router.go
  svc-managers/main.go
  svc-managers/managers/managers.go
Labels: type:bug, prio:normal, status:in-progress

#835 Response correction under telemetry service
  svc-telemetry/telemetry/telemetry.go
Labels: type:bug, prio:normal, status:in-progress

#836 ODIM-5648: Added Aggregation action info under AggregationService
  lib-utilities/proto/aggregator/aggregator.proto
  svc-aggregation/agresponse/rpc.go
  svc-aggregation/rpc/aggregator.go
  svc-api/handle/aggregator.go
  svc-api/router/router.go
  svc-api/rpc/aggregator.go
Labels: type:techdebt, prio:normal, status:in-progress

#837 odim-5611: Reduce the number of task published while adding server
  svc-task/thandle/thandle.go
Labels: type:feature, prio:normal, status:in-progress

#838 ODIM-5698 Limiting the resources which are retrieving from BMC
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  lib-utilities/config/config.go
  lib-utilities/config/mockconfig.go
  lib-utilities/config/odimra_config.json
  lib-utilities/response/errorresponse.go
  lib-utilities/response/response.go
  lib-utilities/services/rpcService.go
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  svc-api/handle/managers_test.go
  svc-api/middleware/middleware.go
  svc-api/router/router.go
Labels: type:bug, prio:normal, status:in-progress

#840 Odim-5703:Removed empty Certificate Property from StorageController
  lib-dmtf/model/storage.go
Labels: type:techdebt

#841 ODIM-5704: Removed AccountTypes from Manager Account Details
  lib-dmtf/model/accountService.go
Labels: type:bug, prio:normal, status:in-progress

#842 Odim 5623: Support for Update BMC account under Managers
  lib-utilities/proto/managers/managers.proto
  svc-api/handle/managers.go
  svc-api/handle/managers_test.go
  svc-api/router/router.go
  svc-api/rpc/managers.go
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrmodel/manager.go
  svc-managers/rpc/manager.go
  svc-managers/rpc/manager_test.go
Labels: type:feature, prio:normal, status:in-progress

#839 Fix broken link under plugin configuration parameters
  README.md
Labels: prio:normal, status:resolved, type:doc

#843 ODIM- 85 Limiting number of requests per session and number of sessions per user
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/odimra_config.json
  lib-utilities/response/errorresponse.go
  lib-utilities/response/errorresponse_test.go
  lib-utilities/response/response.go
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  svc-api/handle/sessions.go
  svc-api/ratelimiter/ratelimiter.go
  svc-api/router/router.go
  svc-api/rpc/sessions.go
Labels: type:bug, prio:high, status:in-progress

#844 BRUCE-5702-Service validator: "Settings" property in 'NetworkPort' schema is not redfish valid property
  lib-dmtf/model/networkport.go
Labels: type:bug, prio:normal, status:in-progress

#845 ODIM-85 Rate limiting should return 503 status code
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  lib-utilities/response/errorresponse.go
  lib-utilities/response/response.go
  svc-api/handle/sessions.go
  svc-api/middleware/middleware.go
  svc-api/ratelimiter/ratelimiter.go
  svc-api/router/router.go
  svc-api/rpc/managers.go
Labels: type:bug, prio:high, status:in-progress
