Repository ODIM-Project/ODIM, pull requests merged in 2023-02, with the labels that each got.

#1092 Add process logs for svc-event
  lib-utilities/common/constants.go
  lib-utilities/common/workerpool.go
  lib-utilities/common/workerpool_test.go
  plugin-dell/dpmessagebus/publish.go
  plugin-dell/main.go
  plugin-lenovo/lpmessagebus/publish.go
  plugin-lenovo/main.go
  plugin-redfish/main.go
  plugin-redfish/rfpmessagebus/publish.go
  svc-events/consumer/consumer.go
  svc-events/evcommon/common.go
  svc-events/evcommon/common_test.go
  svc-events/evcommon/mock.go
  svc-events/events/common.go
  svc-events/events/common_test.go
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription.go
  svc-events/events/evtsubscription_test.go
  svc-events/events/getevtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
  svc-events/events/submittestevent_test.go
  svc-events/events/subscriptionCache.go
  svc-events/events/subscriptionCache_test.go
  svc-events/evmodel/events.go
  svc-events/main.go
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
Labels: type:techdebt, prio:normal, status:in-progress

#1094 Upgrading Kubernetes version to 1.24
  .github/workflows/odimra_deployment.yml
  odim-controller/helmcharts/kafka-ha/templates/kafka-ha-deployment.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-secondary-statefulset.yaml
  odim-controller/helmcharts/zookeeper-ha/templates/zookeeper-ha-deployment.yaml
  odim-controller/kubespray/kubespray-2.18.1.tar.gz
  odim-controller/kubespray/kubespray-2.20.0.tar.gz
  odim-controller/odimra/group_vars/all/all.yaml
  odim-controller/odimra/group_vars/all/requirements.yaml
  odim-controller/odimra/roles/deploy-plugin/tasks/main.yaml
  odim-controller/odimra/roles/k8-copy-image/tasks/main.yaml
  odim-controller/odimra/roles/k8-delete-image/tasks/main.yaml
  odim-controller/odimra/roles/odimra-copy-image/tasks/main.yaml
  odim-controller/odimra/roles/odimra-delete-image/tasks/main.yaml
  odim-controller/odimra/roles/plugin-delete-image/tasks/main.yaml
  odim-controller/odimra/roles/remove-plugin/tasks/main.yaml
  odim-controller/scripts/odim-controller.py
Labels: prio:high, type:feature, status:in-progress

#1098 Adding the context to the Update task when there is a error case
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/reset.go
Labels: type:bug, prio:high, status:in-progress

#1100 Updated simpleupdate response code
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1099 Added new Appendix section + updated log levels and application logs sections
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1102 Updated samples of audit logs and security logs and added sample log in JSON format
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1101 Moved log levels to API readme + added logFormat and logLevel properties in kube yaml file + updated third party pkg versions
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1104 Updated k8s image sample + K8S service versions + noproxy ip
  README.md
  docs/images/kubernetes_images.png
Labels: prio:normal, status:in-progress, type:doc

#1105 changed node role in sentinels pods
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-sentinel-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-sentinel-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-sentinel-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-sentinel-secondary-statefulset.yaml
Labels: type:bug, prio:normal, status:in-progress

#1103 Cleanup logs and add debug logs in manager service
  svc-managers/managers/managers.go
  svc-managers/mgrcommon/common.go
  svc-managers/mgrmodel/manager.go
  svc-managers/rpc/manager.go
Labels: type:feature, prio:low

#1113 Updated base redis version to 7.0.8
  .github/workflows/build_unittest.yml
  build/Redis/Dockerfile.redis
  install/Docker/dockerfiles/Dockerfile.redis
  odim-controller/helmcharts/redis-ha/Chart.yaml
  odim-controller/helmcharts/redis/Chart.yaml
  odim-controller/helmcharts/redis/templates/_helpers.tpl
  odim-controller/odimra/group_vars/all/all.yaml
Labels: type:techdebt, prio:normal, status:in-progress

#1111 Reducing the number of task updates while adding the server
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/common.go
Labels: type:feature, prio:normal, status:in-progress

#1115 Updated versions of ODIM, plugin images and third-party software + troubleshooting readme link before deployment instructions + removed 'master' instances
  README.md
  docs/images/odimra_images.png
Labels: prio:normal, status:in-progress, type:doc

#1117 Replace master node with primary node + grammatical fixes
  docs/Troubleshooting.md
Labels: prio:normal, status:in-progress, type:doc

#1119 Replace master node with primary node + other fixes
  docs/Troubleshooting.md
Labels: prio:normal, status:in-progress, type:doc

#1122 Backup and restore of odim and plugins configuration
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1123 updated golang version
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1124 Updated golang version
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1125 Remove session token from logs
  lib-utilities/logs/logger.go
  lib-utilities/logs/logging.go
  svc-account-session/auth/auth.go
  svc-account-session/auth/session.go
  svc-account-session/role/delete.go
  svc-account-session/role/delete_test.go
  svc-account-session/rpc/account.go
  svc-account-session/rpc/account_test.go
  svc-account-session/rpc/role.go
  svc-account-session/rpc/role_test.go
  svc-account-session/session/getsession.go
  svc-account-session/session/getsession_test.go
Labels: type:feature, prio:normal, status:in-progress

#1127 Remove session tokens from logs
  svc-account-session/auth/session.go
  svc-account-session/session/delete.go
  svc-account-session/session/getsession.go
Labels: type:bug, prio:normal, status:in-progress

#1128 Remove session tokens from logs
  lib-utilities/logs/logger.go
  lib-utilities/logs/logging.go
  svc-account-session/auth/auth.go
  svc-account-session/auth/session.go
  svc-account-session/role/delete.go
  svc-account-session/role/delete_test.go
  svc-account-session/rpc/account.go
  svc-account-session/rpc/account_test.go
  svc-account-session/rpc/role.go
  svc-account-session/rpc/role_test.go
  svc-account-session/session/delete.go
  svc-account-session/session/getsession.go
  svc-account-session/session/getsession_test.go
Labels: type:bug, prio:normal, status:in-progress

#1120 Implement tasks for volume create functionality
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: type:feature, prio:normal, status:in-progress

#1131 Updating the syntax of load image for ctr command
  odim-controller/odimra/roles/pre-upgrade/tasks/main.yaml
Labels: type:bug, prio:low, status:in-progress

#1130 Fixed Chassis is not getting deleted from rack detail after server get deleted
  lib-messagebus/datacommunicator/kafkacomm.go
  svc-events/events/publishevttosubscriber.go
Labels: type:bug, prio:high, status:in-progress

#1134 Fixed Chassis is not getting deleted from rack detail after server get deleted
  lib-messagebus/datacommunicator/kafkacomm.go
  svc-events/events/publishevttosubscriber.go
Labels: type:bug, prio:high, status:in-progress

#1138 Fixed UpdateService.SimpleUpdate functionality for Dell servers
  plugin-dell/dphandler/update.go
Labels: type:bug, prio:high, status:in-progress

#1133 DellXR11 issue with SimpleUpdate
  plugin-dell/dphandler/update.go
Labels: prio:high

#1136 keyExpiryInterval is Configure from config
  lib-persistence-manager/persistencemgr/redis.go
  lib-utilities/config/config.go
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-config/values.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  odim-controller/scripts/odim-controller.py
  svc-task/tmodel/tmodel.go
Labels: type:techdebt, prio:normal, status:in-progress

#1132 Updating load image as per ctr syntax
  odim-controller/odimra/roles/pre-upgrade/tasks/main.yaml
Labels: type:bug, prio:low, status:in-progress

#1135 Implement tasks for Bios settings
  lib-utilities/common/generalerror.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/systems/bootorder.go
  svc-systems/systems/bootorder_test.go
  svc-systems/systems/storage.go
Labels: type:feature, prio:normal, status:in-progress

#1139 Updated docker images section + other minor fixes
  README.md
  docs/images/all_services_verification.png
  docs/images/kuberenetes_pods_verification.png
  docs/images/odimra_images.png
Labels: prio:normal, status:in-progress, type:doc

#1140 Updated connectionmethodvariant versions of plugin and sample request and responses of few services as per team's feedback
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1141 Update the restore and backup instructions of K8S and ODIM etcd
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1142 Updated docker images section + other minor fixes
  README.md
  docs/images/all_services_verification.png
  docs/images/kuberenetes_pods_verification.png
  docs/images/odimra_images.png
Labels: prio:normal, status:in-progress, type:doc

#1143 Updated connectionmethodvariant versions of plugin and sample request and responses of few services as per team's feedback
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1144 Update the restore and backup instructions of K8S and ODIM etcd
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1147 updated backup restore instructions for etcd and service pods
  README.md
  docs/images/all_services_verification.png
Labels: prio:normal, status:in-progress, type:doc

#1148 Updated backup and restore etcd sections + updated screenshot of service pods
  README.md
  docs/images/all_services_verification.png
Labels: prio:normal, status:in-progress, type:doc

#1146 Adding a check for the queue size before performing updateTaskQueue & GRFPlugin fix for simpleupdate
  lib-dmtf/model/update.go
  plugin-dell/dphandler/update.go
  plugin-redfish/rfphandler/update.go
  svc-events/main.go
  svc-task/main.go
  svc-task/tmodel/tmodel.go
  svc-task/tqueue/queue.go
Labels: type:bug, prio:normal, status:in-progress

#1149 Implement tasks for boot settings
  lib-utilities/common/constants.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/systems/bootorder.go
  svc-systems/systems/bootorder_test.go
  svc-task/thandle/thandle.go
Labels: type:feature, prio:normal, status:in-progress

#1152 Fixed incorrect command in updating log levels
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc
