Repository ODIM-Project/ODIM, pull requests merged in 2023-07, with the labels that each got.

#1271 Added CreateLimitReachedForResource error constant and function
  lib-utilities/response/errorresponse.go
  lib-utilities/response/response.go
Labels: type:techdebt, prio:low, status:in-progress

#1264 Change the redis logic to use go-redis library instead of multiple libraries
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  lib-persistence-manager/persistencemgr/config.go
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  lib-persistence-manager/persistencemgr/unit_test_db_confighelp.go
  lib-rest-client/go.mod
  lib-rest-client/go.sum
  lib-utilities/go.mod
  lib-utilities/go.sum
  plugin-dell/go.mod
  plugin-dell/go.sum
  plugin-lenovo/go.mod
  plugin-lenovo/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  plugin-unmanaged-racks/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/agcommon/common.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/common.go
  svc-aggregation/system/rediscoverinventory.go
  svc-api/go.mod
  svc-api/go.sum
  svc-events/events/subscriptionCache.go
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-licenses/go.mod
  svc-licenses/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/smodel/systems.go
  svc-systems/smodel/systems_test.go
  svc-task/go.mod
  svc-task/go.sum
  svc-task/main.go
  svc-task/thandle/thandle.go
  svc-task/thandle/thandle_test.go
  svc-task/thandle/tmonitor_test.go
  svc-task/tmodel/tmodel.go
  svc-task/tmodel/tmodel_test.go
  svc-telemetry/go.mod
  svc-telemetry/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: type:feature, prio:normal

#1273 update ubuntu version to 22.04
  .github/workflows/build_unittest.yml
  .github/workflows/odimra_deployment.yml
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.compositionService
  install/Docker/dockerfiles/Dockerfile.cs
  install/Docker/dockerfiles/Dockerfile.dellplugin
  install/Docker/dockerfiles/Dockerfile.etcd
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.kafka
  install/Docker/dockerfiles/Dockerfile.lenovoplugin
  install/Docker/dockerfiles/Dockerfile.licenses
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.telemetry
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/Dockerfile.urplugin
  install/Docker/dockerfiles/Dockerfile.zookeeper
  lib-messagebus/datacommunicator/config.go
  lib-utilities/common/crypto.go
  lib-utilities/config/config.go
  odim-controller/odimra/group_vars/all/requirements.yaml
  plugin-dell/dputilities/utility.go
  plugin-dell/dputilities/utility_test.go
  plugin-lenovo/lputilities/utility.go
  plugin-redfish/rfputilities/utility.go
  plugin-unmanaged-racks/config/config.go
  plugin-unmanaged-racks/utils/enigma.go
Labels: status:in-progress

#1275 Update ubuntu 22.04
  .github/workflows/build_unittest.yml
  .github/workflows/odimra_deployment.yml
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.compositionService
  install/Docker/dockerfiles/Dockerfile.cs
  install/Docker/dockerfiles/Dockerfile.dellplugin
  install/Docker/dockerfiles/Dockerfile.etcd
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.kafka
  install/Docker/dockerfiles/Dockerfile.lenovoplugin
  install/Docker/dockerfiles/Dockerfile.licenses
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.telemetry
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/Dockerfile.urplugin
  install/Docker/dockerfiles/Dockerfile.zookeeper
  lib-messagebus/datacommunicator/config.go
  lib-utilities/common/crypto.go
  lib-utilities/config/config.go
  odim-controller/odimra/group_vars/all/requirements.yaml
  plugin-dell/dputilities/utility.go
  plugin-dell/dputilities/utility_test.go
  plugin-lenovo/lputilities/utility.go
  plugin-redfish/rfputilities/utility.go
  plugin-unmanaged-racks/config/config.go
  plugin-unmanaged-racks/utils/enigma.go
Labels: type:techdebt, prio:normal, status:in-progress

#1278 Fixed Rediscovery of server in event service
  lib-persistence-manager/persistencemgr/redis.go
  svc-events/events/subscriptionCache.go
Labels: type:bug, prio:normal, status:in-progress

#1277 Using centralized odim logging framework in add host & removing the log directory creation when logsOnConsole is set to true
  install/Docker/dockerfiles/scripts/add-hosts/add-hosts.go
  install/Docker/dockerfiles/scripts/add-hosts/go.mod
  install/Docker/dockerfiles/scripts/add-hosts/go.sum
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_dellplugin.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_grfplugin.sh
  install/Docker/dockerfiles/scripts/start_lenovoplugin.sh
  install/Docker/dockerfiles/scripts/start_licenses.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_telemetry.sh
  install/Docker/dockerfiles/scripts/start_update.sh
  install/Docker/dockerfiles/scripts/start_urplugin.sh
  odim-controller/helmcharts/account-session/templates/deployment.yaml
  odim-controller/helmcharts/aggregation/templates/deployment.yaml
  odim-controller/helmcharts/api/templates/deployment.yaml
  odim-controller/helmcharts/dellplugin/dellplugin.sh
  odim-controller/helmcharts/dellplugin/dellplugin/templates/deployment.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/pv.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/pvc.yaml
  odim-controller/helmcharts/events/templates/deployment.yaml
  odim-controller/helmcharts/fabrics/templates/deployment.yaml
  odim-controller/helmcharts/grfplugin/grfplugin.sh
  odim-controller/helmcharts/grfplugin/grfplugin/templates/deployment.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/pv.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/pvc.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin.sh
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/deployment.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/pv.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/pvc.yaml
  odim-controller/helmcharts/licenses/templates/deployment.yaml
  odim-controller/helmcharts/managers/templates/deployment.yaml
  odim-controller/helmcharts/odimra-pv-pvc/templates/odimra-pv.yaml
  odim-controller/helmcharts/odimra-pv-pvc/templates/odimra-pvc.yaml
  odim-controller/helmcharts/systems/templates/deployment.yaml
  odim-controller/helmcharts/task/templates/deployment.yaml
  odim-controller/helmcharts/telemetry/templates/deployment.yaml
  odim-controller/helmcharts/update/templates/deployment.yaml
  odim-controller/helmcharts/urplugin/urplugin.sh
  odim-controller/helmcharts/urplugin/urplugin/templates/deployment.yaml
  odim-controller/helmcharts/urplugin/urplugin/templates/pv.yaml
  odim-controller/helmcharts/urplugin/urplugin/templates/pvc.yaml
  odim-controller/odimra/roles/pre-install/tasks/main.yaml
Labels: type:feature, prio:normal, status:in-progress
