Repository ODIM-Project/ODIM, pull requests merged in 2023-05, with the labels that each got.

#1216 Implement All SecureBoot operations supported by ILO6 and ILO5
  lib-dmtf/model/ComputerSystem.go
  lib-utilities/common/constants.go
  lib-utilities/proto/systems/systems.proto
  svc-api/handle/systems.go
  svc-api/router/router.go
  svc-api/rpc/fakeStruct_testfile.go
  svc-api/rpc/system.go
  svc-systems/rpc/systems.go
  svc-systems/smodel/systems.go
  svc-systems/systems/reset_test.go
  svc-systems/systems/secureBoot.go
  svc-systems/systems/secureBoot_test.go
Labels: prio:normal

#1214 Fixed three node event subscription cache sync up issue
  svc-events/events/subscriptionCache.go
Labels: type:bug, prio:normal, status:in-progress

#1211 Fix for failing unit test for svc-aggregation
  svc-aggregation/agcommon/common.go
  svc-aggregation/agcommon/common_test.go
  svc-aggregation/agmessagebus/publish.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/pluginHealthCheck.go
  svc-aggregation/system/rediscoverinventory.go
  svc-aggregation/system/systemstate.go
  svc-aggregation/system/update.go
Labels: type:bug, prio:normal

#1217 Add all log properties in dell plugin
  lib-utilities/common/constants.go
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/deployment.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/values.yaml
  plugin-dell/config/config.go
  plugin-dell/config/dell_config.json
  plugin-dell/dphandler/basicAuth.go
  plugin-dell/dphandler/biosSettings.go
  plugin-dell/dphandler/biosSettings_test.go
  plugin-dell/dphandler/bootorder.go
  plugin-dell/dphandler/common.go
  plugin-dell/dphandler/common_test.go
  plugin-dell/dphandler/createSession.go
  plugin-dell/dphandler/getResource.go
  plugin-dell/dphandler/getResource_test.go
  plugin-dell/dphandler/managers.go
  plugin-dell/dphandler/pluginStatus.go
  plugin-dell/dphandler/redfishEvents.go
  plugin-dell/dphandler/reset.go
  plugin-dell/dphandler/reset_test.go
  plugin-dell/dphandler/storage.go
  plugin-dell/dphandler/subscribeEvents.go
  plugin-dell/dphandler/subscribeEvents_test.go
  plugin-dell/dphandler/update.go
  plugin-dell/dpmiddleware/basicAuthenticate.go
  plugin-dell/dputilities/redfishClient.go
  plugin-dell/dputilities/redfishClient_test.go
  plugin-dell/dputilities/utility.go
  plugin-dell/dputilities/utility_test.go
  plugin-dell/go.mod
  plugin-dell/main.go
Labels: type:feature, prio:normal

#1219 Updated UT coverage for event service
  plugin-dell/dputilities/redfishClient_test.go
  svc-events/consumer/consumer_test.go
  svc-events/evcommon/common_test.go
Labels: type:techdebt, prio:low, status:in-progress

#1221 Adding BootOptionReference as a mandatory parameter
  svc-systems/systems/getresource.go
Labels: type:bug, prio:normal, status:in-progress

#1220 Making logs print on console configurable and correcting all the logging keys according to supportability requirements
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_dellplugin.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_grfplugin.sh
  install/Docker/dockerfiles/scripts/start_lenovoplugin.sh
  install/Docker/dockerfiles/scripts/start_licenses.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_telemetry.sh
  install/Docker/dockerfiles/scripts/start_update.sh
  install/Docker/dockerfiles/scripts/start_urplugin.sh
  lib-utilities/logs/logger.go
  odim-controller/helmcharts/dellplugin/dellplugin-config.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/values.yaml
  odim-controller/helmcharts/grfplugin/grfplugin-config.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/templates/configmaps.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/values.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin-config.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-config/values.yaml
  odim-controller/helmcharts/urplugin/urplugin-config.yaml
  odim-controller/helmcharts/urplugin/urplugin/templates/configmaps.yaml
  odim-controller/helmcharts/urplugin/urplugin/values.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  svc-account-session/main.go
  svc-aggregation/main.go
  svc-api/main.go
  svc-events/main.go
  svc-fabrics/main.go
  svc-licenses/main.go
  svc-managers/main.go
  svc-systems/main.go
  svc-task/main.go
  svc-telemetry/main.go
  svc-update/main.go
Labels: type:feature, prio:normal, status:in-progress

#1225 Update commands to install latest third-party packages
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1226 Update GRF plugin password and its messagebustype definition + added new properties and their description in ODIM config file and parameters table + added a note for odimVaultKeyFile in Generating encrypted passwords for nodes and Redis section
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1227 avoided creating new DB connection every time for Redis stream event messagebus
  lib-messagebus/datacommunicator/header.go
  lib-messagebus/datacommunicator/redisstreamcomm.go
Labels: prio:normal

#1228 Use go-redis library instead of redigo
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  lib-persistence-manager/persistencemgr/config.go
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  lib-persistence-manager/persistencemgr/unit_test_db_confighelp.go
  lib-persistence-manager/persistencemgr/unit_test_db_confighelp_test.go
  lib-rest-client/go.mod
  lib-rest-client/go.sum
  lib-utilities/go.mod
  lib-utilities/go.sum
  plugin-dell/go.mod
  plugin-dell/go.sum
  plugin-lenovo/go.mod
  plugin-lenovo/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  plugin-unmanaged-racks/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/rediscoverinventory.go
  svc-api/go.mod
  svc-api/go.sum
  svc-events/events/subscriptionCache.go
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-licenses/go.mod
  svc-licenses/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-systems/smodel/systems.go
  svc-systems/smodel/systems_test.go
  svc-task/go.mod
  svc-task/go.sum
  svc-task/main.go
  svc-task/thandle/thandle.go
  svc-task/thandle/thandle_test.go
  svc-task/thandle/tmonitor_test.go
  svc-task/tmodel/tmodel.go
  svc-task/tmodel/tmodel_test.go
  svc-telemetry/go.mod
  svc-telemetry/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: type:feature, prio:normal, status:in-progress

#1229 Consistency in the API readme
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1231 task for ComputerSystem.Reset request is updated to complete once the reset is done on device side
  lib-persistence-manager/persistencemgr/redis.go
  lib-utilities/common/constants.go
  svc-systems/rpc/systems.go
  svc-systems/scommon/common.go
  svc-systems/scommon/common_test.go
  svc-systems/smodel/systems.go
  svc-systems/smodel/systems_test.go
  svc-systems/systems/bootorder.go
  svc-systems/systems/reset.go
  svc-systems/systems/secureBoot.go
  svc-systems/systems/storage.go
  svc-task/tmodel/tmodel.go
Labels: type:feature, prio:normal, status:in-progress

#1233 Fixing the inconistency in logging parameter for syslog and json log format
  lib-utilities/logs/logger.go
Labels: type:bug, prio:normal, status:in-progress

#1234 Removing duplicate transactionID in svc-events
  svc-events/events/publishevttosubscriber.go
Labels: type:bug, prio:low, status:in-progress
