Repository ODIM-Project/ODIM, pull requests merged in 2023-04, with the labels that each got.

#1192 added task support for delete volume API
  lib-utilities/common/constants.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: type:bug, prio:normal, status:in-progress

#1195 FIx go tools errors in libraries and services
  lib-dmtf/model/events.go
  lib-dmtf/model/licenses.go
  lib-dmtf/model/networkport.go
  lib-dmtf/model/storage.go
  lib-dmtf/model/task.go
  lib-messagebus/datacommunicator/redisstreamcomm.go
  lib-persistence-manager/persistencemgr/redis.go
  lib-rest-client/pmbhandle/rest.go
  lib-utilities/common/constants.go
  lib-utilities/common/responses.go
  lib-utilities/logs/logger.go
  lib-utilities/logs/logging.go
  lib-utilities/logservice/common.go
  lib-utilities/response/response.go
  lib-utilities/services/auth.go
  lib-utilities/services/name.go
  plugin-unmanaged-racks/db/persistence.go
  svc-account-session/account/common.go
  svc-account-session/asmodel/account.go
  svc-account-session/rpc/account.go
  svc-account-session/rpc/auth.go
  svc-account-session/rpc/role.go
  svc-account-session/rpc/sessions.go
  svc-aggregation/agcommon/common.go
  svc-api/apicommon/common.go
  svc-api/handle/handlers.go
  svc-api/handle/licenses.go
  svc-api/main.go
  svc-api/router/router.go
  svc-api/rpc/account.go
  svc-api/rpc/aggregator.go
  svc-api/rpc/chassis.go
  svc-api/rpc/events.go
  svc-api/rpc/fabrics.go
  svc-api/rpc/licenses.go
  svc-api/rpc/managers.go
  svc-api/rpc/role.go
  svc-api/rpc/sessions.go
  svc-api/rpc/system.go
  svc-api/rpc/task.go
  svc-api/rpc/telemetry.go
  svc-api/rpc/update.go
  svc-events/evcommon/common.go
  svc-events/evcommon/mock.go
  svc-events/events/common.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/subscriptionCache.go
  svc-events/events/subscriptionCache_test.go
  svc-events/main.go
  svc-events/rpc/events.go
  svc-telemetry/tcommon/common.go
  svc-telemetry/telemetry/mockTelemetry.go
Labels: type:bug, prio:normal, status:in-progress

#1193 Adding mutex to avoid connection pool blocking
  svc-aggregation/system/rediscoverinventory.go
Labels: type:bug, prio:normal, status:in-progress

#1194 Added tasks for event subscription
  lib-utilities/proto/events/events.proto
  lib-utilities/services/eventsubscription.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/common.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-api/rpc/fakeStruct_testfile.go
  svc-events/events/common.go
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/subscriptionCache.go
  svc-events/events/subscriptionCache_test.go
  svc-events/evmodel/events.go
  svc-events/evresponse/events.go
  svc-events/evresponse/events_test.go
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
  svc-task/tcommon/common.go
  svc-task/thandle/thandle.go
  svc-task/thandle/tmonitor_test.go
  svc-task/tmodel/tmodel.go
Labels: type:techdebt, prio:normal, status:in-progress

#1203 Fixed fabric added event is not received in odim
  svc-events/events/publishevttosubscriber.go
Labels: type:bug, prio:high, status:in-progress

#1201 fixed BMC manager's /LogServices/IEL/Entries is giving 405 response on GET request
  svc-api/router/router.go
Labels: type:bug, prio:high, prio:normal, status:in-progress

#1198 Replacing nohup with tee to print the logs on console too
  install/Docker/dockerfiles/scripts/start_account_session.sh
  install/Docker/dockerfiles/scripts/start_aggregation.sh
  install/Docker/dockerfiles/scripts/start_api.sh
  install/Docker/dockerfiles/scripts/start_dellplugin.sh
  install/Docker/dockerfiles/scripts/start_events.sh
  install/Docker/dockerfiles/scripts/start_fabrics.sh
  install/Docker/dockerfiles/scripts/start_grfplugin.sh
  install/Docker/dockerfiles/scripts/start_licenses.sh
  install/Docker/dockerfiles/scripts/start_managers.sh
  install/Docker/dockerfiles/scripts/start_systems.sh
  install/Docker/dockerfiles/scripts/start_task.sh
  install/Docker/dockerfiles/scripts/start_telemetry.sh
  install/Docker/dockerfiles/scripts/start_update.sh
  install/Docker/dockerfiles/scripts/start_urplugin.sh
Labels: type:feature, prio:low, status:in-progress

#1197 fixed service validator issue: BMC manager response's 'Id' value should be as same as end of odata.id
  svc-managers/managers/managers.go
Labels: type:bug, prio:normal, status:in-progress

#1208 Removing the additional party's for service API's to avoid double deletion of session
  svc-api/handle/aggregator.go
  svc-api/router/router.go
Labels: type:bug, prio:normal, status:in-progress

#1199 fixed service validator issue: Ports URI should give portscollection response
  svc-api/router/router.go
Labels: prio:normal

#1206 Made changes for plugin not getting deleted properly
  svc-aggregation/system/deleteaggregationsource.go
Labels: type:bug, prio:normal, status:in-progress

#1207 Adding UT's for svc-aggregation agmessage package
  lib-utilities/config/mockconfig.go
  svc-aggregation/agmessagebus/publish.go
  svc-aggregation/agmessagebus/publish_test.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
Labels: type:bug, prio:normal, status:in-progress

#1210 Fixing the nil logs in aggregation service
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/get_resource.go
  svc-events/events/publishevttosubscriber.go
  svc-systems/systems/getresource.go
Labels: type:bug, status:in-progress
