Repository ODIM-Project/ODIM, pull requests merged in 2023-01, with the labels that each got.

#1060 Add process logs for Update service
  lib-utilities/common/constants.go
  lib-utilities/common/responses.go
  svc-account-session/auth/session.go
  svc-account-session/rpc/sessions.go
  svc-update/rpc/common.go
  svc-update/rpc/update.go
  svc-update/rpc/update_test.go
  svc-update/ucommon/common.go
  svc-update/ucommon/common_test.go
  svc-update/umodel/update.go
  svc-update/update/common.go
  svc-update/update/getresources.go
  svc-update/update/getresources_test.go
  svc-update/update/simpleUpdate.go
  svc-update/update/simpleUpdate_test.go
  svc-update/update/startUpdate.go
  svc-update/update/startUpdate_test.go
Labels: type:feature, prio:normal, status:in-progress

#1061 Cleanup logs for messagebus and persistence lib
  lib-messagebus/datacommunicator/config.go
  lib-messagebus/datacommunicator/header.go
  lib-messagebus/datacommunicator/kafkacomm.go
  lib-messagebus/datacommunicator/redisstreamcomm.go
  lib-messagebus/go.mod
  lib-messagebus/go.sum
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  svc-account-session/auth/session.go
  svc-task/tmodel/tmodel_test.go
Labels: type:feature, prio:normal, status:in-progress

#1065 Update LicenseService Response
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1067 Adding all processing log properties to svc-aggregation
  lib-utilities/common/constants.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/agcommon/common_test.go
  svc-aggregation/agmessagebus/publish.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/main.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/aggregator_test.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/aggregate_test.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/bootorder_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/connectionmethods.go
  svc-aggregation/system/connectionmethods_test.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/get_resource.go
  svc-aggregation/system/get_resource_test.go
  svc-aggregation/system/pluginHealthCheck.go
  svc-aggregation/system/pluginHealthCheck_test.go
  svc-aggregation/system/rediscoverinventory.go
  svc-aggregation/system/rediscoverinventory_test.go
  svc-aggregation/system/reset.go
  svc-aggregation/system/reset_test.go
  svc-aggregation/system/systemstate.go
  svc-aggregation/system/systemstate_test.go
  svc-aggregation/system/update.go
  svc-aggregation/system/update_test.go
Labels: prio:normal

#1069 Added a new section Backup and restore of Redis
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1068 Use standard logging for audit and security logs
  lib-rest-client/pmbhandle/rest.go
  lib-utilities/common/constants.go
  lib-utilities/logs/logger.go
  lib-utilities/logs/logging.go
  lib-utilities/response/response.go
  svc-account-session/account/getaccounts.go
  svc-account-session/auth/auth.go
  svc-account-session/session/create.go
  svc-api/router/router.go
  svc-systems/scommon/common.go
Labels: type:feature, prio:normal, status:in-progress

#1070 Adding EventService Schema model to lib-dmtf
  .github/workflows/build_unittest.yml
  lib-dmtf/model/events.go
Labels: prio:normal

#1072 Task for delete aggregation not getting updated
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/rediscoverinventory.go
Labels: type:bug, prio:normal, status:in-progress

#1074 Plugin should log all standard log properties in syslog format for update
  lib-rest-client/pmbhandle/rest.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/agcommon/common_test.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/pluginHealthCheck.go
  svc-aggregation/system/reset_test.go
  svc-aggregation/system/update_test.go
  svc-events/evcommon/common.go
  svc-events/evcommon/common_test.go
  svc-events/evcommon/mock.go
  svc-events/evcommon/mock_test.go
  svc-events/events/common.go
  svc-events/events/common_test.go
  svc-events/events/evtsubscription.go
  svc-fabrics/fabrics/common.go
  svc-fabrics/fabrics/getresource_test.go
  svc-fabrics/rpc/fabrics.go
  svc-fabrics/rpc/fabrics_test.go
  svc-licenses/lcommon/common.go
  svc-licenses/licenses/common.go
  svc-licenses/licenses/common_test.go
  svc-licenses/model/licenses.go
  svc-licenses/rpc/licenses_test.go
  svc-managers/managers/common.go
  svc-managers/managers/common_test.go
  svc-managers/mgrcommon/common.go
  svc-managers/mgrcommon/common_test.go
  svc-managers/rpc/manager_test.go
  svc-systems/chassis/fabric.go
  svc-systems/chassis/fabric_test.go
  svc-systems/chassis/getresource.go
  svc-systems/chassis/getresource_test.go
  svc-systems/plugin/client.go
  svc-systems/rpc/systems_test.go
  svc-systems/scommon/common.go
  svc-systems/scommon/common_test.go
  svc-systems/systems/reset.go
  svc-systems/systems/reset_test.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
  svc-telemetry/tcommon/common.go
  svc-telemetry/tcommon/common_test.go
  svc-telemetry/telemetry/common.go
  svc-telemetry/telemetry/mockTelemetry.go
  svc-update/rpc/update_test.go
  svc-update/ucommon/common.go
  svc-update/ucommon/common_test.go
  svc-update/update/common.go
  svc-update/update/getresources_test.go
Labels: type:feature, prio:normal, status:in-progress

#1073 Fixed default subscription delete from BMC server
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
Labels: type:bug, prio:normal, status:in-progress

#1077 Remove CompositionService
  README.md
  docs/images/odimra_images.png
Labels: prio:normal, status:in-progress, type:doc

#1076 Load event subscription table data into cache memory
  build/Redis/createschema.sh
  install/Docker/dockerfiles/scripts/add-hosts/add-hosts.go
  install/Docker/dockerfiles/scripts/redis-createschema.sh
  lib-dmtf/model/events.go
  lib-persistence-manager/persistencemgr/redis.go
  lib-utilities/common/constants.go
  svc-events/evcommon/common.go
  svc-events/evcommon/common_test.go
  svc-events/evcommon/mock.go
  svc-events/evcommon/mock_test.go
  svc-events/events/common.go
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription.go
  svc-events/events/evtsubscription_test.go
  svc-events/events/getevtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
  svc-events/events/submittestevent_test.go
  svc-events/events/subscriptionCache.go
  svc-events/events/subscriptionCache_test.go
  svc-events/evmodel/events.go
  svc-events/evmodel/events_test.go
  svc-events/evresponse/events.go
  svc-events/go.mod
  svc-events/main.go
Labels: prio:high, type:techdebt, status:in-progress

#1071 Cleanup logs and add debug logs in task service and add all log properties
  lib-persistence-manager/persistencemgr/redis.go
  lib-utilities/common/constants.go
  lib-utilities/common/generalerror.go
  lib-utilities/common/generalerror_test.go
  lib-utilities/services/task.go
  svc-aggregation/agcommon/common_test.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/bootorder_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/reset.go
  svc-events/evcommon/mock.go
  svc-events/evcommon/mock_test.go
  svc-events/events/common.go
  svc-events/events/common_test.go
  svc-events/events/evtsubscription.go
  svc-events/rpc/events.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/systems/common.go
  svc-systems/systems/reset.go
  svc-systems/systems/reset_test.go
  svc-task/go.mod
  svc-task/go.sum
  svc-task/tcommon/common.go
  svc-task/thandle/thandle.go
  svc-task/thandle/thandle_test.go
  svc-task/thandle/tmonitor.go
  svc-task/thandle/tmonitor_test.go
  svc-task/tmessagebus/publish.go
  svc-task/tmodel/tmodel.go
  svc-task/tmodel/tmodel_test.go
  svc-update/rpc/update.go
  svc-update/rpc/update_test.go
  svc-update/update/common.go
  svc-update/update/common_test.go
  svc-update/update/simpleUpdate.go
  svc-update/update/simpleUpdate_test.go
  svc-update/update/startUpdate.go
Labels: type:feature, prio:normal, status:in-progress

#1078 Added task service models to lib-dmtf #39
  lib-dmtf/model/task.go
Labels: type:feature, prio:normal, status:in-progress

#1079 Request body is not present in audit log
  lib-utilities/common/constants.go
  lib-utilities/logs/logging.go
  svc-api/handle/systems.go
  svc-api/main.go
  svc-api/router/router.go
Labels: type:bug, prio:normal, status:in-progress

#1082 Wrap the password with the single quote to support special character
  install/Docker/dockerfiles/scripts/redis-entrypointsetup.sh
  lib-persistence-manager/persistencemgr/redis.go
Labels: type:bug, prio:normal

#1080 Added expiry time on task and removed completed task index
  lib-persistence-manager/persistencemgr/redis.go
  svc-task/main.go
  svc-task/thandle/thandle.go
  svc-task/thandle/thandle_test.go
  svc-task/tmodel/tmodel.go
  svc-task/tmodel/tmodel_test.go
Labels: type:bug, prio:normal, status:in-progress

#1081 Added DisplayName property to Creating a Volume section
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1083 Read the subscription info from cache instead of DB
  svc-events/evcommon/common.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
  svc-events/events/subscriptionCache.go
  svc-events/events/subscriptionCache_test.go
Labels: prio:high, type:techdebt, status:in-progress

#1084 Cleanup and add all the log properties in systems service
  lib-utilities/common/constants.go
  svc-systems/chassis/create.go
  svc-systems/chassis/create_test.go
  svc-systems/chassis/delete.go
  svc-systems/chassis/delete_test.go
  svc-systems/chassis/fabric.go
  svc-systems/chassis/fabric_test.go
  svc-systems/chassis/fabricresource.go
  svc-systems/chassis/fabricresource_test.go
  svc-systems/chassis/get.go
  svc-systems/chassis/get_collection.go
  svc-systems/chassis/get_collection_test.go
  svc-systems/chassis/get_test.go
  svc-systems/chassis/getresource.go
  svc-systems/chassis/getresource_test.go
  svc-systems/chassis/update.go
  svc-systems/chassis/update_test.go
  svc-systems/chassis/updatefabricresource.go
  svc-systems/chassis/updatefabricresource_test.go
  svc-systems/main.go
  svc-systems/plugin/client.go
  svc-systems/plugin/client_mock.go
  svc-systems/plugin/client_test.go
  svc-systems/rpc/chassis.go
  svc-systems/rpc/chassis_test.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/rpc/wrapers.go
  svc-systems/rpc/wrapers_test.go
  svc-systems/scommon/common.go
  svc-systems/scommon/common_test.go
  svc-systems/smodel/fabrics.go
  svc-systems/smodel/fabrics_test.go
  svc-systems/smodel/systems.go
  svc-systems/smodel/systems_test.go
  svc-systems/systems/bootorder.go
  svc-systems/systems/bootorder_test.go
  svc-systems/systems/common.go
  svc-systems/systems/getresource.go
  svc-systems/systems/getresource_test.go
  svc-systems/systems/reset.go
  svc-systems/systems/reset_test.go
  svc-systems/systems/storage.go
  svc-systems/systems/storage_test.go
Labels: type:feature, prio:normal, status:in-progress

#1085 Updated the third party package versions
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1086 Updated apt-transport-https pkg version
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1087 Documented workaround for the nginx installation error
  docs/Troubleshooting.md
Labels: prio:normal, status:in-progress, type:doc

#1088 Use the models from lib-dmtf in event service
  lib-dmtf/model/events.go
  lib-utilities/common/constants.go
  svc-events/evcommon/common.go
  svc-events/evcommon/common_test.go
  svc-events/evcommon/mock.go
  svc-events/evcommon/mock_test.go
  svc-events/events/common.go
  svc-events/events/common_test.go
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription.go
  svc-events/events/evtsubscription_test.go
  svc-events/events/getevtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/submittestevent.go
  svc-events/events/subscriptionCache.go
  svc-events/events/subscriptionCache_test.go
  svc-events/evmodel/events.go
  svc-events/evmodel/events_test.go
  svc-events/evresponse/events.go
  svc-events/rpc/events_test.go
Labels: type:techdebt, prio:low, status:in-progress

#1089 Add all log properties in telemetry service
  lib-utilities/common/constants.go
  svc-telemetry/rpc/common.go
  svc-telemetry/rpc/common_test.go
  svc-telemetry/rpc/telemetry.go
  svc-telemetry/rpc/telemetry_test.go
  svc-telemetry/tcommon/common.go
  svc-telemetry/tcommon/common_test.go
  svc-telemetry/telemetry/common.go
  svc-telemetry/telemetry/telemetry.go
  svc-telemetry/telemetry/telemetry_test.go
  svc-telemetry/tmodel/model.go
  svc-telemetry/tmodel/model_test.go
Labels: type:feature, prio:normal, status:in-progress

#1090 Add all log properties in Licenses service
  lib-utilities/common/constants.go
  svc-licenses/lcommon/common.go
  svc-licenses/licenses/common.go
  svc-licenses/licenses/common_test.go
  svc-licenses/licenses/licenses.go
  svc-licenses/licenses/licenses_test.go
  svc-licenses/rpc/common.go
  svc-licenses/rpc/licenses.go
  svc-licenses/rpc/licenses_test.go
Labels: type:feature, prio:normal, status:in-progress

#1091 Fixing the code scanning issue for log fields
  lib-utilities/logs/logging.go
Labels: prio:normal

#1093 Add all the log properties in fabrics service
  lib-utilities/common/constants.go
  svc-fabrics/fabrics/addfabric.go
  svc-fabrics/fabrics/addfabric_test.go
  svc-fabrics/fabrics/common.go
  svc-fabrics/fabrics/common_test.go
  svc-fabrics/fabrics/createresource.go
  svc-fabrics/fabrics/createresource_test.go
  svc-fabrics/fabrics/deleteresource.go
  svc-fabrics/fabrics/deleteresource_test.go
  svc-fabrics/fabrics/getresource.go
  svc-fabrics/fabrics/getresource_test.go
  svc-fabrics/fabrics/removefabric.go
  svc-fabrics/fabrics/removefabric_test.go
  svc-fabrics/rpc/fabrics.go
  svc-fabrics/rpc/fabrics_test.go
Labels: type:feature, prio:normal, status:in-progress

#1096 Fix the security issue of directly printing the logs
  lib-utilities/logs/logger.go
Labels: type:bug

#1095 Upgrade golang version to 1.19.5
  .github/workflows/build_unittest.yml
  .github/workflows/odimra_deployment.yml
  build/odimra/Dockerfile.builddep
  install/Docker/dockerfiles/Dockerfile.odim
  install/Docker/dockerfiles/scripts/add-hosts/go.mod
  install/Docker/dockerfiles/scripts/add-hosts/go.sum
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-messagebus/go.mod
  lib-messagebus/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/persistencemgr/redis_test.go
  lib-rest-client/go.mod
  lib-rest-client/go.sum
  lib-utilities/go.mod
  lib-utilities/go.sum
  odim-controller/scripts/go.mod
  odim-controller/scripts/setup_deployment_node.sh
  plugin-dell/go.mod
  plugin-dell/go.sum
  plugin-lenovo/go.mod
  plugin-lenovo/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  plugin-unmanaged-racks/go.mod
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-licenses/go.mod
  svc-licenses/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-telemetry/go.mod
  svc-telemetry/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: type:feature, prio:normal, status:in-progress
