Repository ODIM-Project/ODIM, pull requests merged in 2023-08, with the labels that each got.

#1281 Odim-7754: Fixed issue with nil values in aggregation log
  svc-aggregation/system/addaggregationsource.go
Labels: prio:normal

#1282 Adding the missing parameter in dell configmap
  odim-controller/helmcharts/dellplugin/dellplugin-config.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
Labels: type:bug, prio:normal, status:in-progress

#1284 upgrade docker image versions and helm packages version of the services and plugin
  build_images.sh
  docker-images.sh
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.compositionService
  install/Docker/dockerfiles/Dockerfile.dellplugin
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.lenovoplugin
  install/Docker/dockerfiles/Dockerfile.licenses
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.telemetry
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/Dockerfile.urplugin
  odim-controller/helmcharts/account-session/Chart.yaml
  odim-controller/helmcharts/account-session/values.yaml
  odim-controller/helmcharts/aggregation/Chart.yaml
  odim-controller/helmcharts/aggregation/values.yaml
  odim-controller/helmcharts/api/Chart.yaml
  odim-controller/helmcharts/api/values.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/Chart.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/values.yaml
  odim-controller/helmcharts/events/Chart.yaml
  odim-controller/helmcharts/events/values.yaml
  odim-controller/helmcharts/fabrics/Chart.yaml
  odim-controller/helmcharts/fabrics/values.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/Chart.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/values.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/Chart.yaml
  odim-controller/helmcharts/lenovoplugin/lenovoplugin/values.yaml
  odim-controller/helmcharts/licenses/Chart.yaml
  odim-controller/helmcharts/licenses/values.yaml
  odim-controller/helmcharts/managers/Chart.yaml
  odim-controller/helmcharts/managers/values.yaml
  odim-controller/helmcharts/systems/Chart.yaml
  odim-controller/helmcharts/systems/values.yaml
  odim-controller/helmcharts/task/Chart.yaml
  odim-controller/helmcharts/task/values.yaml
  odim-controller/helmcharts/telemetry/Chart.yaml
  odim-controller/helmcharts/telemetry/values.yaml
  odim-controller/helmcharts/update/Chart.yaml
  odim-controller/helmcharts/update/values.yaml
  odim-controller/helmcharts/urplugin/urplugin/Chart.yaml
  odim-controller/helmcharts/urplugin/urplugin/values.yaml
  odim-controller/odimra/group_vars/all/all.yaml
Labels: type:techdebt, prio:normal, status:in-progress

#1283 Getting Started doc updates for the release
  README.md
  docs/images/odimra_images.png
Labels: prio:normal, status:in-progress, type:doc

#1285 Odim 7598:Adding the sigint and sigkill signal handle during application termination
  lib-utilities/services/rpcService.go
  svc-aggregation/system/rediscoverinventory.go
Labels: type:bug, prio:normal, status:in-progress

#1287 Validated older sections in the GS readme and updated them
  README.md
  docs/images/kubernetes_images.png
  docs/images/odimra_images.png
Labels: prio:normal, status:in-progress, type:doc

#1286 fixed location header in taskmon while creating event subscription
  lib-utilities/common/generalerror.go
  lib-utilities/proto/task/task.proto
  svc-events/events/common.go
  svc-events/events/evtsubscription.go
  svc-events/go.mod
  svc-task/go.mod
  svc-task/tcommon/common.go
  svc-task/thandle/thandle.go
  svc-task/thandle/tmonitor_test.go
  svc-task/tmodel/tmodel.go
Labels: type:bug, prio:normal, status:in-progress

#1288 Removing extra tabs in dell-plugin config
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
Labels: type:bug, prio:high, status:in-progress

#1289 Fixed taskmon status for event subscription creation while no server added
  svc-events/events/evtsubscription.go
Labels: type:bug, prio:normal, status:in-progress

#1290 Removing duplicate parameter and removing fmt statements
  odim-controller/helmcharts/dellplugin/dellplugin/templates/configmaps.yaml
  plugin-dell/dphandler/subscribeEvents.go
  svc-aggregation/rpc/aggregator.go
  svc-systems/systems/getresource.go
Labels: type:bug, prio:normal, status:in-progress

#1292 Address team feedback for event subscription property in request body
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1293 odim 7948:Updating failover scenario of redis during secret update
  install/Docker/dockerfiles/scripts/redis-entrypointsetup.sh
Labels: type:bug, prio:high, status:in-progress

#1296 Updated third party pkg versions as per team feedback in GS readme
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1295 Updated sections of account service, computer systems and managers
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1298 svc folder readmes and plugin readmes - Italicized all references and links as per HPE style guide
  plugin-dell/README.md
  plugin-lenovo/README.md
  plugin-redfish/README.md
  plugin-unmanaged-racks/README.md
  svc-aggregation/README.md
Labels: prio:normal, status:in-progress, type:doc

#1300 Odim phase7 docs release tasks
  README.md
  docs/README.md
  docs/Troubleshooting.md
  plugin-dell/README.md
  plugin-lenovo/README.md
  plugin-redfish/README.md
  plugin-unmanaged-racks/README.md
  svc-account-session/README.md
  svc-account-session/UserAccounts.md
  svc-aggregation/README.md
  svc-events/README.md
  svc-fabrics/README.md
  svc-licenses/README.md
  svc-managers/README.md
  svc-systems/README.md
  svc-task/README.md
  svc-telemetry/README.md
  svc-update/README.md
Labels: prio:normal, status:in-progress, type:doc
