Repository ODIM-Project/ODIM, pull requests merged in 2023-03, with the labels that each got.

#1150 updated connectionmethod variant versions for dell and lenovo + updated backup restore instructions for Redis
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1155 Cleanup and add new logs in update service
  svc-update/rpc/common.go
  svc-update/rpc/update.go
  svc-update/rpc/update_test.go
  svc-update/ucommon/common.go
  svc-update/umodel/update.go
  svc-update/update/common.go
  svc-update/update/getresources.go
  svc-update/update/getresources_test.go
  svc-update/update/simpleUpdate.go
  svc-update/update/startUpdate.go
  svc-update/update/startUpdate_test.go
Labels: type:feature, prio:normal, status:in-progress

#1156 Cleanup logs and add debug logs in telemetry service
  svc-telemetry/rpc/common_test.go
  svc-telemetry/rpc/telemetry.go
  svc-telemetry/tcommon/common.go
  svc-telemetry/tcommon/common_test.go
  svc-telemetry/telemetry/common.go
  svc-telemetry/telemetry/mockTelemetry.go
  svc-telemetry/telemetry/telemetry.go
  svc-telemetry/telemetry/telemetry_test.go
  svc-telemetry/tmodel/model.go
  svc-telemetry/tmodel/model_test.go
Labels: type:feature, prio:normal, status:in-progress

#1158 Implement tasks on BMC accounts - create, delete and update
  lib-utilities/common/constants.go
  lib-utilities/services/pluginTask.go
  svc-managers/main.go
  svc-managers/managers/common.go
  svc-managers/managers/common_test.go
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrcommon/common.go
  svc-managers/mgrcommon/common_test.go
  svc-managers/mgrmodel/manager.go
  svc-managers/mgrmodel/manager_test.go
  svc-managers/rpc/manager.go
  svc-managers/rpc/manager_test.go
  svc-systems/systems/bootorder.go
  svc-systems/systems/bootorder_test.go
  svc-task/tcommon/common.go
  svc-task/thandle/thandle.go
  svc-task/thandle/tpolling.go
  svc-task/tmessagebus/consume.go
  svc-task/tmodel/tmodel.go
Labels: type:feature, prio:normal, status:in-progress

#1157 Implement tasks for update service
  lib-persistence-manager/persistencemgr/redis.go
  svc-task/main.go
  svc-task/tauth/tauth.go
  svc-task/thandle/thandle.go
  svc-task/thandle/thandle_test.go
  svc-task/thandle/tmonitor.go
  svc-task/thandle/tmonitor_test.go
  svc-task/thandle/tpolling.go
  svc-task/tmessagebus/consume.go
  svc-task/tmessagebus/publish.go
  svc-task/tmodel/plugin.go
  svc-task/tmodel/tmodel.go
  svc-task/tqueue/queue_test.go
  svc-task/tresponse/error.go
  svc-task/tresponse/task.go
  svc-update/main.go
  svc-update/ucommon/common.go
  svc-update/ucommon/common_test.go
  svc-update/update/common.go
  svc-update/update/getresources_test.go
  svc-update/update/simpleUpdate.go
  svc-update/update/simpleUpdate_test.go
  svc-update/update/startUpdate.go
Labels: type:feature, prio:normal, status:in-progress

#1160 Cleanup event service code for incoming events and publishing
  lib-persistence-manager/persistencemgr/redis.go
  lib-utilities/common/dbconn.go
  lib-utilities/common/generalerror.go
  lib-utilities/common/mockconfig.go
  lib-utilities/common/workerpool.go
  lib-utilities/config/README.md
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/constants.go
  lib-utilities/config/mockconfig.go
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-config/values.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  svc-aggregation/agcommon/common.go
  svc-aggregation/system/pluginHealthCheck.go
  svc-composition-service/app/config/config_test.py
  svc-events/evcommon/common.go
  svc-events/evcommon/mock.go
  svc-events/events/common.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
  svc-events/events/subscriptionCache.go
  svc-events/events/subscriptionCache_test.go
  svc-events/evmodel/events.go
  svc-events/evmodel/events_test.go
  svc-events/main.go
  svc-events/rpc/events.go
Labels: prio:high, type:techdebt, status:in-progress

#1161 Implement tasks for insert and eject virtual media
  svc-managers/managers/managers.go
  svc-managers/managers/managers_test.go
  svc-managers/mgrmodel/device.go
  svc-managers/mgrresponse/managers.go
  svc-managers/mgrresponse/rpc.go
  svc-managers/rpc/manager.go
  svc-managers/rpc/manager_test.go
Labels: type:feature, prio:normal, status:in-progress

#1159 Added cleanup logs and debug logs in aggregation & fabrics service
  svc-aggregation/agcommon/common.go
  svc-aggregation/agcommon/common_test.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/agmodel/system_test.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/addplugin_test.go
  svc-aggregation/system/aggregate.go
  svc-aggregation/system/bootorder.go
  svc-aggregation/system/common.go
  svc-aggregation/system/connectionmethods.go
  svc-aggregation/system/connectionmethods_test.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-aggregation/system/get_resource.go
  svc-aggregation/system/get_resource_test.go
  svc-aggregation/system/pluginHealthCheck.go
  svc-aggregation/system/rediscoverinventory.go
  svc-aggregation/system/rediscoverinventory_test.go
  svc-aggregation/system/reset.go
  svc-aggregation/system/systemstate.go
  svc-aggregation/system/update.go
Labels: type:feature, prio:normal, status:in-progress

#1162 Fixing Message consumptions from Redis Stream
  lib-messagebus/datacommunicator/redisstreamcomm.go
Labels: type:bug, prio:high, status:in-progress

#1163 Implemented tasks for update service - start update
  svc-update/update/simpleUpdate.go
  svc-update/update/startUpdate.go
  svc-update/update/startUpdate_test.go
Labels: type:feature, prio:normal, status:in-progress

#1165 Added task support for install license API
  lib-utilities/common/constants.go
  svc-licenses/lcommon/common.go
  svc-licenses/licenses/common.go
  svc-licenses/licenses/common_test.go
  svc-licenses/licenses/licenses.go
  svc-licenses/licenses/licenses_test.go
  svc-licenses/rpc/common.go
  svc-licenses/rpc/licenses.go
  svc-licenses/rpc/licenses_test.go
  svc-task/thandle/thandle.go
Labels: type:feature, prio:normal, status:in-progress

#1168 Removing the extra spaces between the log properties
  lib-utilities/logs/logger.go
Labels: type:bug, prio:normal, status:in-progress

#1112 Added caching in event service
  build/Redis/createschema.sh
  install/Docker/dockerfiles/scripts/add-hosts/add-hosts.go
  install/Docker/dockerfiles/scripts/redis-createschema.sh
  lib-dmtf/model/events.go
  lib-persistence-manager/persistencemgr/redis.go
  lib-utilities/common/constants.go
  lib-utilities/common/dbconn.go
  lib-utilities/common/generalerror.go
  lib-utilities/common/mockconfig.go
  lib-utilities/common/workerpool.go
  lib-utilities/common/workerpool_test.go
  lib-utilities/config/README.md
  lib-utilities/config/config.go
  lib-utilities/config/config_test.go
  lib-utilities/config/constants.go
  lib-utilities/config/mockconfig.go
  lib-utilities/config/odimra_config.json
  odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
  odim-controller/helmcharts/odimra-config/values.yaml
  odim-controller/scripts/kube_deploy_nodes.yaml.tmpl
  plugin-dell/dpmessagebus/publish.go
  plugin-dell/main.go
  plugin-lenovo/lpmessagebus/publish.go
  plugin-lenovo/main.go
  plugin-redfish/main.go
  plugin-redfish/rfpmessagebus/publish.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/system/pluginHealthCheck.go
  svc-composition-service/app/config/config_test.py
  svc-events/consumer/consumer.go
  svc-events/evcommon/common.go
  svc-events/evcommon/common_test.go
  svc-events/evcommon/mock.go
  svc-events/evcommon/mock_test.go
  svc-events/events/common.go
  svc-events/events/common_test.go
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription.go
  svc-events/events/evtsubscription_test.go
  svc-events/events/getevtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/publishevttosubscriber_test.go
  svc-events/events/submittestevent.go
  svc-events/events/submittestevent_test.go
  svc-events/events/subscriptionCache.go
  svc-events/events/subscriptionCache_test.go
  svc-events/evmodel/events.go
  svc-events/evmodel/events_test.go
  svc-events/evresponse/events.go
  svc-events/go.mod
  svc-events/main.go
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
Labels: prio:high, type:techdebt, status:in-progress

#1171 Event subscription Get and Add request optimized and clean up
  lib-utilities/common/constants.go
  lib-utilities/services/task.go
  svc-events/consumer/consumer.go
  svc-events/events/common.go
  svc-events/events/common_test.go
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription.go
  svc-events/events/evtsubscription_test.go
  svc-events/events/getevtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/subscriptionCache.go
  svc-events/evmodel/events.go
  svc-events/rpc/events.go
Labels: type:techdebt, prio:normal, status:in-progress

#1176 Adding debug logs to the svc-api
  svc-api/handle/account.go
  svc-api/handle/aggregator.go
  svc-api/handle/chassis.go
  svc-api/handle/events.go
  svc-api/handle/fabrics.go
  svc-api/handle/handlers.go
  svc-api/handle/licenses.go
  svc-api/handle/managers.go
  svc-api/handle/role.go
  svc-api/handle/sessions.go
  svc-api/handle/systems.go
  svc-api/handle/task.go
  svc-api/handle/telemetry.go
  svc-api/handle/update.go
  svc-api/router/router.go
Labels: type:feature, prio:normal, status:in-progress

#1178 Fixing the Method name for Taskmon URI in Log properties
  lib-utilities/common/constants.go
  svc-api/main.go
Labels: type:bug, prio:normal, status:in-progress

#1177 Removing unnecessary logs from ODIM services
  svc-account-session/rpc/account.go
  svc-account-session/rpc/auth.go
  svc-account-session/rpc/role.go
  svc-account-session/rpc/sessions.go
  svc-api/handle/systems.go
  svc-api/router/router.go
  svc-managers/rpc/manager.go
  svc-systems/chassis/fabric.go
  svc-systems/chassis/fabricresource.go
  svc-systems/chassis/get.go
  svc-systems/chassis/getresource.go
  svc-systems/chassis/update.go
  svc-systems/chassis/updatefabricresource.go
  svc-systems/rpc/systems.go
  svc-systems/systems/getresource.go
Labels: type:bug, prio:normal, status:in-progress

#1175 Fixing all the nil logging parameters occurred during auth check
  lib-utilities/logService/common.go
  lib-utilities/logs/logging.go
  lib-utilities/services/auth.go
  lib-utilities/services/eventsubscription.go
  svc-aggregation/main.go
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/common.go
  svc-aggregation/system/reset_test.go
  svc-api/handle/handlers.go
  svc-api/handle/handlers_test.go
  svc-events/evcommon/mock.go
  svc-events/evcommon/mock_test.go
  svc-events/events/common.go
  svc-events/events/deletesubscription.go
  svc-events/events/evtsubscription_test.go
  svc-events/events/getevtsubscription.go
  svc-events/events/getevtsubscription_test.go
  svc-events/events/submittestevent.go
  svc-events/events/submittestevent_test.go
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
  svc-fabrics/fabrics/common.go
  svc-fabrics/fabrics/createresource_test.go
  svc-fabrics/rpc/fabrics.go
  svc-fabrics/rpc/fabrics_test.go
  svc-licenses/licenses/common.go
  svc-licenses/licenses/common_test.go
  svc-licenses/rpc/licenses.go
  svc-licenses/rpc/licenses_test.go
  svc-managers/main.go
  svc-managers/rpc/manager.go
  svc-managers/rpc/manager_test.go
  svc-systems/rpc/chassis.go
  svc-systems/rpc/chassis_test.go
  svc-systems/rpc/systems.go
  svc-systems/rpc/systems_test.go
  svc-systems/rpc/wrapers.go
  svc-systems/rpc/wrapers_test.go
  svc-task/tauth/tauth.go
  svc-task/thandle/thandle.go
  svc-task/thandle/tmonitor.go
  svc-task/thandle/tmonitor_test.go
  svc-telemetry/main.go
  svc-telemetry/rpc/telemetry.go
  svc-telemetry/telemetry/common.go
  svc-telemetry/telemetry/mockTelemetry.go
  svc-update/rpc/update.go
  svc-update/rpc/update_test.go
  svc-update/update/common.go
  svc-update/update/getresources_test.go
Labels: type:bug, prio:normal, status:in-progress

#1169 Added debug logs in license service
  svc-licenses/lcommon/common.go
  svc-licenses/licenses/common.go
  svc-licenses/licenses/common_test.go
  svc-licenses/licenses/licenses.go
  svc-licenses/rpc/licenses.go
  svc-licenses/rpc/licenses_test.go
Labels: type:feature, prio:normal, status:in-progress

#1172 Cleanup logs and add debug logs in events service
  lib-utilities/common/pluginstatus.go
  lib-utilities/common/pluginstatus_test.go
  lib-utilities/proto/events/events.proto
  lib-utilities/services/eventsubscription.go
  svc-aggregation/agcommon/common.go
  svc-api/rpc/fakeStruct_testfile.go
  svc-events/consumer/consumer.go
  svc-events/consumer/consumer_test.go
  svc-events/evcommon/common.go
  svc-events/evcommon/mock.go
  svc-events/evcommon/mock_test.go
  svc-events/events/common.go
  svc-events/events/deletesubscription.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
  svc-events/events/submittestevent.go
  svc-events/events/subscriptionCache.go
  svc-events/events/subscriptionCache_test.go
  svc-events/evmodel/events.go
  svc-events/evresponse/errorResponse.go
  svc-events/evresponse/errorResponse_test.go
  svc-events/evresponse/events.go
  svc-events/evresponse/rpc.go
  svc-events/main.go
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
  svc-licenses/lcommon/common.go
  svc-managers/mgrcommon/common.go
  svc-systems/scommon/common.go
  svc-telemetry/tcommon/common.go
  svc-update/ucommon/common.go
Labels: type:techdebt, prio:normal, status:in-progress

#1182 Fixed panic error in change bios setting while updating task with error
  svc-systems/systems/bootorder.go
Labels: type:bug, prio:normal, status:in-progress

#1184 Fixing the nil parameters in logging during internal RPC calls
  lib-utilities/services/auth.go
  lib-utilities/services/eventsubscription.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-events/events/publishevttosubscriber.go
Labels: type:bug, prio:normal, status:in-progress

#1174 Added debug logs for fabrics service
  svc-fabrics/fabmodel/fabrics.go
  svc-fabrics/fabmodel/fabrics_test.go
  svc-fabrics/fabrics/addfabric.go
  svc-fabrics/fabrics/addfabric_test.go
  svc-fabrics/fabrics/common.go
  svc-fabrics/fabrics/removefabric.go
  svc-fabrics/rpc/fabrics.go
Labels: type:feature, prio:normal, status:in-progress

#1183 Upgraded third party packages to resolve GitHub vulnerabilities.
  install/Docker/dockerfiles/scripts/add-hosts/go.mod
  install/Docker/dockerfiles/scripts/add-hosts/go.sum
  lib-dmtf/go.mod
  lib-dmtf/go.sum
  lib-messagebus/go.mod
  lib-messagebus/go.sum
  lib-persistence-manager/go.mod
  lib-persistence-manager/go.sum
  lib-rest-client/go.mod
  lib-rest-client/go.sum
  lib-utilities/go.mod
  lib-utilities/go.sum
  odim-controller/scripts/go.mod
  odim-controller/scripts/go.sum
  plugin-dell/go.mod
  plugin-dell/go.sum
  plugin-lenovo/go.mod
  plugin-lenovo/go.sum
  plugin-redfish/go.mod
  plugin-redfish/go.sum
  plugin-unmanaged-racks/go.mod
  plugin-unmanaged-racks/go.sum
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-aggregation/go.mod
  svc-aggregation/go.sum
  svc-api/go.mod
  svc-api/go.sum
  svc-api/handle/chassis_test.go
  svc-api/handle/handlers_test.go
  svc-events/go.mod
  svc-events/go.sum
  svc-fabrics/go.mod
  svc-fabrics/go.sum
  svc-licenses/go.mod
  svc-licenses/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
  svc-task/go.mod
  svc-task/go.sum
  svc-telemetry/go.mod
  svc-telemetry/go.sum
  svc-update/go.mod
  svc-update/go.sum
Labels: type:bug, prio:high, status:in-progress

#1181 Fixing the nil parameter for logging while create aggregates.
  svc-aggregation/rpc/aggregator.go
Labels: type:bug, prio:normal, status:in-progress

#1187 fixed aggregate reset returns success for negative cases
  svc-aggregation/system/common.go
Labels: type:feature, prio:normal, status:in-progress

#1190 Fixed server addition task percentage update is stuck at middle of the execution
  svc-aggregation/system/addaggregationsource.go
  svc-aggregation/system/common.go
Labels: type:bug, prio:normal, status:in-progress

#1188 Removing go.sed dependency as it requires GPL licenses
  svc-account-session/go.mod
  svc-account-session/go.sum
  svc-events/go.mod
  svc-events/go.sum
  svc-managers/go.mod
  svc-managers/go.sum
  svc-systems/go.mod
  svc-systems/go.sum
Labels: type:bug, prio:high, status:in-progress

#1191 Create default subscription when all subscriptions are deleted
  svc-events/events/deletesubscription.go
Labels: type:bug, prio:normal, status:in-progress
