Repository ODIM-Project/ODIM, pull requests merged in 2023-09, with the labels that each got.

#1291 Fixed event subscription creation for mutiple origin resource with same system and different resources type
  svc-events/events/common.go
  svc-events/events/evtsubscription.go
  svc-events/events/publishevttosubscriber.go
Labels: type:bug, prio:low, status:in-progress

#1304 Odim 7033
  lib-dmtf/model/Chassis_test.go
  lib-dmtf/model/ComputerSystem_test.go
  lib-utilities/common/constants.go
  lib-utilities/etc/Base.1.16.0.json
  lib-utilities/etc/Composition.1.1.1.json
  lib-utilities/etc/EthernetFabric.1.0.0.json
  lib-utilities/etc/Fabric.1.0.0.json
  lib-utilities/etc/JobEvent.1.0.0.json
  lib-utilities/etc/License.1.0.2.json
  lib-utilities/etc/LogService.1.0.0.json
  lib-utilities/etc/NetworkDevice.1.0.2.json
  lib-utilities/etc/Redfish_1.4.0_PrivilegeRegistry.json
  lib-utilities/etc/ResouceEvent1.3.0.json
  lib-utilities/etc/StorageDevice.1.1.0.json
  lib-utilities/etc/TaskEvent.1.0.3.json
  lib-utilities/etc/Update.1.0.1.json
  plugin-redfish/rfphandler/managers.go
  plugin-redfish/rfphandler/metricreport_test.go
  plugin-unmanaged-racks/redfish/chassis.go
  plugin-unmanaged-racks/rest/get_manager_handler.go
  svc-account-session/UserAccounts.md
  svc-aggregation/system/addplugin.go
  svc-aggregation/system/connectionmethods.go
  svc-api/handle/aggregator_test.go
  svc-api/handle/handlers.go
  svc-api/handle/handlers_test.go
  svc-licenses/licenses/licenses.go
  svc-licenses/licenses/licenses_test.go
  svc-managers/main.go
  svc-systems/chassis/create_test.go
  svc-systems/chassis/delete_test.go
  svc-systems/chassis/update_test.go
  svc-systems/systems/getresource.go
  svc-telemetry/tcommon/common_test.go
  svc-telemetry/telemetry/mockTelemetry.go
Labels: type:feature, prio:normal, status:in-progress

#1306 Update Models in lib-dmtf
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/ComputerSystem.go
  lib-dmtf/model/Links.go
  lib-dmtf/model/accountService.go
  lib-dmtf/model/endpoint.go
  lib-dmtf/model/events.go
  lib-dmtf/model/port.go
  lib-dmtf/model/serviceRoot.go
  lib-dmtf/model/storage.go
Labels: type:feature, prio:normal

#1307 Updating the kubespray version to 2.22.1
  .github/workflows/odimra_deployment.yml
  odim-controller/kubespray/kubespray-2.20.0.tar.gz
  odim-controller/kubespray/kubespray-2.22.1.tar.gz
Labels: prio:high, type:feature, status:in-progress

#1302 Implemented subtasks for delete event subscription
  lib-utilities/proto/events/events.proto
  lib-utilities/services/eventsubscription.go
  lib-utilities/services/pluginTask.go
  svc-aggregation/agmessagebus/publish_test.go
  svc-aggregation/go.mod
  svc-aggregation/rpc/aggregator.go
  svc-aggregation/rpc/common.go
  svc-aggregation/rpc/common_test.go
  svc-aggregation/system/addaggregationsource_test.go
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/common.go
  svc-aggregation/system/deleteaggregationsource.go
  svc-aggregation/system/deleteaggregationsource_test.go
  svc-api/rpc/fakeStruct_testfile.go
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription.go
  svc-events/evresponse/events_test.go
  svc-events/rpc/common.go
  svc-events/rpc/events.go
  svc-events/rpc/events_test.go
  svc-task/tcommon/common.go
  svc-task/thandle/thandle.go
Labels: type:techdebt, prio:normal, status:in-progress

#1305 Changed the status code from 500 to 404 for ODIM and Plugin manager if data is not present in the system
  build_images.sh
  svc-managers/managers/managers.go
Labels: type:bug, prio:normal, status:in-progress

#1309 Adding new schema properties
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/ComputerSystem.go
  lib-dmtf/model/Links.go
  lib-dmtf/model/accountService.go
  lib-dmtf/model/endpoint.go
  lib-dmtf/model/events.go
  lib-dmtf/model/port.go
  lib-dmtf/model/serviceRoot.go
  lib-dmtf/model/storage.go
Labels: type:feature, prio:normal, status:in-progress

#1311 Changes in svc-events for ServerPostDiscoveryComplete
  svc-events/events/publishevttosubscriber.go
Labels: type:feature, prio:normal, status:in-progress

#1312 Fixed volume delete bug
  svc-aggregation/agcommon/common.go
  svc-aggregation/system/common.go
  svc-aggregation/system/rediscoverinventory.go
  svc-events/events/publishevttosubscriber.go
Labels: type:bug, prio:normal, status:in-progress

#1310 Fixed event pod crashing
  plugin-dell/dpmessagebus/publish.go
  plugin-dell/go.mod
  svc-aggregation/agcommon/common.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/system/pluginHealthCheck.go
Labels: type:bug, prio:normal, status:in-progress

#1313 Fixed wrong status update while simple update url is invalid
  svc-task/thandle/thandle.go
  svc-task/tmodel/tmodel.go
Labels: type:bug, prio:normal, status:in-progress

#1314 fixed OData.Id invalid path issue while add account
  svc-managers/managers/managers.go
  svc-task/thandle/thandle.go
  svc-task/tmodel/tmodel.go
Labels: type:bug, prio:normal, status:in-progress

#1316 Replace master with primary in all occurrences of scripts
  install/Docker/dockerfiles/Dockerfile.redis
  install/Docker/dockerfiles/scripts/redis-checkdb.sh
  install/Docker/dockerfiles/scripts/redis-createschema.sh
  install/Docker/dockerfiles/scripts/redis-entrypointsetup.sh
  install/Docker/dockerfiles/scripts/redis-primary.conf
  install/Docker/dockerfiles/scripts/redis-secondary.conf
  lib-persistence-manager/persistencemgr/config.go
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-sentinel-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-inmemory-sentinel-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-sentinel-primary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/templates/redis-ha-ondisk-sentinel-secondary-statefulset.yaml
  odim-controller/helmcharts/redis-ha/values.yaml
  odim-controller/helmcharts/redis/templates/redis-ondisk-statefulset.yaml
  odim-controller/helmcharts/urplugin/urplugin/templates/configmaps.yaml
  odim-controller/helmcharts/urplugin/urplugin/values.yaml
  odim-controller/odimra/roles/configure-keepalived/templates/action_script.sh.j2
  odim-controller/odimra/roles/configure-keepalived/templates/keepalived.conf.j2
  odim-controller/scripts/odim-controller.py
  plugin-unmanaged-racks/config/config.go
  plugin-unmanaged-racks/config/config.yml
  plugin-unmanaged-racks/db/persistence.go
  plugin-unmanaged-racks/go.sum
  plugin-unmanaged-racks/rest/module.go
Labels: type:feature, prio:normal, status:in-progress

#1318 Updating the redis instance name in redis-in-memory
  odim-controller/helmcharts/redis/templates/redis-inmemory-statefulset.yaml
Labels: type:bug, prio:normal, status:in-progress

#1317 Fixed subtask id creation in odim
  svc-events/events/deletesubscription.go
  svc-events/events/evtsubscription.go
Labels: type:bug, prio:normal, status:in-progress
