Repository ODIM-Project/ODIM, pull requests merged in 2023-06, with the labels that each got.

#1240 Add info on logsOnConsole for odim and plugins
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1241 Add new secureboot APIs and update the latest event subscription response code
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1244 Fixed major consistency issues in API readme
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1239 Upgrading Kafka and zookeeper version to the latest
  build/Kafka/Dockerfiles/Dockerfile.kafka
  build/Kafka/Dockerfiles/Dockerfile.zookeeper
  build/docker-compose.yml
  build_images.sh
  docker-images.sh
  install/Docker/dockerfiles/Dockerfile.kafka
  install/Docker/dockerfiles/Dockerfile.zookeeper
  odim-controller/helmcharts/kafka-ha/Chart.yaml
  odim-controller/helmcharts/kafka-ha/values.yaml
  odim-controller/helmcharts/kafka-secret/Chart.yaml
  odim-controller/helmcharts/kafka/Chart.yaml
  odim-controller/helmcharts/kafka/templates/_helpers.tpl
  odim-controller/helmcharts/kafka/values.yaml
  odim-controller/helmcharts/zookeeper-ha/Chart.yaml
  odim-controller/helmcharts/zookeeper-ha/values.yaml
  odim-controller/helmcharts/zookeeper-secret/Chart.yaml
  odim-controller/helmcharts/zookeeper/Chart.yaml
  odim-controller/helmcharts/zookeeper/templates/_helpers.tpl
  odim-controller/helmcharts/zookeeper/values.yaml
  odim-controller/odimra/group_vars/all/all.yaml
Labels: type:feature, prio:normal, status:in-progress

#1245 Updated phase 6 downstream content in phase 7 upstream docs to be in sync + minor fixes
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1242 Resolve code smell issues
  lib-messagebus/datacommunicator/config.go
  lib-messagebus/datacommunicator/header_test.go
  lib-messagebus/datacommunicator/kafkacomm_test.go
  lib-messagebus/datacommunicator/redisstreamcomm.go
  lib-persistence-manager/persistencemgr/config.go
  lib-persistence-manager/persistencemgr/redis.go
  lib-persistence-manager/persistencemgr/redis_test.go
  lib-persistence-manager/persistencemgr/unit_test_db_confighelp.go
  lib-persistence-manager/persistencemgr/unit_test_db_confighelp_test.go
  lib-utilities/common/caseValidator.go
  lib-utilities/common/constants.go
  lib-utilities/common/trackconfig.go
  lib-utilities/config/config.go
  lib-utilities/logs/logger.go
  lib-utilities/services/auth.go
  lib-utilities/services/rpcService.go
Labels: type:techdebt, prio:low, status:in-progress

#1250 Improved performance for handling multiple computer system resets.
  lib-persistence-manager/persistencemgr/redis.go
  svc-aggregation/agcommon/common.go
  svc-aggregation/agmodel/system.go
  svc-aggregation/system/common.go
  svc-aggregation/system/rediscoverinventory.go
Labels: prio:normal

#1243 Fixed invalid status code for error responses from plugins
  svc-systems/scommon/common.go
  svc-systems/systems/bootorder.go
  svc-systems/systems/secureBoot.go
  svc-systems/systems/storage.go
Labels: type:feature, prio:normal, status:in-progress

#1252 upgrade docker image versions and helm packages version of the services and plugin
  build_images.sh
  docker-images.sh
  install/Docker/dockerfiles/Dockerfile.accountSession
  install/Docker/dockerfiles/Dockerfile.aggregation
  install/Docker/dockerfiles/Dockerfile.api
  install/Docker/dockerfiles/Dockerfile.compositionService
  install/Docker/dockerfiles/Dockerfile.dellplugin
  install/Docker/dockerfiles/Dockerfile.events
  install/Docker/dockerfiles/Dockerfile.fabrics
  install/Docker/dockerfiles/Dockerfile.grfplugin
  install/Docker/dockerfiles/Dockerfile.lenovoplugin
  install/Docker/dockerfiles/Dockerfile.licenses
  install/Docker/dockerfiles/Dockerfile.managers
  install/Docker/dockerfiles/Dockerfile.systems
  install/Docker/dockerfiles/Dockerfile.task
  install/Docker/dockerfiles/Dockerfile.telemetry
  install/Docker/dockerfiles/Dockerfile.update
  install/Docker/dockerfiles/Dockerfile.urplugin
  odim-controller/helmcharts/aggregation/Chart.yaml
  odim-controller/helmcharts/aggregation/values.yaml
  odim-controller/helmcharts/api/Chart.yaml
  odim-controller/helmcharts/api/values.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/Chart.yaml
  odim-controller/helmcharts/dellplugin/dellplugin/values.yaml
  odim-controller/helmcharts/events/Chart.yaml
  odim-controller/helmcharts/events/values.yaml
  odim-controller/helmcharts/fabrics/Chart.yaml
  odim-controller/helmcharts/fabrics/values.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/Chart.yaml
  odim-controller/helmcharts/grfplugin/grfplugin/values.yaml
  odim-controller/helmcharts/licenses/Chart.yaml
  odim-controller/helmcharts/licenses/values.yaml
  odim-controller/helmcharts/managers/Chart.yaml
  odim-controller/helmcharts/managers/values.yaml
  odim-controller/helmcharts/systems/Chart.yaml
  odim-controller/helmcharts/systems/values.yaml
  odim-controller/helmcharts/task/Chart.yaml
  odim-controller/helmcharts/task/values.yaml
  odim-controller/helmcharts/telemetry/Chart.yaml
  odim-controller/helmcharts/telemetry/values.yaml
  odim-controller/helmcharts/update/Chart.yaml
  odim-controller/helmcharts/update/values.yaml
  odim-controller/helmcharts/urplugin/urplugin/Chart.yaml
  odim-controller/helmcharts/urplugin/urplugin/values.yaml
  odim-controller/odimra/group_vars/all/all.yaml
Labels: prio:normal

#1258 enable event service in case if the property set to false while adding server
  svc-aggregation/system/addcompute.go
  svc-aggregation/system/addcompute_test.go
  svc-aggregation/system/reset_test.go
Labels: type:feature, prio:normal, status:in-progress

#1259 Update dmtf model for Port to match latest schema
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/common.go
  lib-dmtf/model/port.go
  lib-dmtf/model/power.go
  lib-dmtf/model/task.go
  lib-dmtf/model/telemetry.go
  lib-dmtf/model/thermal.go
Labels: type:bug, prio:normal, status:in-progress

#1262 Update data type of ConfiguredLinkSpeedGbps
  lib-dmtf/model/port.go
Labels: type:bug

#1255 Fixed password update issue on BMC
  lib-utilities/proto/managers/managers.proto
  svc-api/rpc/fakeStruct_testfile.go
  svc-managers/managers/common.go
  svc-managers/managers/managers.go
  svc-managers/mgrcommon/common.go
  svc-managers/mgrmodel/device.go
  svc-managers/mgrmodel/device_test.go
  svc-managers/rpc/manager.go
  svc-task/tcommon/common.go
  svc-task/thandle/thandle.go
  svc-task/thandle/tmonitor.go
  svc-task/tmodel/tmodel.go
Labels: type:bug, prio:normal, status:in-progress

#1261 Update GetRemoteAccountService response to match latest schema
  lib-dmtf/model/Chassis.go
  lib-dmtf/model/accountService.go
  lib-dmtf/model/common.go
  lib-dmtf/model/port.go
  lib-dmtf/model/power.go
  lib-dmtf/model/task.go
  lib-dmtf/model/telemetry.go
  lib-dmtf/model/thermal.go
  lib-utilities/common/constants.go
  svc-managers/managers/managers.go
Labels: type:bug, prio:normal, status:in-progress

#1263 reset API taskmon update failure: dns is converted to ip while saving the task data in db
  lib-utilities/common/common.go
  lib-utilities/common/common_test.go
  svc-events/evcommon/common.go
  svc-events/events/deletesubscription.go
  svc-events/events/deletesubscription_test.go
  svc-events/events/evtsubscription.go
  svc-events/events/evtsubscription_test.go
  svc-systems/systems/reset.go
Labels: type:bug, prio:normal, status:in-progress

#1266 Fixed extra spaces in codeblock, fixed bulleting and broken links in TOC
  docs/README.md
Labels: prio:normal, status:in-progress, type:doc

#1267 Updated GitHub action workflow details URL
  README.md
Labels: prio:normal, status:in-progress, type:doc

#1268 bugfix - device subscription is not saved while adding server
  svc-events/events/evtsubscription.go
Labels: type:bug, prio:normal, status:in-progress

#1269 Reduce duplicate code % for svc-account-session
  svc-account-session/account/create.go
  svc-account-session/account/create_test.go
  svc-account-session/account/delete.go
  svc-account-session/account/delete_test.go
  svc-account-session/account/getaccounts.go
  svc-account-session/account/getaccounts_test.go
  svc-account-session/account/update.go
  svc-account-session/account/update_test.go
  svc-account-session/asmodel/privilege.go
  svc-account-session/asmodel/redfishroles.go
  svc-account-session/asmodel/sessions.go
  svc-account-session/asmodel/userRole.go
  svc-account-session/asresponse/accounts.go
  svc-account-session/asresponse/error.go
  svc-account-session/asresponse/privilege.go
  svc-account-session/asresponse/session.go
  svc-account-session/role/create.go
  svc-account-session/role/create_test.go
  svc-account-session/role/delete.go
  svc-account-session/role/delete_test.go
  svc-account-session/role/getroles.go
  svc-account-session/role/getroles_test.go
  svc-account-session/role/update.go
  svc-account-session/role/update_test.go
  svc-account-session/rpc/account.go
  svc-account-session/rpc/auth.go
  svc-account-session/rpc/role.go
  svc-account-session/rpc/sessions.go
  svc-account-session/session/create_test.go
  svc-account-session/session/delete.go
  svc-account-session/session/delete_test.go
  svc-account-session/session/getsession.go
  svc-account-session/session/getsession_test.go
Labels: type:techdebt, prio:low, status:in-progress
